import { test, expect } from './fixtures';
import { closeTopOverlay, exportJson, fillRegister, importText, openApp, openDetail, openExport, openRegister, register, removeAgent, row, total } from './helpers';

test.beforeEach(async ({ page }) => openApp(page));

test('14.1 in_memory_reload_resets_coherently', async ({ page }) => {
  await register(page); await page.getByRole('checkbox',{name:'Idle'}).check(); await openDetail(page,'Delta Signal'); await page.reload(); await expect(page.locator('.agent-row')).toHaveCount(9); await expect(page.locator('.status-filter input:checked')).toHaveCount(0); await expect(page.locator('.detail-panel')).toHaveCount(0); await expect(page.getByRole('button',{name:'Undo registry mutation'})).toBeDisabled();
});
test('14.2 status_filter_union_proves_live', async ({ page }) => {
  await page.getByRole('checkbox',{name:'Idle'}).check(); const idle = await page.locator('.agent-row').allTextContents(); await page.getByRole('checkbox',{name:'Offline'}).check(); const union = await page.locator('.agent-row').allTextContents(); expect(union.length).toBeGreaterThan(idle.length); expect(idle.every((text)=>union.includes(text))).toBe(true); await page.getByRole('checkbox',{name:'Idle'}).uncheck(); await page.getByRole('checkbox',{name:'Offline'}).uncheck(); await expect(page.locator('.agent-row')).toHaveCount(9);
});
test('14.3 export_derived_view_tracks_mutations', async ({ page }) => {
  const before = await exportJson(page); await closeTopOverlay(page); await register(page); const after = await exportJson(page); expect(after.agents.length-before.agents.length).toBe(1); expect(after.rollup.total-before.rollup.total).toBe(1);
});
test('14.4 cross_view_row_panel_export_echo', async ({ page }) => {
  const panel = await openDetail(page,'Boreal Echo'); await panel.getByRole('button',{name:'Edit'}).click(); const modal=page.locator('.cds--modal-container').filter({hasText:'Update the API configuration'}); await modal.getByLabel('Name').fill('Boreal Echo Prime'); await modal.getByRole('button',{name:'Save changes'}).click(); await expect(row(page,'Boreal Echo Prime')).toHaveCount(1); await expect(panel).toContainText('Boreal Echo Prime'); await page.keyboard.press('Escape'); const data=await exportJson(page); expect(data.agents.some((a:any)=>a.name==='Boreal Echo Prime')).toBe(true);
});
test('14.5 rollup_count_delta_exact', async ({ page }) => { const before=Number(await total(page).textContent()); await register(page); expect(Number(await total(page).textContent())-before).toBe(1); });
test('14.6 different_agents_different_export', async ({ page }) => { await register(page,'Delta Signal'); await register(page,'Echo Signal','Cinder','Quill','echo_signal_key_2026'); const data=await exportJson(page); expect(data.agents.map((a:any)=>a.name)).toEqual(expect.arrayContaining(['Delta Signal','Echo Signal'])); });
test('14.7 interleaved_register_and_run', async ({ page }) => { let modal=await openRegister(page); await modal.getByLabel('Name').fill('Canceled Agent'); await modal.getByRole('button',{name:'Cancel'}).click(); const running=row(page,'Boreal Echo'); await running.getByRole('button',{name:'Start run'}).click(); modal=await openRegister(page); await page.waitForTimeout(1100); await modal.getByRole('button',{name:'Cancel'}).click(); await register(page); await expect(running).toContainText(/Running|Idle/); await expect(row(page,'Delta Signal')).toHaveCount(1); const panel=await openDetail(page,'Boreal Echo'); await panel.getByRole('tab',{name:'Activity'}).click(); await expect(panel.locator('.step-row.status-complete')).toBeVisible(); });
test('14.8 empty_then_repopulate_tracks_export', async ({ page }) => { for(const name of ['Aster Finch','Boreal Echo','Cinder Vale','Aster Drift','Boreal Sable','Cinder Nova','Aster Rune','Boreal Kite','Cinder Loom']) await removeAgent(page,name); await expect(page.getByText('No agents registered')).toBeVisible(); let data=await exportJson(page); expect(data.agents).toEqual([]); await closeTopOverlay(page); await register(page); await expect(total(page)).toHaveText('1'); data=await exportJson(page); expect(data.agents.map((a:any)=>a.name)).toEqual(['Delta Signal']); });
test('14.9 undo_round_trip_restores_export', async ({ page }) => { await removeAgent(page,'Boreal Kite'); let data=await exportJson(page); expect(data.agents.some((a:any)=>a.name==='Boreal Kite')).toBe(false); await closeTopOverlay(page); await page.getByRole('button',{name:'Undo registry mutation'}).click(); await expect(row(page,'Boreal Kite')).toHaveCount(1); data=await exportJson(page); expect(data.agents.some((a:any)=>a.name==='Boreal Kite')).toBe(true); });
test('14.10 export_import_reconstructs_state', async ({ page }) => { await register(page); const data=await exportJson(page); await closeTopOverlay(page); await removeAgent(page,'Delta Signal'); const modal=await importText(page,JSON.stringify(data)); await modal.getByRole('button',{name:'Import fleet'}).click(); await expect(row(page,'Delta Signal')).toHaveCount(1); await expect(total(page)).toHaveText(String(data.rollup.total)); });
