import { test, expect } from './fixtures';
import { closeTopOverlay, exportJson, fillRegister, importText, openApp, openRegister, register, removeAgent, row, total } from './helpers';
test.beforeEach(async({page})=>openApp(page));

test('4.1 empty_registry_or_filter_empty_state',async({page})=>{await row(page,'Boreal Sable').getByRole('button',{name:'Retry'}).click();await page.getByRole('checkbox',{name:'Error'}).check();await expect(page.getByText('No agents match the active filter')).toBeVisible();await expect(page.getByRole('button',{name:'Clear filter'})).toBeVisible();});
test('4.2 field_contract_inline_validation',async({page})=>{const modal=await openRegister(page);for(const [field,value,message,id] of [['Name','A','Name must be 2 to 40 characters','#agent-name-error-msg'],['Name','X'.repeat(41),'Name must be 2 to 40 characters','#agent-name-error-msg'],['Access key','K'.repeat(15),'Access key must be 16 to 64 characters','#agent-access-key-error-msg'],['Access key','K'.repeat(65),'Access key must be 16 to 64 characters','#agent-access-key-error-msg'],['Access key','invalid key value','Access key may use only letters','#agent-access-key-error-msg']]){await modal.getByLabel(field).fill(value);await expect(modal.locator(id)).toContainText(message);}await fillRegister(page,modal);await modal.getByLabel('Name').fill('aster finch');await expect(modal.locator('#agent-name-error-msg')).toContainText('Name must be unique');await expect(page.locator('.agent-row')).toHaveCount(9);});
test('4.3 errors_name_field_and_rule',async({page})=>{const modal=await openRegister(page);await modal.getByLabel('Access key').fill('bad key');await expect(modal.getByText(/Access key must be 16 to 64 characters|Access key may use only/).first()).toBeVisible();});
test('4.4 toasts_after_mutations_and_export',async({page,context})=>{await context.grantPermissions(['clipboard-write']);await register(page);await expect(page.getByLabel('Notifications')).toContainText('Delta Signal registered');await page.getByRole('button',{name:'Export fleet'}).first().click();await page.getByRole('button',{name:'Copy'}).click();await expect(page.getByLabel('Notifications')).toContainText('Fleet JSON copied');});
test('4.5 run_steps_show_progress_feedback',async({page})=>{await row(page,'Boreal Echo').getByRole('button',{name:'Start run'}).click();await row(page,'Boreal Echo').click();await page.getByRole('tab',{name:'Activity'}).click();await expect(page.locator('.step-row')).toHaveCount(5);const progress=page.getByText(/\d of 5 steps complete/);const before=await progress.textContent();await expect.poll(()=>progress.textContent()).not.toBe(before);});
test('4.6 remove_confirm_and_undo',async({page})=>{await removeAgent(page,'Boreal Kite');await expect(page.getByRole('button',{name:'Undo registry mutation'})).toBeEnabled();await page.getByRole('button',{name:'Undo registry mutation'}).click();await expect(row(page,'Boreal Kite')).toHaveCount(1);});
test('4.7 cancel_and_double_submit_safe',async({page})=>{let modal=await openRegister(page);await modal.getByRole('button',{name:'Cancel'}).click();await expect(page.locator('.agent-row')).toHaveCount(9);modal=await openRegister(page);await fillRegister(page,modal);await modal.getByRole('button',{name:'Register Agent'}).dblclick();await expect(row(page,'Delta Signal')).toHaveCount(1);});
test('4.8 import_rejects_malformed_contract',async({page})=>{await register(page);const before=await page.locator('.agent-row strong').allTextContents();await page.getByRole('button',{name:'Undo registry mutation'}).click();await page.getByRole('button',{name:'Redo registry mutation'}).click();const modal=await importText(page,'{bad');await expect(modal.locator('#fleet-json-import-error-msg')).toHaveText('Import JSON is malformed');await expect(page.locator('.agent-row strong')).toHaveText(before);await modal.getByRole('button',{name:'Cancel'}).click();await expect(page.getByRole('button',{name:'Undo registry mutation'})).toBeEnabled();});
test('4.9 empty_undo_redo_disabled',async({page})=>{await expect(page.getByRole('button',{name:'Undo registry mutation'})).toBeDisabled();await expect(page.getByRole('button',{name:'Redo registry mutation'})).toBeDisabled();await expect(page.locator('.agent-row')).toHaveCount(9);});
test('4.10 palette_escape_no_mutation',async({page})=>{await page.keyboard.press('Control+K');await expect(page.locator('.palette-modal')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.palette-modal')).toHaveCount(0);await expect(page.locator('.agent-row')).toHaveCount(9);});
test('4.11 pause_all_idle_selection_noop',async({page})=>{for(const name of ['Boreal Echo','Cinder Nova'])await page.getByRole('checkbox',{name:`Select ${name}`}).check();await expect(page.getByRole('button',{name:'Pause All'})).toBeDisabled();await expect(row(page,'Boreal Echo')).toContainText('Idle');await expect(row(page,'Cinder Nova')).toContainText('Offline');});
test('4.12 export_empty_agents_compiles',async({page})=>{for(const name of ['Aster Finch','Boreal Echo','Cinder Vale','Aster Drift','Boreal Sable','Cinder Nova','Aster Rune','Boreal Kite','Cinder Loom'])await removeAgent(page,name);const data=await exportJson(page);expect(data.agents).toEqual([]);expect(data.rollup).toEqual({idle:0,running:0,paused:0,error:0,offline:0,total:0});});
