import { test, expect } from './fixtures';
import { closeTopOverlay, importText, openApp, openExport, register, row } from './helpers';
// NOT-AUTOMATABLE:
// - 9.5 seeded_registry_renders_smoothly — "perceived hitching" has no deterministic frame-time budget in the criterion.
// - 9.9 no_layout_thrash_on_ticks — visual jank depends on host/GPU scheduling and lacks a measurable threshold.
test.beforeEach(async({page})=>openApp(page));
test('9.1 cold_start_under_two_seconds',async({page})=>{const start=Date.now();await page.reload();await expect(page.locator('.agent-row')).toHaveCount(9);expect(Date.now()-start).toBeLessThan(2000);});
test('9.2 console_clean_full_exercise',async({page})=>{await row(page,'Aster Finch').getByRole('button',{name:'Pause'}).click();await openExport(page);await closeTopOverlay(page);const modal=await importText(page,'{bad');await page.waitForTimeout(1100);await expect(modal.locator('#fleet-json-import-error-msg')).toHaveText('Import JSON is malformed');});
test('9.3 ui_stays_responsive_under_runs',async({page})=>{for(const name of ['Boreal Echo','Boreal Kite'])await row(page,name).getByRole('button',{name:'Start run'}).click();const start=Date.now();await page.getByRole('checkbox',{name:'Running'}).check();await page.getByRole('checkbox',{name:'Running'}).uncheck();await row(page,'Aster Finch').click();await expect(page.locator('.detail-panel')).toBeVisible();expect(Date.now()-start).toBeLessThan(2000);});
test('9.4 run_progress_shows_live_feedback',async({page})=>{await row(page,'Boreal Echo').getByRole('button',{name:'Start run'}).click();await row(page,'Boreal Echo').click();await page.getByRole('tab',{name:'Activity'}).click();const label=page.getByText(/\d of 5 steps complete/);const before=await label.textContent();await expect.poll(()=>label.textContent()).not.toBe(before);});
test('9.6 rapid_filter_no_dropped_input',async({page})=>{for(let i=0;i<5;i++){await page.getByRole('checkbox',{name:'Idle'}).check();await expect(page.getByRole('checkbox',{name:'Idle'})).toBeChecked();await page.getByRole('checkbox',{name:'Idle'}).uncheck();await page.getByRole('checkbox',{name:'Select Boreal Echo'}).check();await page.getByRole('checkbox',{name:'Select Boreal Echo'}).uncheck();}await expect(page.locator('.agent-row')).toHaveCount(9);});
test('9.7 export_reopen_stays_snappy',async({page})=>{await register(page);for(let i=0;i<3;i++){const start=Date.now();await openExport(page);await expect(page.locator('.json-preview')).toContainText('Delta Signal');expect(Date.now()-start).toBeLessThan(2000);await closeTopOverlay(page);}});
test('9.8 undo_redo_responsive',async({page})=>{await register(page);const start=Date.now();for(let i=0;i<3;i++){await page.getByRole('button',{name:'Undo registry mutation'}).click();await page.getByRole('button',{name:'Redo registry mutation'}).click();}expect(Date.now()-start).toBeLessThan(2000);await expect(row(page,'Delta Signal')).toHaveCount(1);});
test('9.10 import_parse_feedback_timely',async({page})=>{const start=Date.now();const modal=await importText(page,'{bad');await expect(modal.locator('#fleet-json-import-error-msg')).toHaveText('Import JSON is malformed');expect(Date.now()-start).toBeLessThan(2000);});
