<script lang="ts">
    import {fade, fly} from "svelte/transition";
    import type {PreviewState} from "$lib/stores/import.svelte";

    interface Props {
        parsed?: boolean | PreviewState["parsed"];
        parsedDiff?: PreviewState["parsedDiff"];
        parseError?: boolean;
        text?: string | null;
        showEmptyState?: boolean;
        clampHeight?: boolean;
    }

    const {parsed = true, parsedDiff, parseError, text, showEmptyState = true, clampHeight = false}: Props = $props();

    interface ConfigLine {
        id: string;
        key: string;
        value: string;
    }

    // Flat, stably-keyed line list so an entering override animates in and a removed one
    // animates out in place, without surrounding lines jumping mid-transition.
    const lines = $derived.by((): ConfigLine[] => {
        if (!parsedDiff) return [];
        const out: ConfigLine[] = [];
        for (const [key, value] of Object.entries(parsedDiff)) {
            if (Array.isArray(value)) {
                value.forEach((entry, index) => out.push({id: `${key}=${entry}#${index}`, key, value: String(entry)}));
            }
            else {
                out.push({id: `${key}=${value}`, key, value: String(value)});
            }
        }
        return out;
    });

    const hasDiff = $derived(lines.length > 0);
</script>

<div class="preview" class:clamped={clampHeight}>
    {#if parsed}
        {#if hasDiff}
            <div class="row p2"># Config generated by Ghostty Config</div>
            <div class="row p2"># https://ghostty.zerebos.com</div>
        {:else if showEmptyState}
            <div class="row p2"># No changes to the default config yet</div>
        {/if}
        <div class="row">&nbsp;</div>

        {#if parsedDiff}
            {#each lines as line (line.id)}
                <div class="row" in:fly={{x: -8, duration: 220}} out:fade={{duration: 200}}>
                    <span class="p4">{line.key}</span> = <span class="p5">{line.value}</span>
                </div>
            {/each}
        {/if}
    {:else}
        {#if parseError}
            <div class="row p2"># Could not parse config structure. Showing raw text:</div>
            <div class="row">&nbsp;</div>
        {/if}
        {#each (text ?? "").split("\n") as line, i (i)}
            <div class="row">{line}</div>
        {/each}
    {/if}
</div>



<style>
.preview {
    background: var(--config-bg);
    font-family: var(--config-font-family);
    font-size: var(--config-font-size);
    color: var(--config-fg);
    min-height: 175px;
    overflow-y: auto;
    padding: 8px;
    border-radius: var(--radius-level-3);
    border: 1px solid rgba(0, 0, 0, 0.5);
    box-shadow: 0 0 1px rgba(255, 255, 255, 0.5) inset;
    flex: 1;
    user-select: text;
}

.preview.clamped {
    min-height: 80px;
    max-height: 280px;
}

.preview .row {
    display: block;
    white-space: pre;
}

.p2 {color: var(--config-palette-2);}
.p4 {color: var(--config-palette-4);}
.p5 {color: var(--config-palette-5);}

@media (prefers-reduced-motion: reduce) {
    .preview .row {
        transition: none;
    }
}
</style>
