// Seed collection + bundled historical colour-name dataset.
// Everything here is local, deterministic, and loaded synchronously — no
// network requests at runtime.

export const PERIODS = [
  'Abstract + Geometric',
  'Americana',
  'Baroque to Neoclassical',
  'Expressionism',
  'Fauvism',
  'Impressionism',
  'Medieval',
  'Modern',
  'Old Masters',
  'Post-Impressionism',
  'Primitive + Folk',
  'Realism',
  'Romanticism',
  'Symbolism',
  'Tonalism',
];

// 9 seeded palettes (≥ 6 required). Notes are markdown provenance text.
export const SEED_PALETTES = [
  {
    id: 'p-starry-night',
    name: 'The Starry Night',
    artist: 'Vincent van Gogh',
    period: 'Post-Impressionism',
    swatches: ['#0F1B33', '#1C3A6E', '#2E5FA3', '#F2D877', '#E8B94D'],
    favorite: true,
    tags: ['night sky', 'impasto'],
    notes:
      '## Saint-Rémy, June 1889\n\nPulled from the **thick impasto** of the night sky over the asylum garden.\n\n- Cobalt and ultramarine laid wet over Prussian ground\n- Indian yellow halos around the morning star',
    archived: false,
  },
  {
    id: 'p-water-lilies',
    name: 'Water Lilies',
    artist: 'Claude Monet',
    period: 'Impressionism',
    swatches: ['#3E5F7A', '#5B7C99', '#7C9A6D', '#A8C3A0', '#DCE8E2'],
    favorite: false,
    tags: ['garden', 'water'],
    notes: 'Giverny pond studies, 1899 — the greens are **viridian mixtures** brushed over a cool grey ground.',
    archived: false,
  },
  {
    id: 'p-the-scream',
    name: 'The Scream',
    artist: 'Edvard Munch',
    period: 'Expressionism',
    swatches: ['#2F3E4E', '#6E8CA8', '#B3342B', '#E07B39', '#F2C879'],
    favorite: true,
    tags: ['anguish', 'fjord'],
    notes: 'The fjord at Ekeberg, 1893 — **blood red** tempera streaks over waxy crayon, reported by the artist as the sky itself screaming.',
    archived: false,
  },
  {
    id: 'p-composition-viii',
    name: 'Composition VIII',
    artist: 'Wassily Kandinsky',
    period: 'Abstract + Geometric',
    swatches: ['#121212', '#3A5BA0', '#E4572E', '#E8C547', '#F3EDE2'],
    favorite: false,
    tags: ['geometric', 'bauhaus'],
    notes: 'Bauhaus period, 1923. The circles carry **synesthetic weight** — Kandinsky taught that yellow sounds a trumpet, blue a cello.',
    archived: false,
  },
  {
    id: 'p-the-milkmaid',
    name: 'The Milkmaid',
    artist: 'Johannes Vermeer',
    period: 'Baroque to Neoclassical',
    swatches: ['#2C4A7C', '#8C6D46', '#B3342B', '#C9A227', '#E5DCC8'],
    favorite: false,
    tags: ['domestic', 'delft'],
    notes: 'Delft, c. 1658. Vermeer’s **pointillé highlights** — tiny dots of lead white — soften the crust of the bread.',
    archived: false,
  },
  {
    id: 'p-grande-jatte',
    name: 'A Sunday on La Grande Jatte',
    artist: 'Georges Seurat',
    period: 'Post-Impressionism',
    swatches: ['#2C3E50', '#4E7936', '#7A4E8C', '#9DB86D', '#E8D9A0'],
    favorite: false,
    tags: ['pointillism', 'park'],
    notes: 'Optical mixing, 1886 — complementary dots of **violet and chartreuse** meant to blend in the viewer’s eye at three metres.',
    archived: false,
  },
  {
    id: 'p-american-gothic',
    name: 'American Gothic',
    artist: 'Grant Wood',
    period: 'Americana',
    swatches: ['#2E2A24', '#6B4A2E', '#8A9B6E', '#B5BFC9', '#C8B89A'],
    favorite: false,
    tags: ['midwest'],
    notes: 'Eldon, Iowa, 1930. The overalls are a **single tube of Prussian blue** stretched with white across both figures.',
    archived: false,
  },
  {
    id: 'p-persistence-of-memory',
    name: 'The Persistence of Memory',
    artist: 'Salvador Dalí',
    period: 'Modern',
    swatches: ['#333B45', '#4A5A6A', '#8C7355', '#C9A86A', '#E3D5B8'],
    favorite: false,
    tags: ['surrealism'],
    notes: 'Port Lligat, 1931. The melting watches sit on **Cadaqués sand tones** warmed by a late afternoon light.',
    archived: false,
  },
  {
    id: 'p-ghent-altarpiece',
    name: 'The Ghent Altarpiece',
    artist: 'Jan van Eyck',
    period: 'Medieval',
    swatches: ['#29527A', '#3B2F2F', '#5E7C4A', '#8C2F39', '#D4AF37'],
    favorite: false,
    tags: ['altarpiece', 'gilded'],
    notes: '### Pigment analysis, 2019\n\nThe restoration confirmed **lapis lazuli** for the Madonna’s robe, ground coarsely so the stone itself seems to glow beneath the oil.',
    archived: false,
  },
];

// Bundled historical colour-name dataset, in the tradition of Werner's
// Nomenclature of Colours (1821). Each hex is matched to its nearest entry.
export const COLOR_NAMES = [
  { hex: '#FDFDFB', name: 'Snow White', note: 'The purest white, named for freshly fallen snow.' },
  { hex: '#F5F1E6', name: 'Milk White', note: 'A soft warm white, as in unbleached linen grounds.' },
  { hex: '#F2EDE6', name: 'Greyish White', note: 'White tempered with a breath of grey, common in primed canvases.' },
  { hex: '#F6F1D7', name: 'Yellowish White', note: 'A pale ivory white with a waxen warmth.' },
  { hex: '#F1E9D2', name: 'Cream White', note: 'The yellowed white of aged varnish and vellum.' },
  { hex: '#E7E4D8', name: 'Eggshell White', note: 'A chalky white with the faintest green undertone.' },
  { hex: '#D8D6CB', name: 'Cloudy White', note: 'White dulled as though seen through gauze.' },
  { hex: '#C9C7BC', name: 'Pearl Grey', note: 'A lustrous grey like the inside of a shell.' },
  { hex: '#B2BEB5', name: 'Ash Grey', note: 'The cool grey of settled wood ash.' },
  { hex: '#9BA19A', name: 'Sage Grey', note: 'A green-tinged grey borrowed from dried herbs.' },
  { hex: '#8C8C84', name: 'Mouse Grey', note: 'A soft neutral grey, named for the field mouse.' },
  { hex: '#736F64', name: 'Smoke Grey', note: 'Grey of woodsmoke hanging in still air.' },
  { hex: '#6B6E73', name: 'Storm Grey', note: 'The flat grey of an approaching squall.' },
  { hex: '#4E5257', name: 'Iron Grey', note: 'A hard metallic grey like forged tools.' },
  { hex: '#3A3D42', name: 'Charcoal Grey', note: 'Deep grey of burnt willow drawing sticks.' },
  { hex: '#2B2D31', name: 'Slate Black', note: 'Near black with a blue cast, like split slate.' },
  { hex: '#16181B', name: 'Jet Black', note: 'The deepest black, named for polished jet stone.' },
  { hex: '#241E20', name: 'Velvet Black', note: 'A lightless black that drinks the brush.' },
  { hex: '#292429', name: 'Ivory Black', note: 'A warm brown-black ground from calcined bone.' },
  { hex: '#1C2431', name: 'Bluish Black', note: 'Black deepened with indigo, for night skies.' },
  { hex: '#232A22', name: 'Greenish Black', note: 'Black shadowed with viridian, used in deep foliage.' },
  { hex: '#3B2F2F', name: 'Warm Umber Black', note: 'A brown-black earth tone for shaded flesh.' },
  { hex: '#8FA6C4', name: 'Dove Blue', note: 'A tender grey-blue of a dove’s neck.' },
  { hex: '#9DB4C0', name: 'Misty Blue', note: 'Blue thinned by morning haze over water.' },
  { hex: '#73B2D6', name: 'Sky Blue', note: 'The clear blue of a high summer sky.' },
  { hex: '#6FA8DC', name: 'Azure Blue', note: 'A bright heavenly blue, once ground from smalt.' },
  { hex: '#2E5FA3', name: 'Cobalt Blue', note: 'A saturated glass-blue introduced to painters in 1802.' },
  { hex: '#0047AB', name: 'Cerulean Blue', note: 'A vivid sky-blue pigment of tin and cobalt oxides.' },
  { hex: '#1C3A6E', name: 'Ultramarine Blue', note: 'Lapis lazuli, once costlier than gold leaf.' },
  { hex: '#1B3153', name: 'Prussian Blue', note: 'The first modern synthetic pigment, discovered by accident in 1704.' },
  { hex: '#274060', name: 'Indigo Blue', note: 'Dye-vat blue imported along the spice routes.' },
  { hex: '#1034A6', name: 'Egyptian Blue', note: 'The oldest manufactured pigment, fired from sand and copper.' },
  { hex: '#545AA7', name: 'Bluish Purple', note: 'A cool violet leaning towards indigo.' },
  { hex: '#967BB6', name: 'Lavender Purple', note: 'A pale violet named for the dried flower.' },
  { hex: '#6A4E7E', name: 'Violet Purple', note: 'The bishop’s violet of medieval vestments.' },
  { hex: '#773C6C', name: 'Mulberry Purple', note: 'A wine-dark purple from crushed mulberries.' },
  { hex: '#673147', name: 'Plum Purple', note: 'A browned purple of overripe plums.' },
  { hex: '#4A2C5E', name: 'Royal Purple', note: 'Tyrian purple, once extracted from sea snails by the thousand.' },
  { hex: '#E8B4A2', name: 'Salmon Pink', note: 'A warm pink of fresh salmon flesh.' },
  { hex: '#F1D9CF', name: 'Shell Pink', note: 'The faint pink of an empty scallop shell.' },
  { hex: '#DE9AA8', name: 'Rose Pink', note: 'A faded rose colour of tinted grounds.' },
  { hex: '#C08081', name: 'Venetian Pink', note: 'An earthy pink from red ochre and white lead.' },
  { hex: '#A85A64', name: 'Rosewood Red', note: 'A dusty red with the warmth of polished rosewood.' },
  { hex: '#E34234', name: 'Vermilion Red', note: 'Cinnabar red, the brilliant scarlet of illuminated manuscripts.' },
  { hex: '#D9381E', name: 'Scarlet Red', note: 'The blazing red of dyed wool and heraldic banners.' },
  { hex: '#C0272D', name: 'Arterial Blood Red', note: 'Werner’s vivid red, compared to fresh blood.' },
  { hex: '#B3342B', name: 'Red Lead', note: 'A fiery orange-red once used to protect iron and underline drawings.' },
  { hex: '#8C2F39', name: 'Brick Red', note: 'The baked red of kiln-fired clay.' },
  { hex: '#960018', name: 'Carmine Red', note: 'Cochineal lakes, crushed from insects on prickly pear.' },
  { hex: '#841432', name: 'Crimson Red', note: 'A deep ceremonial red of cardinals’ robes.' },
  { hex: '#7A1F2B', name: 'Wine Red', note: 'The dark red of mulled wine held to candlelight.' },
  { hex: '#E07B39', name: 'Reddish Orange', note: 'Ember orange of a cooling fire.' },
  { hex: '#D35400', name: 'Pumpkin Orange', note: 'A full-bodied autumn orange.' },
  { hex: '#E49B0F', name: 'Gamboge Yellow', note: 'A resinous orange-yellow tapped from gamboge trees.' },
  { hex: '#E8A012', name: 'Orange Yellow', note: 'The golden orange of marigold petals.' },
  { hex: '#F3D64F', name: 'Lemon Yellow', note: 'A cool sharp yellow like citrus rind.' },
  { hex: '#E3A008', name: 'Saffron Yellow', note: 'The precious yellow of crocus stamens.' },
  { hex: '#EDC773', name: 'Naples Yellow', note: 'A pale sunny yellow of lead antimonate.' },
  { hex: '#F2D877', name: 'Indian Yellow', note: 'A luminous glazing yellow once shipped in balls from Bengal.' },
  { hex: '#E7D8A7', name: 'Straw Yellow', note: 'The pale gold of threshed straw.' },
  { hex: '#EEDC9A', name: 'Wax Yellow', note: 'The mellow yellow of beeswax candles.' },
  { hex: '#C9A227', name: 'Yellow Ochre', note: 'An earth yellow dug since the cave painters.' },
  { hex: '#D4AF37', name: 'Gilded Gold', note: 'The warm sheen of beaten gold leaf.' },
  { hex: '#87A08B', name: 'Sage Green', note: 'A dry grey-green of the herb garden.' },
  { hex: '#A8C3A0', name: 'Pistachio Green', note: 'A pale milky green of fresh pistachios.' },
  { hex: '#9DB86D', name: 'Apple Green', note: 'The bright green of unripe orchard fruit.' },
  { hex: '#7C9A6D', name: 'Reed Green', note: 'A muted green of river reeds in late summer.' },
  { hex: '#5A6E2C', name: 'Sap Green', note: 'A yellowing green made from buckthorn berries.' },
  { hex: '#4E7936', name: 'Grass Green', note: 'The honest green of pasture in June.' },
  { hex: '#3E7C5B', name: 'Sea Green', note: 'The green of shallow water over dark sand.' },
  { hex: '#2E8B57', name: 'Emerald Green', note: 'A jewel green once made with deadly copper arsenite.' },
  { hex: '#43B3AE', name: 'Verdigris Green', note: 'The blue-green bloom of weathered bronze.' },
  { hex: '#1F4A38', name: 'Bottle Green', note: 'A deep glassy green of wine bottles.' },
  { hex: '#6B7436', name: 'Olive Green', note: 'A browned green of preserved olives.' },
  { hex: '#3E4E3A', name: 'Moss Green', note: 'The dark damp green of forest moss.' },
  { hex: '#C8B89A', name: 'Sand Yellow', note: 'The pale tan of wind-blown dunes.' },
  { hex: '#C9A86A', name: 'Amber Tan', note: 'A golden brown of fossilized resin.' },
  { hex: '#B5BFC9', name: 'Fog Grey', note: 'A blue-grey of harbour fog on cold mornings.' },
  { hex: '#E5DCC8', name: 'Parchment Tan', note: 'The warm pale tone of stretched animal skin.' },
  { hex: '#DCE8E2', name: 'Celadon White', note: 'A greenish white of glazed porcelain.' },
  { hex: '#8C6D46', name: 'Raw Umber', note: 'A cool brown earth pigment, raw and unburnt.' },
  { hex: '#8C7355', name: 'Fawn Brown', note: 'A soft brown of young deer coats.' },
  { hex: '#6B4A2E', name: 'Chestnut Brown', note: 'The russet brown of roasted chestnuts.' },
  { hex: '#6E5A3B', name: 'Bistre Brown', note: 'A sooty brown once made from chimney soot.' },
  { hex: '#5D4037', name: 'Sepia Brown', note: 'The cuttlefish brown of early photographs.' },
  { hex: '#53422E', name: 'Liver Brown', note: 'A dark reddish-brown of aged oak.' },
  { hex: '#4A3222', name: 'Burnt Umber', note: 'Umber roasted to a deeper chocolate brown.' },
  { hex: '#2E2A24', name: 'Van Dyke Brown', note: 'A near-black earth brown favoured by the Flemish.' },
  { hex: '#A9BA9D', name: 'Laurel Green', note: 'A grey-green of victor’s laurels.' },
  { hex: '#7A4E8C', name: 'Grape Purple', note: 'The dusty purple of wine grapes at harvest.' },
  { hex: '#333B45', name: 'Gunmetal Grey', note: 'A blue-black grey of oiled machinery.' },
  { hex: '#2C3E50', name: 'Midnight Blue', note: 'The last blue before the sky turns black.' },
  { hex: '#2C4A7C', name: 'Marine Blue', note: 'The deep blue of open water beyond the shoals.' },
  { hex: '#E3D5B8', name: 'Bone White', note: 'A weathered white of sun-bleached bone.' },
  { hex: '#F2C879', name: 'Honey Yellow', note: 'The amber glow of comb honey held to light.' },
  { hex: '#9BA8AB', name: 'Gull Grey', note: 'A pale grey of gulls against an overcast sea.' },
];
