/** NOT-AUTOMATABLE: none; animations are sampled during their real trigger paths. */
import { expect, gotoApp, openCreateDialog, openRepository, openTask, submitRun, test } from './fixtures'

test('4.1 hover_feedback_required', async ({ page }) => {
  await gotoApp(page)
  const button = page.getByRole('button', { name: 'Create task', exact: true }).first()
  const buttonBefore = await button.evaluate((element) => getComputedStyle(element).backgroundColor)
  await button.hover()
  await expect(button).toHaveClass(/is-hovered/)
  await expect.poll(() => button.evaluate((element) => getComputedStyle(element).backgroundColor)).not.toBe(buttonBefore)
  const nav = page.getByRole('button', { name: 'Timeline', exact: true })
  const navBefore = await nav.evaluate((element) => getComputedStyle(element).transform)
  await nav.hover()
  expect(await nav.evaluate((element) => getComputedStyle(element).transform)).not.toBe(navBefore)
  await openCreateDialog(page)
  const field = page.getByLabel('Pull-request number')
  await field.focus()
  expect(await field.evaluate((element) => getComputedStyle(element).boxShadow)).not.toBe('none')
})

test('4.2 create_dialog_enter_exit', async ({ page }) => {
  await gotoApp(page)
  const { dialog } = await openCreateDialog(page)
  const enter = await dialog.evaluate((element) => ({ name: getComputedStyle(element).animationName, duration: getComputedStyle(element).animationDuration }))
  expect(enter.name).toBe('dialogIn')
  expect(Number.parseFloat(enter.duration)).toBeGreaterThanOrEqual(0.2)
  expect(Number.parseFloat(enter.duration)).toBeLessThanOrEqual(0.3)
  await dialog.getByRole('button', { name: 'Close create task dialog' }).click()
  await expect(dialog).toHaveAttribute('data-state', 'closed')
  const exit = await dialog.evaluate((element) => ({ name: getComputedStyle(element).animationName, duration: getComputedStyle(element).animationDuration }))
  expect(exit.name).toBe('dialogOut')
  expect(Number.parseFloat(exit.duration)).toBeGreaterThanOrEqual(0.2)
})

test('4.3 run_and_timeline_microinteractions', async ({ page }) => {
  await gotoApp(page)
  const row = await submitRun(page, { pullRequestNumber: '991' })
  expect(await row.evaluate((element) => getComputedStyle(element).animationName)).toBe('rowIn')
  const running = row.locator('.stage-running')
  await expect(running).toBeVisible({ timeout: 2_000 })
  expect(await running.evaluate((element) => getComputedStyle(element).animationName)).toBe('stagePulse')
  await page.getByRole('button', { name: 'Timeline', exact: true }).click()
  const freshEvent = page.locator('.event-row').first()
  expect(await freshEvent.evaluate((element) => getComputedStyle(element).animationName)).toBe('eventIn')
  await openTask(page, 184)
  await page.getByRole('button', { name: /^bad-success ·/ }).click()
  expect(await page.locator('.trial-row').first().evaluate((element) => getComputedStyle(element).animationName)).toBe('fadeMove')
  expect(await page.locator('.dist-segment.active').evaluate((element) => getComputedStyle(element).transitionDuration)).not.toBe('0s')
})

test('4.4 log_disclosure_transition', async ({ page }) => {
  await openTask(page)
  const toggle = page.getByRole('button', { name: 'Log excerpt' }).first()
  await toggle.click()
  const disclosure = page.locator('.log-disclosure').first()
  await expect(disclosure).toBeVisible()
  expect(await disclosure.evaluate((element) => getComputedStyle(element).transitionProperty)).toContain('max-height')
  expect(await toggle.locator('svg').last().evaluate((element) => getComputedStyle(element).transform)).not.toBe('none')
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
})

test('4.6 toasts_slide_autodismiss', async ({ page }) => {
  await gotoApp(page)
  await submitRun(page, { pullRequestNumber: '992' })
  const toast = page.getByRole('status').filter({ hasText: 'Run started' })
  await expect(toast).toBeVisible()
  const animation = await toast.evaluate((element) => ({ name: getComputedStyle(element).animationName, duration: getComputedStyle(element).animationDuration }))
  expect(animation.name).toBe('toastLife')
  expect(Number.parseFloat(animation.duration)).toBeGreaterThan(4)
  await expect(toast).toBeHidden({ timeout: 5_000 })
})

test('4.7 reduced_motion_respected', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await gotoApp(page)
  const row = await submitRun(page, { pullRequestNumber: '993' })
  await expect(row.locator('.stage-running')).toBeVisible({ timeout: 2_000 })
  expect(await row.evaluate((element) => getComputedStyle(element).animationName)).toBe('none')
  expect(await row.locator('.stage-running').evaluate((element) => getComputedStyle(element).animationName)).toBe('none')
  await openTask(page, 184)
  const toggle = page.getByRole('button', { name: 'Log excerpt' }).first()
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: /^bad-success ·/ }).click()
  await expect(page.locator('.trial-row')).toHaveCount(1)
})
