/** NOT-AUTOMATABLE: none; all user flows have explicit action/postcondition paths. */
import {
  downloadJson, expect, fillCreateForm, gotoApp, openCreateDialog, openRepository,
  openTask, pipelineRows, readManifest, repositoryMetrics, submitRun, test, waitForAcceptedRun,
} from './fixtures'

test('6.1 create_task_advances_pipeline_and_metrics', async ({ page }) => {
  await gotoApp(page)
  const before = await repositoryMetrics(page)
  const row = await submitRun(page, { pullRequestNumber: '971', minFiles: '4', maxFiles: '12' })
  const generate = row.locator('.stage-cell').nth(3)
  await expect(generate).toHaveClass(/stage-failed/, { timeout: 6_000 })
  await expect(generate).toContainText('a1')
  await expect(generate).toContainText('a2', { timeout: 3_000 })
  await waitForAcceptedRun(page, '971')
  await page.getByRole('button', { name: 'Repositories', exact: true }).click()
  const after = await repositoryMetrics(page)
  expect(after.tasks).toBe(before.tasks + 1)
  expect(after.processed).toBe(before.processed + 1)
  expect(after.yieldPercent).toBe(Math.round(after.tasks / after.processed * 100))
  await page.getByRole('button', { name: 'Timeline', exact: true }).click()
  await expect(page.getByText('Task accepted').first()).toBeVisible()
  await page.getByRole('button', { name: 'Analytics', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Tasks per week' })).toBeVisible()
})

test('6.2 invalid_create_task_inline_validation', async ({ page }) => {
  await openRepository(page)
  const before = await pipelineRows(page).count()
  await openCreateDialog(page)
  const dialog = await fillCreateForm(page, { pullRequestNumber: 'not-a-number', minFiles: '50', maxFiles: '20' })
  await expect(dialog.getByText(/Pull-request number must/)).toBeVisible()
  await expect(dialog.getByText(/Minimum file bound must not exceed maximum/).first()).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Start pipeline run' })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Cancel' }).click()
  await expect(pipelineRows(page)).toHaveCount(before)
})

test('6.3 retry_resume_preserves_completed_stages', async ({ page }) => {
  await gotoApp(page)
  const row = await submitRun(page, { pullRequestNumber: '972' })
  const completedBeforeRetry: string[] = []
  const generate = row.locator('.stage-cell').nth(3)
  await expect(generate).toHaveClass(/stage-failed/, { timeout: 6_000 })
  for (let index = 0; index < 3; index += 1) {
    const stage = row.locator('.stage-cell').nth(index)
    await expect(stage).toHaveClass(/stage-complete/)
    completedBeforeRetry.push((await stage.getAttribute('title'))!)
  }
  await expect(generate).toContainText('a2', { timeout: 3_000 })
  for (let index = 0; index < 3; index += 1) await expect(row.locator('.stage-cell').nth(index)).toHaveAttribute('title', completedBeforeRetry[index])
})

test('6.4 verdict_filter_and_needs_review', async ({ page }) => {
  await openTask(page)
  await expect(page.getByText('Needs review', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^bad-success ·/ }).click()
  await expect(page.locator('.trial-row')).toHaveCount(1)
  await expect(page.locator('.verdict-chip')).toHaveText('bad-success')
  await page.getByRole('button', { name: 'Clear filter' }).click()
  await expect(page.locator('.trial-row')).toHaveCount(7)
})

test('6.5 repos_pipeline_detail_navigation_retains_state', async ({ page }) => {
  await openRepository(page)
  await page.getByRole('button', { name: 'Accepted', exact: true }).click()
  await expect.poll(() => pipelineRows(page).count()).toBe(3)
  const filteredCount = await pipelineRows(page).count()
  await page.getByRole('button', { name: /^Open pull request 184,/ }).click()
  const disclosure = page.getByRole('button', { name: 'Log excerpt' }).first()
  await disclosure.click()
  await page.getByRole('button', { name: 'quartz-orm pipeline' }).click()
  await expect(pipelineRows(page)).toHaveCount(filteredCount)
  await page.getByRole('button', { name: /^Open pull request 184,/ }).click()
  await expect(page.getByRole('button', { name: 'Log excerpt' }).first()).toHaveAttribute('aria-expanded', 'true')
})

test('6.6 empty_or_filtered_pipeline_empty_state', async ({ page }) => {
  await openRepository(page)
  await page.getByLabel('Search pull requests').fill('definitely-not-a-real-pr')
  await expect(page.getByRole('heading', { name: 'No pull requests match' })).toBeVisible()
  await expect(page.getByText(/Clear the current search or status filter/)).toBeVisible()
  await page.getByRole('button', { name: 'Clear filter' }).click()
  await expect(pipelineRows(page)).toHaveCount(9)
})

test('6.7 timeline_status_filter_coherence', async ({ page }) => {
  await gotoApp(page)
  await page.getByRole('button', { name: 'Timeline', exact: true }).click()
  const all = await page.locator('.event-row:visible').count()
  await page.getByRole('button', { name: 'failed', exact: true }).click()
  await expect.poll(() => page.locator('.event-row:visible').count()).toBeLessThan(all)
  const failed = await page.locator('.event-row:visible').count()
  expect(failed).toBeGreaterThan(0)
  expect(failed).toBeLessThan(all)
  await page.getByRole('button', { name: /^All ·/ }).click()
  await expect(page.locator('.event-row:visible')).toHaveCount(all)
})

test('6.8 analytics_and_timeline_chrome_continuity', async ({ page }) => {
  await gotoApp(page)
  await submitRun(page, { pullRequestNumber: '973' })
  await page.getByRole('button', { name: 'Timeline', exact: true }).click()
  await expect(page.getByText(/PR #973/).first()).toBeVisible({ timeout: 3_000 })
  await page.getByRole('button', { name: 'Analytics', exact: true }).click()
  const mark = page.locator('.recharts-pie-sector path').first()
  await mark.hover()
  await expect(page.locator('[data-chart-tooltip="true"]')).toBeVisible()
  await page.getByRole('button', { name: 'Repositories', exact: true }).click()
  await page.getByRole('button', { name: 'Open quartz-orm pipeline' }).click()
  await expect(page.getByRole('button', { name: /^Open pull request 973,/ })).toBeVisible()
})

test('6.9 create_and_manifest_overlays', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await gotoApp(page)
  const { dialog } = await openCreateDialog(page)
  await dialog.getByRole('button', { name: 'Cancel' }).click()
  await expect(dialog).toBeHidden()
  await openTask(page)
  await page.getByRole('button', { name: 'Copy', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Copied' })).toBeVisible()
  const downloaded = await downloadJson(page, 'Download task-manifest.json')
  expect(downloaded.pullRequestNumber).toBe(184)
  await page.getByRole('button', { name: 'quartz-orm pipeline' }).click()
  await expect(page.getByRole('heading', { name: 'quartz-orm' })).toBeVisible()
})

test('6.10 manifest_export_and_failed_create_recover', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await gotoApp(page)
  await openCreateDialog(page)
  const dialog = await fillCreateForm(page, { pullRequestNumber: 'bad', minFiles: '30', maxFiles: '20' })
  await expect(dialog.getByRole('button', { name: 'Start pipeline run' })).toBeDisabled()
  await fillCreateForm(page, { pullRequestNumber: '974', minFiles: '3', maxFiles: '13' })
  await dialog.getByRole('button', { name: 'Start pipeline run' }).click()
  await waitForAcceptedRun(page, '974')
  const visible = await readManifest(page)
  await page.getByRole('button', { name: 'Copy', exact: true }).click()
  expect(JSON.parse(await page.evaluate(() => navigator.clipboard.readText()))).toEqual(visible)
  expect(await downloadJson(page, 'Download task-manifest.json')).toEqual(visible)
})

test('6.11 manifest_export_after_accepted_create', async ({ page }) => {
  await gotoApp(page)
  await page.getByRole('button', { name: 'Timeline', exact: true }).click()
  const baseline = await downloadJson(page, 'Export accepted tasks')
  await page.getByRole('button', { name: 'Repositories', exact: true }).click()
  await submitRun(page, { pullRequestNumber: '975', minFiles: '5', maxFiles: '15' })
  await waitForAcceptedRun(page, '975')
  const firstManifest = await readManifest(page)
  expect(firstManifest).toMatchObject({ pullRequestNumber: 975, minFiles: 5, maxFiles: 15 })
  await submitRun(page, { pullRequestNumber: '976', minFiles: '6', maxFiles: '16' })
  await waitForAcceptedRun(page, '976')
  await page.getByRole('button', { name: 'Timeline', exact: true }).click()
  const after = await downloadJson(page, 'Export accepted tasks')
  expect(after).toHaveLength(baseline.length + 2)
  expect(after.map((manifest: any) => manifest.pullRequestNumber)).toEqual(expect.arrayContaining([975, 976]))
})
