import { COMPONENT_FIXTURES } from '../fixtures';

function generateCSS(storeState) {
  const { desktopLayout, tabletOverrides, mobileOverrides } = storeState;

  let css = `/* Generated by Constraint Forge */\n\n.layout-container {\n  display: grid;\n  grid-template-columns: repeat(12, 1fr);\n  grid-auto-rows: 8px;\n  gap: 16px;\n}\n\n`;

  // Desktop
  desktopLayout.forEach(comp => {
    if (comp.visibility === 'hidden') return;
    css += `.component-${comp.id} {\n`;
    if (comp.colStart) css += `  grid-column: ${comp.colStart} / span ${comp.colSpan};\n`;
    if (comp.rowStart) css += `  grid-row: ${comp.rowStart} / span ${comp.rowSpan};\n`;
    css += `}\n`;
  });

  // Tablet Override
  css += `\n@media (max-width: 1023px) {\n`;
  Object.entries(tabletOverrides).forEach(([id, override]) => {
    if (Object.keys(override).length === 0) return;
    css += `  .component-${id} {\n`;
    if (override.visibility) css += `    display: ${override.visibility === 'hidden' ? 'none' : 'block'};\n`;
    if (override.colStart || override.colSpan) css += `    grid-column: ${override.colStart || 'auto'} / span ${override.colSpan || 'auto'};\n`;
    if (override.rowStart || override.rowSpan) css += `    grid-row: ${override.rowStart || 'auto'} / span ${override.rowSpan || 'auto'};\n`;
    css += `  }\n`;
  });
  css += `}\n`;

  // Mobile Override
  css += `\n@media (max-width: 599px) {\n`;
  Object.entries(mobileOverrides).forEach(([id, override]) => {
    if (Object.keys(override).length === 0) return;
    css += `  .component-${id} {\n`;
    if (override.visibility) css += `    display: ${override.visibility === 'hidden' ? 'none' : 'block'};\n`;
    if (override.colStart || override.colSpan) css += `    grid-column: ${override.colStart || 'auto'} / span ${override.colSpan || 'auto'};\n`;
    if (override.rowStart || override.rowSpan) css += `    grid-row: ${override.rowStart || 'auto'} / span ${override.rowSpan || 'auto'};\n`;
    css += `  }\n`;
  });
  css += `}\n`;

  return css;
}

export function generateContract(storeState) {
  const css = generateCSS(storeState);

  return {
    schemaVersion: "responsive-layout-contract/v1",
    exportedAt: new Date().toISOString(),
    fixtures: COMPONENT_FIXTURES.map(f => f.id),
    desktopLayout: storeState.desktopLayout,
    tabletOverrides: storeState.tabletOverrides,
    mobileOverrides: storeState.mobileOverrides,
    semanticOrder: storeState.semanticOrder,
    contentPressure: storeState.contentPressure,
    cssChecksum: "stubbed-checksum", // Real hashing would go here
    generatedCSS: css,
    strategies: {
      a: storeState.strategyA,
      b: storeState.strategyB
    }
  };
}
