import { chromium } from '/usr/lib/node_modules/playwright/index.mjs'
import assert from 'node:assert/strict'

const browser = await chromium.connectOverCDP('http://127.0.0.1:9222')
const context = browser.contexts()[0]
const page = await context.newPage()
const errors = []
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
page.on('pageerror', (error) => errors.push(error.message))
await page.setViewportSize({ width: 1280, height: 900 })
await page.goto('http://127.0.0.1:3000', { waitUntil: 'networkidle' })

await page.locator('#taskDescription').fill('Explain the release to new users')
await page.locator('#outputFormat').selectOption('table')
await page.locator('#tone').selectOption('friendly')
await page.getByRole('button', { name: 'Generate prompt' }).click()
assert.match(await page.locator('.code-surface pre').textContent(), /Output format: Table[\s\S]*Tone: Friendly/)

await page.getByRole('button', { name: /One-Shot/ }).click()
await page.locator('#taskDescription').fill('Convert notes into actions')
await page.locator('#exampleInput').fill('Discuss launch date')
await page.locator('#expectedOutput').fill('Action: confirm launch date')
await page.getByRole('button', { name: 'Generate prompt' }).click()
assert.match(await page.locator('.code-surface pre').textContent(), /Discuss launch date[\s\S]*confirm launch date/)

await page.getByRole('button', { name: /Few-Shot/ }).click()
await page.getByRole('button', { name: /Remove example 1/ }).click()
assert.equal(await page.getByRole('button', { name: 'Generate prompt' }).isDisabled(), true)
assert.match(await page.getByText('At least one example is required.').textContent(), /At least one example/)
await page.getByRole('button', { name: 'Add example' }).click()

await page.getByRole('button', { name: /Outcome-Based/ }).click()
await page.locator('#goal').fill('Improve onboarding completion')
await page.locator('#successCriteria-0-text').fill('Completion rises by ten percent')
await page.getByRole('button', { name: 'Add success criterion' }).click()
await page.locator('#successCriteria-1-text').fill('Support tickets decrease')
await page.locator('#measurement').selectOption('percentage')
await page.getByRole('button', { name: 'Generate prompt' }).click()
assert.match(await page.locator('.code-surface pre').textContent(), /Completion rises[\s\S]*Support tickets decrease[\s\S]*Percentage/)

await page.getByRole('button', { name: /Role-Based/ }).click()
await page.locator('#role').fill('an accessibility specialist')
await page.locator('#audience').fill('frontend engineers')
await page.locator('#taskDescription').fill('Review this interface for keyboard risks')
await page.getByRole('button', { name: 'Add document' }).click()
await page.getByRole('option', { name: /api-reference.json/ }).click()
await page.getByRole('button', { name: 'Generate prompt' }).click()
assert.match(await page.locator('.code-surface pre').textContent(), /^You are an accessibility specialist/)
assert.match(await page.locator('.code-surface pre').textContent(), /api-reference.json/)

await page.getByRole('button', { name: /Constraint-Based/ }).click()
await page.locator('#taskDescription').fill('Draft a status update')
await page.locator('#constraints-0-type').selectOption('length')
await page.locator('#constraints-0-text').fill('Use fewer than 100 words')
await page.getByRole('button', { name: 'Add constraint' }).click()
await page.locator('#constraints-1-type').selectOption('format')
await page.locator('#constraints-1-text').fill('Use three bullets')
await page.getByRole('button', { name: 'Generate prompt' }).click()
assert.match(await page.locator('.code-surface pre').textContent(), /1\. \[Length\][\s\S]*2\. \[Format\]/)

await page.getByRole('button', { name: /Library 5/ }).click()
await page.getByRole('button', { name: 'Export library' }).click()
const json = await page.locator('.export-panel pre').textContent()
await page.getByRole('button', { name: /Delete Executive brief distiller/ }).click()
await page.waitForTimeout(200)
assert.equal(await page.locator('.nav-count').textContent(), '4')
await page.getByRole('button', { name: 'Import JSON' }).click()
await page.locator('#import-document-text').fill(json)
await page.waitForTimeout(100)
await page.getByRole('button', { name: 'Replace library' }).click()
await page.waitForTimeout(120)
assert.equal(await page.locator('.nav-count').textContent(), '5')
assert.equal(await page.locator('.row-copy strong', { hasText: 'Executive brief distiller' }).count(), 1)

assert.deepEqual(errors, [])
console.log(JSON.stringify({ ok: true, techniquesCovered: 7, importRoundTrip: true, consoleErrors: errors }))
await page.close()
process.exit(0)
