import { chromium } from '/usr/lib/node_modules/playwright/index.mjs'
import assert from 'node:assert/strict'

const browser = await chromium.connectOverCDP('http://127.0.0.1:9222')
const context = browser.contexts()[0] || await browser.newContext()
const page = await context.newPage()
const errors = []
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
page.on('pageerror', (error) => errors.push(error.message))

await page.goto('http://127.0.0.1:3000', { waitUntil: 'networkidle' })
assert.equal(await page.locator('.technique-item').count(), 7)
assert.match(await page.locator('.nav-count').textContent(), /5/)

await page.getByRole('button', { name: /Chain-of-Thought/ }).click()
await page.waitForTimeout(120)
assert.equal(await page.getByRole('button', { name: 'Generate prompt' }).isDisabled(), true)
assert.match(await page.locator('#goal-error-msg').textContent(), /Goal is required/i)
await page.locator('#goal').fill('Choose the strongest launch strategy')
await page.waitForTimeout(80)
assert.equal(await page.getByRole('button', { name: 'Generate prompt' }).isEnabled(), true)
await page.locator('#scratchpad').check({ force: true })
await page.getByRole('button', { name: 'Generate prompt' }).click()
assert.match(await page.locator('.code-surface pre').textContent(), /Think step by step/)

await page.getByRole('button', { name: /Few-Shot/ }).click()
await page.locator('#taskDescription').fill('Classify support requests by urgency')
await page.locator('#examples-0-input').fill('The service is down for everyone')
await page.locator('#examples-0-output').fill('Critical')
await page.getByRole('button', { name: 'Add example' }).click()
await page.locator('#examples-1-input').fill('How do I update my profile?')
await page.locator('#examples-1-output').fill('Low')
await page.getByRole('button', { name: 'Add document' }).click()
await page.getByRole('option', { name: /support-faq.txt/ }).click()
await page.getByRole('button', { name: 'Generate prompt' }).click()
const fewPrompt = await page.locator('.code-surface pre').textContent()
assert.match(fewPrompt, /service is down/)
assert.match(fewPrompt, /update my profile/)
assert.match(fewPrompt, /support-faq.txt/)
await page.getByRole('button', { name: 'Save to library' }).click()
await page.locator('#library-title').fill('Support urgency classifier')
await page.getByRole('button', { name: 'Save prompt', exact: true }).click()
await page.waitForTimeout(150)
assert.equal(await page.locator('.nav-count').textContent(), '6')
assert.match(await page.getByRole('button', { name: /Few-Shot/ }).textContent(), /Saved/)

await page.getByRole('button', { name: /Library 6/ }).click()
await page.getByRole('button', { name: 'Export library' }).click()
const exported = await page.locator('.export-panel pre').textContent()
assert.match(exported, /Support urgency classifier/)
assert.match(exported, /Classify support requests by urgency/)
assert.match(exported, /"schemaVersion": 1/)

await page.getByRole('button', { name: 'Open Executive brief distiller' }).first().click()
assert.match(await page.locator('#taskDescription').inputValue(), /Summarize the supplied executive brief/)
assert.match(await page.locator('.code-surface pre').textContent(), /Output format: Bullets/)

await page.getByRole('button', { name: /Role-Based/ }).click()
await page.locator('#role').fill('a research lead')
await page.getByRole('button', { name: /Zero-Shot/ }).click()
await page.locator('#taskDescription').fill('Retain this exact zero-shot draft')
await page.getByRole('button', { name: /Role-Based/ }).click()
assert.equal(await page.locator('#role').inputValue(), 'a research lead')
await page.getByRole('button', { name: /Zero-Shot/ }).click()
assert.equal(await page.locator('#taskDescription').inputValue(), 'Retain this exact zero-shot draft')

const webmcp = await page.evaluate(() => ({ info: window.webmcp_session_info(), list: window.webmcp_list_tools() }))
assert.equal(webmcp.info.contractVersion, 'zto-webmcp-v1')
assert.ok(webmcp.list.tools.length >= 20)
const webOpen = await page.evaluate(() => window.webmcp_invoke_tool('browse_open', { destination: 'constraint-based' }))
assert.equal(webOpen.ok, true)
assert.match(await page.locator('.technique-hero h1').textContent(), /Constraint-Based/)

await page.setViewportSize({ width: 375, height: 780 })
assert.equal(await page.locator('.mobile-technique').isVisible(), true)
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true)

console.log(JSON.stringify({ ok: true, consoleErrors: errors, webmcpTools: webmcp.list.tools.length }))
await page.close()
process.exit(0)
