/* NOT-AUTOMATABLE: 3.1, 3.2, 3.3 require subjective pixel-level comparison to reference screenshots; objective composition and typography invariants are covered in visual_design. */
import{assertClean,cards,clear,expect,gallery,load,paint,save,test,toolbar}from'./helpers.js'
test.beforeEach(async({page})=>load(page));test.afterEach(async({page})=>assertClean(page))
test('3.4 gallery_card_motion_matches_spec',async({page})=>{await save(page,'Motion Fidelity','Design');const c=cards(page).filter({hasText:'Motion Fidelity'});expect(await c.evaluate(e=>getComputedStyle(e).animationName)).toContain('card-enter');await c.getByRole('button',{name:'Delete Motion Fidelity'}).click();await c.getByRole('button',{name:'Confirm delete Motion Fidelity'}).click();await expect(c).toHaveClass(/is-deleting/);await expect(c).toHaveCount(0)})
test('3.5 narrow_toolbar_reflow_matches_spec',async({page})=>{await page.setViewportSize({width:375,height:844});expect(await toolbar(page).evaluate(e=>getComputedStyle(e).position)).toBe('relative');for(const n of['QR Brush','Color Brush','Eraser','Export','Import'])await expect(page.getByRole('button',{name:n,exact:n==='Export'||n==='Import'})).toBeVisible()})
test('3.6 toolbar_control_styling_matches',async({page})=>{const b=page.getByRole('button',{name:'Color Brush'}),s=await b.evaluate(e=>getComputedStyle(e));expect(parseFloat(s.height)).toBeGreaterThan(30);expect(s.borderStyle).not.toBe('none');expect(s.backgroundColor).not.toBe('rgba(0, 0, 0, 0)')})
test('3.7 title_vs_toolbar_hierarchy',async({page})=>{const title=Number(await page.getByRole('heading',{level:1}).evaluate(e=>parseFloat(getComputedStyle(e).fontSize))),label=Number(await page.getByRole('button',{name:'Color Brush'}).evaluate(e=>parseFloat(getComputedStyle(e).fontSize)));expect(title).toBeGreaterThan(label*3)})
test('3.8 component_states_match_spec',async({page})=>{const b=page.getByRole('button',{name:'Color Brush'}),before=await b.evaluate(e=>getComputedStyle(e).backgroundColor);await b.hover();await page.waitForTimeout(180);expect(await b.evaluate(e=>getComputedStyle(e).backgroundColor)).not.toBe(before);await b.focus();expect((await b.evaluate(e=>getComputedStyle(e).outlineStyle))).not.toBe('none');await paint(page,[0]);await expect(page.locator('.slider-wrap')).toHaveClass(/is-locked/);await clear(page)})
test('3.9 seven_swatches_and_qr_cells',async({page})=>{await expect(page.locator('.swatch')).toHaveCount(7);await paint(page,[0]);await expect(page.getByRole('gridcell').first()).toHaveCSS('background-image',/data:image/);await expect(page.getByRole('grid')).toHaveClass(/grid-on/)})
test('3.10 toolbar_controls_present_in_order',async({page})=>{const text=(await toolbar(page).innerText()).replace(/\s+/g,' ').toLowerCase();for(const word of['cell size','qr brush','color brush','eraser','mirror','grid on','save board','import','export'])expect(text.indexOf(word)).toBeGreaterThan(-1);expect(text.indexOf('cell size')).toBeLessThan(text.indexOf('qr brush'));expect(text.indexOf('qr brush')).toBeLessThan(text.indexOf('mirror'))})
