/* NOT-AUTOMATABLE: none; timing and style changes are sampled on real UI controls. */
import{assertClean,cards,clear,expect,gallery,importText,load,paint,remove,save,test,toolbar}from'./helpers.js'
test.beforeEach(async({page})=>load(page));test.afterEach(async({page})=>assertClean(page))
test('4.1 toolbar_gallery_hover_animations',async({page})=>{for(const b of[page.getByRole('button',{name:'Color Brush'}),page.getByRole('button',{name:/red palette/})]){const before=await b.evaluate(e=>getComputedStyle(e).transform);await b.hover();await page.waitForTimeout(170);const after=await b.evaluate(e=>getComputedStyle(e).transform);expect(after===before?await b.evaluate(e=>getComputedStyle(e).backgroundColor):after).toBeTruthy()}await gallery(page);const c=cards(page).first(),before=await c.evaluate(e=>getComputedStyle(e).transform);await c.hover();await page.waitForTimeout(180);expect(await c.evaluate(e=>getComputedStyle(e).transform)).not.toBe(before)})
test('4.2 paint_gallery_switch_keeps_hover',async({page})=>{const url=page.url();await gallery(page);const c=cards(page).first();await c.hover();await page.waitForTimeout(180);expect(await c.evaluate(e=>getComputedStyle(e).transform)).not.toBe('none');await page.getByRole('button',{name:'Paint',exact:true}).click();expect(page.url()).toBe(url);await page.getByRole('button',{name:'Color Brush'}).hover()})
test('4.4 cell_slider_lock_fade_and_toolbar_drag',async({page})=>{await paint(page,[0]);await expect(page.locator('.slider-wrap')).toHaveClass(/is-locked/);expect(Number(await page.locator('.slider-wrap').evaluate(e=>getComputedStyle(e).opacity))).toBeLessThan(1);await clear(page);await expect(page.locator('.slider-wrap')).not.toHaveClass(/is-locked/);const p=toolbar(page),h=p.locator('.tool-panel-header');await h.scrollIntoViewIfNeeded();const before=await p.boundingBox(),b=await h.boundingBox();await page.mouse.move(b.x+10,b.y+10);await page.mouse.down();await page.mouse.move(b.x+90,b.y+80,{steps:4});await page.mouse.up();const after=await p.boundingBox();expect(`${after.x},${after.y}`).not.toBe(`${before.x},${before.y}`)})
test('4.5 camera_overlay_fades',async({page})=>{await page.getByRole('button',{name:'Camera'}).click();const d=page.getByRole('dialog',{name:'Capture image'});expect(await d.evaluate(e=>getComputedStyle(e).animationName)).toContain('dialog-in');await d.getByRole('button',{name:'Dismiss'}).click();await expect(d).toHaveClass(/is-closing/);await expect(d).toHaveCount(0)})
test('4.6 gallery_card_enter_exit_animation',async({page})=>{await save(page,'Animated Card','Motion');const c=cards(page).filter({hasText:'Animated Card'});expect(await c.evaluate(e=>getComputedStyle(e).animationName)).toContain('card-enter');await c.getByRole('button',{name:'Delete Animated Card'}).click();await c.getByRole('button',{name:'Confirm delete Animated Card'}).click();await expect(c).toHaveClass(/is-deleting/);await expect(c).toHaveCount(0)})
test('4.7 validation_feedback_eased_in',async({page})=>{await page.getByRole('button',{name:'Save current board'}).click();const n=page.getByLabel('Name required · max 40');await n.focus();await n.blur();const a=page.getByRole('alert');expect(await a.evaluate(e=>getComputedStyle(e).animationName)).toContain('notice-in')})
test('4.8 reduced_motion_removes_animation',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.reload();const duration=await page.locator('.display-title').evaluate(e=>getComputedStyle(e).animationDuration);expect(parseFloat(duration)).toBeLessThan(.01);await paint(page,[0]);await save(page,'Reduced','Motion');await page.getByRole('button',{name:'Load Reduced'}).click();await gallery(page);await page.getByRole('button',{name:'Filter boards by tag'}).click();await page.getByRole('option',{name:'Motion'}).click();await expect(cards(page)).toHaveCount(1)})
test('4.9 export_surface_enter_and_copy_confirm',async({page})=>{await page.getByRole('button',{name:'Export',exact:true}).click();const d=page.getByRole('dialog',{name:'Export'});expect(await d.evaluate(e=>getComputedStyle(e).animationName)).toContain('dialog-in');await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{}}})});await d.getByRole('button',{name:'Copy JSON'}).click();await expect(d.getByRole('status')).toContainText(/copied/i);await expect(d.getByRole('status')).toHaveCount(0,{timeout:3000})})
