/* NOT-AUTOMATABLE: none; breakpoint geometry and touch input are directly measured. */
import{assertClean,cards,cells,expect,gallery,load,test,toolbar}from'./helpers.js'
test.beforeEach(async({page})=>load(page));test.afterEach(async({page})=>assertClean(page))
async function mobile(page){await page.setViewportSize({width:375,height:844});await page.reload();await expect(page.getByRole('grid')).toBeVisible()}
test('7.1 layout_adapts_1440_to_375',async({page})=>{await page.setViewportSize({width:1440,height:900});expect((await toolbar(page).evaluate(e=>getComputedStyle(e).position))).toBe('absolute');await mobile(page);expect(await toolbar(page).evaluate(e=>getComputedStyle(e).position)).toBe('relative')})
test('7.2 mobile_tap_targets_large_enough',async({page})=>{await mobile(page);const boxes=await toolbar(page).locator('button:visible').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return[Math.round(r.width),Math.round(r.height)]}));for(const[w,h]of boxes)expect(Math.max(w,h)).toBeGreaterThanOrEqual(44)})
test('7.3 typography_readable_across_breakpoints',async({page})=>{for(const width of[1440,375]){await page.setViewportSize({width,height:844});const sizes=await page.locator('.site-header h1,.tool-panel button').evaluateAll(es=>es.map(e=>parseFloat(getComputedStyle(e).fontSize)));expect(Math.min(...sizes)).toBeGreaterThanOrEqual(9)}})
test('7.4 no_clip_or_overflow_at_375',async({page})=>{await mobile(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const clipped=await toolbar(page).locator('button:visible').evaluateAll(es=>es.some(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth}));expect(clipped).toBe(false)})
test('7.5 toolbar_docks_or_reflows_on_narrow',async({page})=>{await mobile(page);for(const n of['QR Brush','Color Brush','Eraser','Horizontal mirror','Vertical mirror','Export','Import'])await expect(page.getByRole('button',{name:n,exact:n==='Export'||n==='Import'})).toBeVisible();await expect(page.getByLabel('Live fill statistics')).toBeVisible()})
test('7.6 gallery_cards_reflow_single_column',async({page})=>{await mobile(page);await gallery(page);const boxes=await cards(page).evaluateAll(es=>es.map(e=>e.getBoundingClientRect()));expect(boxes.every((b,i)=>i===0||b.top>boxes[i-1].top)).toBe(true);await expect(cards(page).first().getByRole('heading')).toBeVisible();expect(await cards(page).first().locator('button').count()).toBeGreaterThanOrEqual(4)})

test('7.7 touch_drag_paints_on_mobile',async({browser,page})=>{const baseURL=new URL(page.url()).origin,context=await browser.newContext({baseURL,viewport:{width:375,height:844},hasTouch:true});try{const p=await context.newPage();await p.goto('/');await p.getByRole('gridcell').first().scrollIntoViewIfNeeded();const a=await p.getByRole('gridcell').first().boundingBox(),b=await p.getByRole('gridcell').nth(4).boundingBox(),cdp=await context.newCDPSession(p),point=(box)=>({x:box.x+box.width/2,y:box.y+box.height/2}),from=point(a),to=point(b);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[from]});for(let step=1;step<=5;step++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:from.x+(to.x-from.x)*step/5,y:from.y+(to.y-from.y)*step/5}]});await p.waitForTimeout(16)}await expect.poll(()=>p.locator('.grid-cell:not(.kind-blank)').count()).toBeGreaterThan(1);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}finally{await context.close()}})
test('7.8 no_horizontal_scroll_at_375',async({page})=>{await mobile(page);expect(await page.evaluate(()=>document.body.scrollWidth<=375)).toBe(true);await gallery(page);expect(await page.evaluate(()=>document.body.scrollWidth<=375)).toBe(true)})
test('7.9 canvas_grid_sizes_responsively',async({page})=>{for(const width of[1440,375]){await page.setViewportSize({width,height:844});const b=await page.getByRole('grid').boundingBox();expect(b.width).toBeLessThanOrEqual(width);expect(b.x).toBeGreaterThanOrEqual(0)}})
test('7.10 docked_toolbar_actions_accessible',async({page})=>{await mobile(page);for(const b of await toolbar(page).locator('button:visible').all())await expect(b).toBeEnabled({timeout:1000}).catch(async()=>expect(b).toBeDisabled())})
test('7.11 export_import_usable_at_375',async({page})=>{await mobile(page);await page.getByRole('button',{name:'Export',exact:true}).click();let d=page.getByRole('dialog',{name:'Export'});for(const n of['Session JSON','PNG','Copy JSON','Download'])await expect(d.getByRole(n==='Session JSON'||n==='PNG'?'tab':'button',{name:n})).toBeVisible();await page.keyboard.press('Escape');await page.waitForTimeout(180);await page.getByRole('button',{name:'Import',exact:true}).click();d=page.getByRole('dialog',{name:'Import Session JSON'});await expect(d.getByRole('textbox')).toBeVisible();await expect(d.getByRole('button',{name:'Import session'})).toBeVisible()})
