import { chromium } from '/usr/lib/node_modules/playwright/index.mjs'
const browser = await chromium.connectOverCDP('http://127.0.0.1:9222')
const page = browser.contexts()[0].pages()[0]
page.on('console', m => console.log('console', m.type(), m.text()))
page.on('pageerror', e => console.log('pageerror', e.message))
await page.goto('http://127.0.0.1:3000/', { waitUntil: 'networkidle' })
await page.getByText('Map constraint ambiguity in routing prompts', { exact: true }).click()
await page.getByRole('button', { name: 'Add finding', exact: true }).first().click()
const dialog = page.getByRole('dialog', { name: 'Add finding' })
await page.waitForTimeout(500)
console.log('initial errors', await dialog.locator('.field-error').allTextContents())
await dialog.locator('.n-select').nth(0).click()
await page.getByText('Blocker — gate stopping', { exact: true }).click()
await dialog.locator('.n-select').nth(1).click()
await page.getByText('Correctness', { exact: true }).last().click()
await dialog.getByPlaceholder('Describe the quality issue and its impact…').fill('Expected result omits the required final routing constraint.')
await dialog.getByPlaceholder('Paste an observed example or trial note…').fill('Trial fixture nine ends before the constraint is evaluated.')
await page.waitForTimeout(500)
console.log('after errors', await dialog.locator('.field-error').allTextContents())
console.log('button', await dialog.locator('button[type=submit]').evaluate(x => ({ disabled: x.disabled, html: x.outerHTML })))
console.log('values', await dialog.locator('textarea').evaluateAll(els => els.map(x => x.value)))
await browser.close()
