import { chromium } from '/usr/lib/node_modules/playwright/index.mjs'
const browser = await chromium.connectOverCDP('http://127.0.0.1:9222')
const page = browser.contexts()[0].pages()[0]
page.on('console', m => console.log('console', m.type(), m.text()))
await page.goto('http://127.0.0.1:3000/', { waitUntil: 'networkidle' })
await page.keyboard.press('Control+K')
const input = page.getByRole('searchbox', { name: 'Search commands' })
await page.waitForTimeout(450)
console.log('focused', await input.evaluate(x => x === document.activeElement))
await input.fill('Submission queue')
console.log('focused after fill', await input.evaluate(x => ({ same: x === document.activeElement, active: document.activeElement?.outerHTML?.slice(0,300), visible: !!(x.offsetWidth || x.offsetHeight || x.getClientRects().length) })))
console.log('ancestors', await input.evaluate(x => { const out=[]; for(let p=x; p; p=p.parentElement) out.push(`${p.tagName}.${p.className}`); return out.slice(0,9) }))
console.log('modals', await page.locator('.n-modal-container').count())
await input.evaluate(x => x.addEventListener('keydown', e => console.log('native-key', e.key)))
await page.waitForTimeout(200)
console.log('results', await page.locator('.palette-results button').allTextContents())
console.log('highlight', await page.locator('.palette-results button.highlighted').innerText())
await input.press('Enter')
await page.waitForTimeout(400)
console.log('url text', await page.locator('h1').innerText())
console.log('palette', await page.locator('.command-palette').isVisible().catch(() => false))
await page.waitForTimeout(1200)
console.log('palette later', await page.locator('.command-palette').isVisible().catch(() => false))
console.log('pinia', await page.evaluate(() => document.querySelector('#app').__vue_app__.config.globalProperties.$pinia.state.value.qc.palette))
await browser.close()
