import { chromium } from '/usr/lib/node_modules/playwright/index.mjs'
const browser = await chromium.connectOverCDP('http://127.0.0.1:9222')
const page = browser.contexts()[0].pages()[0]
const errors = []
page.on('console', m => { if (['error','warning'].includes(m.type())) errors.push(`${m.type()}: ${m.text()}`) })
page.on('pageerror', e => errors.push(`pageerror: ${e.message}`))
await page.setViewportSize({ width: 1440, height: 1000 })
await page.goto('http://127.0.0.1:3000/', { waitUntil: 'networkidle' })
await page.getByText('Align extraction span boundaries', { exact: true }).click()
const earlyBefore = await page.locator('.profile-row').first().innerText()
await page.getByRole('button', { name: 'Early' }).click()
await page.waitForTimeout(600)
const earlyAfter = await page.locator('.profile-row').first().innerText()
await page.getByRole('button', { name: 'All' }).click()
await page.getByRole('button', { name: 'Request revision', exact: true }).click()
const revisionDialog = page.getByRole('dialog', { name: 'Request revision' })
await page.waitForTimeout(250)
const revisionError = await revisionDialog.locator('.field-error').innerText()
await revisionDialog.getByPlaceholder('Explain what the contributor needs to revise…').fill('Please align the extraction boundaries with the permitted punctuation examples.')
await revisionDialog.getByRole('button', { name: 'Request revision' }).click()
await page.locator('.stage-needs-revision').first().waitFor()
await page.locator('.avatar-link').click()
const timelineUpdated = await page.getByText('Please align the extraction boundaries with the permitted punctuation examples.', { exact: true }).isVisible()
await page.locator('.n-drawer-header__close').click()
await page.getByRole('button', { name: 'Mark revised' }).click()
await page.locator('.stage-in-review').first().waitFor()
await page.getByRole('button', { name: 'Run re-check' }).click()
await page.getByText('Re-check complete — gate state confirmed.', { exact: true }).waitFor({ timeout: 5000 })
const stepsComplete = await page.locator('.recheck-steps li.complete').count()
await page.getByRole('button', { name: 'Approve' }).click()
await page.locator('.stage-approved').first().waitFor()
await page.locator('.payout-released').first().waitFor()
await page.getByRole('button', { name: 'Export' }).click()
await page.getByRole('button', { name: 'Copy export' }).click()
await page.getByRole('button', { name: 'Copied!' }).waitFor()
await page.keyboard.press('Control+K')
await page.getByRole('searchbox', { name: 'Search commands' }).fill('Submission queue')
await page.keyboard.press('Enter')
await page.getByRole('heading', { name: 'Submission queue' }).waitFor()
console.log(JSON.stringify({ profileChanged: earlyBefore !== earlyAfter, revisionError, timelineUpdated, stepsComplete, errors }, null, 2))
await browser.close()
