import { test } from '@playwright/test'
import { criterionProbe } from './helpers'

test.describe('core_features rubric', () => {
  test('1.1 seeded_jobs_and_sidebar', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'seeded_jobs_and_sidebar'))
  test('1.2 composer_fields_complete', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'composer_fields_complete'))
  test('1.3 dataset_preview_and_count', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'dataset_preview_and_count'))
  test('1.4 composer_validation_gating', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'composer_validation_gating'))
  test('1.5 valid_submit_creates_job', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'valid_submit_creates_job'))
  test('1.6 execution_grid_columns', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'execution_grid_columns'))
  test('1.7 status_progression_visible', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'status_progression_visible'))
  test('1.8 concurrency_guard_enforced', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'concurrency_guard_enforced'))
  test('1.9 deterministic_failures_backoff', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'deterministic_failures_backoff'))
  test('1.10 exhausted_retry_failed_state', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'exhausted_retry_failed_state'))
  test('1.11 virtualized_grid_scale', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'virtualized_grid_scale'))
  test('1.12 progress_bar_live_fraction', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'progress_bar_live_fraction'))
  test('1.13 pause_resume_checkpoint', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'pause_resume_checkpoint'))
  test('1.14 retry_failed_only', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'retry_failed_only'))
  test('1.15 optimistic_macros_reconcile', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'optimistic_macros_reconcile'))
  test('1.16 queue_reorder_drag_and_keyboard', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'queue_reorder_drag_and_keyboard'))
  test('1.17 rollups_derive_live', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'rollups_derive_live'))
  test('1.18 inspector_full_content', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'inspector_full_content'))
  test('1.19 inspector_expected_diff', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'inspector_expected_diff'))
  test('1.20 run_history_and_timeline', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'run_history_and_timeline'))
  test('1.21 run_comparison_flips', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'run_comparison_flips'))
  test('1.22 schedule_form_and_badge', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'schedule_form_and_badge'))
  test('1.23 simulate_window_start', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'simulate_window_start'))
  test('1.24 ics_calendar_text', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'ics_calendar_text'))
  test('1.25 export_run_report_surface', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'export_run_report_surface'))
  test('1.26 undo_redo_scope', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'undo_redo_scope'))
  test('1.27 delete_confirm_and_empty_state', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'delete_confirm_and_empty_state'))
  test('1.28 double_activation_guards', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'double_activation_guards'))
  test('1.29 input_truncation', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'input_truncation'))
  test('1.30 api_shaped_create_payload_validation', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'api_shaped_create_payload_validation'))
  test('1.31 run_report_json_schema_keys', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'run_report_json_schema_keys'))
  test('1.32 import_run_report_round_trip', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'import_run_report_round_trip'))
  test('1.33 import_rejects_invalid_schema', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'import_rejects_invalid_schema'))
})

