/* NOT-AUTOMATABLE: none; keyboard, focus, names, roles, and live regions are DOM-observable. */
import {archiveFirst,createUser,fillUser,load,nav,openExport,openUsers,rows,sidebar,test,expect} from './helpers'
test.beforeEach(async({page})=>{await load(page);await openUsers(page)})
test('8.1 keyboard_reaches_directory_controls',async({page})=>{const search=page.getByLabel('Search users');await search.focus();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).toMatch(/BUTTON|INPUT/);await nav(page,'Add user');await page.getByLabel('First name').focus();await page.keyboard.type('Key');await expect(page.getByLabel('First name')).toHaveValue('Key')})
test('8.2 visible_focus_indicators',async({page})=>{await page.locator('body').click();await page.keyboard.press('Tab');const s=await page.evaluate(()=>getComputedStyle(document.activeElement!));expect(s.outlineStyle).not.toBe('none');expect(Number.parseFloat(s.outlineWidth)).toBeGreaterThan(0)})
test('8.3 overlays_escape_and_focus_return',async({page})=>{for(const name of ['Open notifications','Open profile menu']){const b=page.getByRole('button',{name});await b.click();await page.keyboard.press('Escape');await expect(b).toBeFocused()}const command=page.getByRole('button',{name:'Open Command palette'});await command.click();const palette=page.getByRole('dialog',{name:'Command palette'});await expect(palette.getByLabel('Search Command palette')).toBeFocused();await page.keyboard.press('Escape');await expect(palette).toHaveCount(0);await expect(command).toBeFocused();const exp=page.getByRole('button',{name:'Export directory',exact:true}).last();await exp.click();const drawer=page.getByRole('dialog',{name:'Export directory'});await expect(drawer.getByRole('button',{name:'Close export drawer'})).toBeFocused();await page.keyboard.press('Escape');await expect(drawer).toHaveCount(0);await expect(exp).toBeFocused()})
test('8.4 palette_and_drawer_trap_focus',async({page})=>{await page.getByRole('button',{name:'Open Command palette'}).click();const d=page.getByRole('dialog',{name:'Command palette'});await expect(d.getByLabel('Search Command palette')).toBeFocused();await d.getByRole('button').last().focus();await page.keyboard.press('Tab');await expect(d.getByLabel('Search Command palette')).toBeFocused();await page.keyboard.press('Escape');await expect(d).toHaveCount(0);const e=await openExport(page);await expect(e.getByRole('button',{name:'Close export drawer'})).toBeFocused();await e.getByRole('button',{name:'Download'}).focus();await page.keyboard.press('Tab');await expect(e.getByRole('button',{name:'Close export drawer'})).toBeFocused()})
test('8.5 validation_announced_aria_live',async({page})=>{await nav(page,'Add user');await page.getByLabel('First name').fill('A'.repeat(41));await expect(page.locator('.form-card [aria-live="polite"]')).toContainText('firstName length')})
test('8.6 mutation_announcements_aria_live',async({page})=>{await createUser(page,'Announce','User','announce@example.dev');await expect(page.getByRole('status')).toContainText('was created');await page.getByRole('button',{name:'Delete Announce'}).click();await expect(page.getByRole('status')).toContainText('archived');await nav(page,'Archive');await page.getByRole('button',{name:'Restore'}).click();await expect(page.getByRole('status')).toContainText('restored')})
test('8.7 checkboxes_and_icon_buttons_labeled',async({page})=>{for(const input of await page.locator('input[type=checkbox]').all())expect(await input.getAttribute('aria-label')||await input.evaluate(n=>n.closest('label')?.textContent)).toBeTruthy();for(const b of await page.locator('button.icon-btn').all())expect(await b.getAttribute('aria-label')).toBeTruthy()})
test('8.8 status_and_role_not_color_only',async({page})=>{for(const badge of await rows(page).locator('.badge').all())expect((await badge.innerText()).trim()).toMatch(/Admin|Manager|Member|Viewer|Active|Invited|Suspended/)})
test('8.9 form_fields_have_visible_labels',async({page})=>{await nav(page,'Add user');for(const n of ['First name','Last name','Email','Phone','Notes','Temporary password','Account segment','Status','Role']){const control=page.getByLabel(new RegExp(n));await expect(control).toBeVisible();expect(await control.getAttribute('id')).toBeTruthy()}})
