/* NOT-AUTOMATABLE: none; every behavioral criterion has a state-delta or round-trip oracle. */
import {archiveByFirst,archiveFirst,closeExport,createUser,exportJson,importJson,load,names,nav,openExport,openUsers,payments,rows,test,total,expect} from './helpers'
test.beforeEach(async({page})=>{await load(page);await openUsers(page)})
test('14.1 multi_facet_reload_resets_seed',async({page})=>{await page.getByRole('button',{name:'Switch to dark theme'}).click();await createUser(page,'Reset','Probe','reset@example.dev');await archiveFirst(page);await openExport(page);await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await expect(page.getByRole('heading',{name:'Operations overview'})).toBeVisible();await expect(page.getByRole('dialog',{name:'Export directory'})).toHaveCount(0);await openUsers(page);await expect(page.getByText('Reset Probe',{exact:true})).toHaveCount(0);await nav(page,'Archive');await expect(page.getByText('Archive is empty')).toBeVisible()})
test('14.2 sort_name_az_vs_highest_spend_reversal',async({page})=>{await page.getByLabel('Sort users').selectOption('name-az');const az=await names(page);await page.getByLabel('Sort users').selectOption('highest-spend');expect(await names(page)).not.toEqual(az);expect(await payments(page)).toEqual([15420,12840,11300,9780,8180,6420]);await page.getByLabel('Sort users').selectOption('name-az');expect(await names(page)).toEqual(az)})
test('14.3 export_preview_tracks_mutations',async({page})=>{await createUser(page,'Derived','View','derived@example.dev');const a=await archiveByFirst(page,'Mina'),j=await exportJson(page);expect(j.users.some((u:any)=>u.email==='derived@example.dev')).toBeTruthy();expect(j.archive.some((u:any)=>u.email===a.email)).toBeTruthy();await closeExport(page);const d=await openExport(page);await d.getByRole('tab',{name:'Users CSV'}).click();await expect(d.locator('.preview')).toContainText('derived@example.dev');await expect(d.locator('.preview')).not.toContainText(a.email)})
test('14.4 cross_view_echo_users_logs_archive_export',async({page})=>{const before=Number(await total(page).innerText()),a=await archiveFirst(page);expect(Number(await total(page).innerText())).toBe(before-1);await nav(page,'Archive');await expect(page.getByText(a.name,{exact:true})).toBeVisible();await nav(page,'User logs');await expect(page.locator('.log-row').first()).toContainText(a.email);const j=await exportJson(page);expect(j.archive.some((u:any)=>u.email===a.email)).toBeTruthy()})
test('14.5 create_count_delta_exact',async({page})=>{const before=Number(await total(page).innerText());await createUser(page,'Delta','One','delta@example.dev');expect(Number(await total(page).innerText())).toBe(before+1)})
test('14.6 different_emails_different_export_rows',async({page})=>{for(const [n,e] of [['First','first@diff.dev'],['Second','second@diff.dev']])await createUser(page,n,'Distinct',e);const j=await exportJson(page);for(const e of ['first@diff.dev','second@diff.dev'])expect(j.users.some((u:any)=>u.email===e)).toBeTruthy()})
test('14.7 interleaved_duplicate_and_archive',async({page})=>{await page.getByRole('button',{name:'Duplicate Mina'}).click();await nav(page,'Archive');await nav(page,'All users');await page.getByRole('button',{name:'Duplicate Mina'}).click();await page.getByLabel('Email').fill('interleave@example.dev');await page.getByLabel('Temporary password').fill('ValidPass42!');await page.getByRole('button',{name:'Create user'}).click();await expect(page.getByText('Mina Park',{exact:true})).toHaveCount(2)})
test('14.8 archive_all_then_restore_repopulates',async({page})=>{const ids=await page.evaluate(async()=>{const tools=await window.webmcp_list_tools();return tools.length});expect(ids).toBeGreaterThan(0);while(Number(await total(page).innerText())>0){await page.getByRole('checkbox',{name:'Select all users on this page'}).check();await page.getByRole('button',{name:'Delete',exact:true}).click()}await expect(page.getByText('The active directory is empty')).toBeVisible();await nav(page,'Archive');await page.locator('.archive-row').first().getByRole('button',{name:'Restore'}).click();await openUsers(page);await expect(total(page)).toHaveText('1');expect((await exportJson(page)).users).toHaveLength(1)})
test('14.9 export_import_round_trip_preserves_mutations',async({page})=>{await createUser(page,'Round','Behavior','round.behavior@example.dev');const a=await archiveByFirst(page,'Mina'),j=await exportJson(page);await closeExport(page);await page.getByRole('button',{name:'Delete Round'}).click();await importJson(page,j);await openUsers(page);await expect(page.getByText('Round Behavior',{exact:true})).toBeVisible();await nav(page,'Archive');await expect(page.getByText(a.name,{exact:true})).toBeVisible()})
test('14.10 request_body_fields_survive_export_import',async({page})=>{await nav(page,'Add user');await page.getByLabel('First name').fill('Payload');await page.getByLabel('Last name').fill('Keeper');await page.getByLabel('Email').fill('payload@example.dev');await page.getByLabel('Temporary password').fill('ValidPass42!');await page.getByLabel('Send invitation after creating this user').check();await page.getByLabel('billing.view').check();await page.getByRole('button',{name:'Create user'}).click();const j=await exportJson(page);await closeExport(page);await importJson(page,j);const u=(await exportJson(page)).users.find((x:any)=>x.email==='payload@example.dev');expect(u).toMatchObject({firstName:'Payload',sendInvitation:true});expect(u.permissions).toContain('billing.view')})
