/* NOT-AUTOMATABLE: none; the closed-checkbox permission boundary is probed through the declared WebMCP form path. */
import {archiveFirst,createUser,fillUser,load,nav,openExport,openUsers,rows,selectFirst,test,total,expect} from './helpers'
test.beforeEach(async({page})=>{await load(page);await openUsers(page)})
test('4.1 empty_active_list_state_present',async({page})=>{await page.getByLabel('Search users').fill('nobody-matches');await expect(page.getByText('No users match these filters')).toBeVisible()})
test('4.2 add_edit_forms_validate_inline',async({page})=>{await nav(page,'Add user');await page.getByLabel('First name').fill('A'.repeat(41));await expect(page.locator('#firstName-error')).not.toBeEmpty();await nav(page,'All users');await page.getByRole('button',{name:'Edit Mina'}).click();await page.getByLabel('Email').fill('bad');await expect(page.locator('#email-error')).not.toBeEmpty()})
test('4.3 validation_and_import_errors_actionable',async({page})=>{await nav(page,'Add user');await page.getByLabel('Email').fill('bad');await expect(page.locator('#email-error')).toContainText('email must include a domain dot');await nav(page,'All users');await page.getByRole('button',{name:'Import directory'}).click();const d=page.getByRole('dialog',{name:'Import directory'});await d.getByLabel('Directory JSON text').fill('{');await d.getByRole('button',{name:'Import directory',exact:true}).click();await expect(d.locator('.field-error').last()).toContainText('payload')})
test('4.4 create_archive_restore_export_feedback',async({page,context})=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await createUser(page,'Feedback','User','feedback@example.dev');await expect(page.getByRole('status')).toContainText('created');await page.getByRole('button',{name:'Delete Feedback'}).click();await expect(page.getByRole('status')).toContainText('archived');await nav(page,'Archive');await page.getByRole('button',{name:'Restore'}).click();await expect(page.getByRole('status')).toContainText('restored');const d=await openExport(page);await d.getByRole('button',{name:'Copy'}).click();await expect(page.getByRole('status')).toContainText('copied')})
test('4.5 cancel_leaves_collection_unchanged',async({page})=>{const before=Number(await total(page).innerText());await nav(page,'Add user');await fillUser(page);await page.getByRole('button',{name:'Cancel'}).click();expect(Number(await total(page).innerText())).toBe(before)})
test('4.6 archive_provides_restore_path',async({page})=>{const a=await archiveFirst(page);await nav(page,'Archive');await expect(page.locator('.archive-row').filter({hasText:a.email}).getByRole('button',{name:'Restore'})).toBeVisible()})
test('4.7 double_submit_creates_one_user',async({page})=>{const before=Number(await total(page).innerText());await nav(page,'Add user');await fillUser(page,'Double','Edge','double.edge@example.dev');await page.getByRole('button',{name:'Create user'}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()});expect(Number(await total(page).innerText())).toBe(before+1)})
test('4.8 bulk_noop_without_selection',async({page})=>{for(const x of ['Change status','Change role','Delete'])await expect(page.getByRole('button',{name:x,exact:true})).toBeDisabled();await page.getByRole('button',{name:'Export',exact:true}).click();await expect(page.getByRole('dialog',{name:'Export directory'})).toBeVisible()})
test('4.9 malformed_import_rejected',async({page})=>{const before=Number(await total(page).innerText());await page.getByRole('button',{name:'Import directory'}).click();const d=page.getByRole('dialog',{name:'Import directory'});await d.getByLabel('Directory JSON text').fill('{bad');await d.getByRole('button',{name:'Import directory',exact:true}).click();await expect(d.locator('.field-error').last()).toContainText('payload');await page.keyboard.press('Escape');expect(Number(await total(page).innerText())).toBe(before)})
test('4.10 field_bounds_block_create',async({page})=>{const before=Number(await total(page).innerText());await nav(page,'Add user');await fillUser(page,'A'.repeat(41),'Bounds','bounds@example.dev');await page.getByLabel('Phone').fill('123');await page.getByLabel('Notes').fill('n'.repeat(281));await page.getByLabel('Temporary password').fill('short');for(const x of ['firstName','phone','notes','temporaryPassword'])await expect(page.locator(`#${x}-error`)).not.toBeEmpty();await expect(page.getByRole('button',{name:'Create user'})).toBeDisabled();await nav(page,'All users');expect(Number(await total(page).innerText())).toBe(before)})
test('4.11 unknown_permission_id_rejected',async({page})=>{const before=Number(await total(page).innerText()),tools=await page.evaluate(()=>window.webmcp_list_tools());const submit=tools.find((t:any)=>t.name.includes('form_submit'));expect(submit,'form_submit WebMCP tool').toBeTruthy();const result=await page.evaluate(async(name)=>{try{return await window.webmcp_invoke_tool(name,{fields:{'first-name':'Unknown','last-name':'Permission',email:'unknown.permission@example.dev','temporary-password':'ValidPass42!','account-segment':'External',role:'Member',status:'Active',permissions:['unknown.permission']}})}catch(e){return String(e)}},submit.name);expect(JSON.stringify(result)).toMatch(/permission/i);expect(Number(await total(page).innerText())).toBe(before)})
