/* NOT-AUTOMATABLE: none; animations are sampled after real pointer and control interactions. */
import {archiveFirst,createUser,load,nav,openExport,openUsers,rows,sidebar,test,expect} from './helpers'

test.beforeEach(async({page})=>load(page))

test('4.1 hover_and_theme_toggle_animation',async({page})=>{const b=page.getByRole('button',{name:'New product'}),before=await b.evaluate(n=>getComputedStyle(n).backgroundColor);await b.hover();await expect.poll(()=>b.evaluate(n=>getComputedStyle(n).backgroundColor)).not.toBe(before);const icon=page.locator('.theme-icon');expect(Number.parseFloat(await icon.evaluate(n=>getComputedStyle(n).transitionDuration))).toBeCloseTo(.2,1);await page.getByRole('button',{name:'Switch to dark theme'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark')})

test('4.2 view_switch_keeps_hover_feedback',async({page})=>{await openUsers(page);await nav(page,'Dashboard');const b=page.getByRole('button',{name:'New product'});expect(await b.evaluate(n=>getComputedStyle(n).transitionDuration)).not.toBe('0s');await b.hover();await expect(b).toBeVisible()})

test('4.4 sidebar_accordion_exclusive_chevron',async({page})=>{const users=sidebar(page).getByRole('button',{name:'Users',exact:true}),products=sidebar(page).getByRole('button',{name:'Products',exact:true});await expect(users).toHaveAttribute('aria-expanded','true');await products.click();await expect(products).toHaveAttribute('aria-expanded','true');await expect(users).toHaveAttribute('aria-expanded','false');expect(await products.locator('.chev').evaluate(n=>getComputedStyle(n).transform)).not.toBe('none')})

test('4.5 popover_enter_exit_animation',async({page})=>{for(const name of ['Open notifications','Open profile menu']){const b=page.getByRole('button',{name});await b.click();const p=page.locator('.popover').last();await expect(p).toBeVisible();const durationMs=await p.evaluate(n=>Number.parseFloat(getComputedStyle(n).animationDuration)*1000);expect(durationMs).toBeGreaterThanOrEqual(150);await p.locator('.menu-row').first().hover();await page.keyboard.press('Escape');await expect(p).toHaveCount(0)}await page.getByRole('button',{name:/Ari Lane/}).click();await expect(page.locator('.popover.up')).toBeVisible()})

test('4.6 list_add_remove_reorder_animation',async({page})=>{await openUsers(page);await createUser(page,'Animated','Row','animated@example.dev');let a=await rows(page).first().evaluate(n=>n.getAnimations().map(x=>Number(x.effect?.getTiming().duration)));expect(Math.max(...a)).toBeGreaterThan(0);await page.getByRole('button',{name:'Delete Animated'}).click();await page.getByLabel('Sort users').selectOption('name-az');a=await rows(page).first().evaluate(n=>n.getAnimations().map(x=>Number(x.effect?.getTiming().duration)));expect(Math.max(...a)).toBeGreaterThan(0)})

test('4.7 drawer_slide_overlay_small_viewport',async({page})=>{await page.setViewportSize({width:375,height:844});await page.getByRole('button',{name:'Open navigation'}).click();const s=page.locator('.sidebar');expect(Number.parseFloat(await s.evaluate(n=>getComputedStyle(n).transitionDuration))).toBeGreaterThan(0);await expect(page.getByRole('button',{name:'Close navigation'})).toBeVisible();await page.getByRole('button',{name:'Close navigation'}).click();await expect(s).not.toBeInViewport();await page.setViewportSize({width:1440,height:900});await expect(s).toBeInViewport()})

test('4.8 chart_hover_and_trend_redraw',async({page})=>{const canvas=page.locator('canvas').first(),box=await canvas.boundingBox(),before=await canvas.evaluate((c:HTMLCanvasElement)=>c.toDataURL());await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2);await expect.poll(()=>canvas.evaluate((c:HTMLCanvasElement)=>c.toDataURL())).not.toBe(before);await expect(page.locator('.status-ping')).toHaveCSS('animation-name','ping');await openUsers(page);const label=await page.locator('.spark').first().getAttribute('aria-label');await createUser(page,'Chart','Delta','chart@example.dev');await expect(page.locator('.spark').first()).not.toHaveAttribute('aria-label', label);await expect(page.locator('.dot-error')).toBeAttached()})

test('4.9 breadcrumb_underline_and_focus_rings',async({page})=>{const crumb=page.locator('.breadcrumb button');await crumb.hover();await expect.poll(()=>crumb.evaluate(n=>getComputedStyle(n).textDecorationLine)).toContain('underline');await openUsers(page);await nav(page,'Add user');const input=page.getByLabel('First name');await input.focus();expect(await input.evaluate(n=>getComputedStyle(n).outlineStyle)).not.toBe('none')})

test('4.20 export_drawer_and_palette_motion',async({page})=>{await openUsers(page);const d=await openExport(page);expect((await d.evaluate(n=>n.getAnimations().map(a=>Number(a.effect?.getTiming().duration)))).some(n=>n>=200)).toBeTruthy();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Open Command palette'}).click();const c=page.getByRole('dialog',{name:'Command palette'});expect((await c.evaluate(n=>n.getAnimations().map(a=>Number(a.effect?.getTiming().duration)))).some(n=>n>=180)).toBeTruthy()})

test('reduced motion suppresses transitions',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.reload();const durations=await page.locator('button,.card,.sidebar').evaluateAll(ns=>ns.flatMap(n=>getComputedStyle(n).transitionDuration.split(',')).map(Number.parseFloat));expect(Math.max(...durations)).toBeLessThanOrEqual(.001)})
