/* NOT-AUTOMATABLE: none; fixed desktop and 375px viewports cover every responsive criterion. */
import {archiveFirst,load,nav,openExport,openUsers,test,expect} from './helpers'
test.use({viewport:{width:375,height:844},hasTouch:true})
test('7.1 desktop_drawer_open_by_default',async({page})=>{await page.setViewportSize({width:1440,height:900});await load(page);await expect(page.locator('.sidebar')).toBeInViewport();await expect(page.locator('.sidebar')).toContainText('Pineapple Tech')})
test('7.2 mobile_hamburger_overlay_drawer',async({page})=>{await load(page);await expect(page.locator('.sidebar')).not.toBeInViewport();await page.getByRole('button',{name:'Open navigation'}).tap();await expect(page.locator('.sidebar')).toBeInViewport();await expect(page.getByRole('button',{name:'Close navigation'})).toBeVisible()})
test('7.3 no_clip_or_page_scroll_at_375',async({page})=>{await load(page);await openUsers(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(375);const t=page.locator('.table-scroll');expect(await t.evaluate(n=>n.scrollWidth>=n.clientWidth)).toBeTruthy()})
test('7.4 export_drawer_usable_at_375',async({page})=>{await load(page);await openUsers(page);const d=await openExport(page);await page.waitForTimeout(250);const b=await d.boundingBox();expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(375);await expect(d.getByRole('button',{name:'Copy'})).toBeVisible()})
test('7.5 command_palette_usable_at_375',async({page})=>{await load(page);await page.getByRole('button',{name:'Open Command palette'}).tap();const d=page.getByRole('dialog',{name:'Command palette'}),b=await d.boundingBox();expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(375);await expect(d.getByLabel('Search Command palette')).toBeVisible()})
test('7.6 archive_view_usable_at_375',async({page})=>{await load(page);await openUsers(page);const a=await archiveFirst(page);await nav(page,'Archive');await expect(page.getByText(a.name,{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Restore'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)})
test('7.7 add_user_form_usable_at_375',async({page})=>{await load(page);await openUsers(page);await nav(page,'Add user');for(const n of ['First name','Last name','Email','Temporary password'])await expect(page.getByLabel(n)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)})
test('7.8 kpi_strip_wraps_or_scrolls_cleanly',async({page})=>{await load(page);await openUsers(page);const cards=page.locator('.users-kpis .kpi-card');await expect(cards).toHaveCount(4);for(const c of await cards.all()){const b=await c.boundingBox();expect(b!.x).toBeGreaterThanOrEqual(0);expect(b!.x+b!.width).toBeLessThanOrEqual(375)}})
