/* NOT-AUTOMATABLE: none; visual criteria are reduced to explicit layout, style, and content contracts. */
import {load,nav,openExport,openUsers,rows,test,expect} from './helpers'
test('3.1 mosaic_overview_dense_users_views',async({page})=>{await load(page);await expect(page.locator('.mosaic')).toHaveCSS('grid-template-columns',/repeat\(12|px/);const spans=await page.locator('.overview-card').evaluateAll(ns=>ns.map(n=>[...n.classList].find(c=>c.startsWith('span-'))));expect(new Set(spans).size).toBeGreaterThan(1);await expect(page.locator('.overview-card.inverse')).toContainText('Revenue run rate');await openUsers(page);await expect(page.locator('.data-table')).toBeVisible()})
test('3.2 badges_distinct_empty_state_visible',async({page})=>{await load(page);await openUsers(page);const a=rows(page).locator('.badge.Active').first(),s=rows(page).locator('.badge.Suspended').first();expect(await a.evaluate(n=>getComputedStyle(n).backgroundColor)).not.toBe(await s.evaluate(n=>getComputedStyle(n).backgroundColor));await page.getByLabel('Search users').fill('none-match');await expect(page.getByText('No users match these filters')).toBeVisible()})
test('3.4 chart_accent_palette_radial_wash',async({page})=>{await load(page);await expect(page.locator('.main')).toHaveCSS('background-image',/radial-gradient/);expect(await page.locator('canvas').count()).toBeGreaterThanOrEqual(4);await expect(page.locator('.bars i').first()).toBeVisible()})
test('3.5 card_surfaces_and_density_elements',async({page})=>{await load(page);const c=page.locator('.card').first();expect(await c.evaluate(n=>getComputedStyle(n).boxShadow)).not.toBe('none');expect(await c.evaluate(n=>getComputedStyle(n).borderTopWidth)).not.toBe('0px');await expect(page.locator('.ring').first()).toBeVisible();await expect(page.locator('.progress-line').first()).toBeVisible()})
test('3.6 icon_family_avatars_header_chrome',async({page})=>{await load(page);await expect(page.locator('.sidebar svg').first()).toBeVisible();for(const img of await page.locator('img').all())await expect(img).toHaveJSProperty('complete',true);await expect(page.locator('.header-search')).toHaveCSS('border-radius',/px/);await expect(page.locator('.icon-btn').first()).toHaveCSS('border-radius','999px')})
test('3.7 responsive_drawer_breakpoints',async({page})=>{await page.setViewportSize({width:1440,height:900});await load(page);await expect(page.locator('.sidebar')).toBeInViewport();await page.setViewportSize({width:375,height:844});await expect(page.getByRole('button',{name:'Open navigation'})).toBeVisible();await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.locator('.sidebar')).toBeInViewport()})
test('3.9 copy_capitalization_and_verb_labels',async({page})=>{await load(page);await openUsers(page);for(const x of ['Add user','Export directory'])await expect(page.getByRole('button',{name:x,exact:true}).last()).toBeVisible();await expect(page.getByRole('button',{name:/Duplicate/}).first()).toBeVisible();await expect(page.getByRole('button',{name:/^(Submit|OK)$/})).toHaveCount(0)})
test('3.10 validation_and_empty_state_copy',async({page})=>{await load(page);await openUsers(page);await nav(page,'Add user');await page.getByLabel('Email').fill('bad');await expect(page.locator('#email-error')).toContainText('domain dot');await nav(page,'Archive');await expect(page.getByText('Archive is empty')).toBeVisible();await expect(page.locator('.empty')).toContainText('Users archived from All users will appear here')})
test('3.12 export_drawer_and_command_palette_chrome',async({page})=>{await load(page);await openUsers(page);const d=await openExport(page);await expect(d.locator('.preview')).toHaveCSS('font-family',/mono/i);for(const x of ['Directory JSON','Users CSV'])await expect(d.getByRole('tab',{name:x})).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Open Command palette'}).click();const c=page.getByRole('dialog',{name:'Command palette'});await expect(c.getByLabel('Search Command palette')).toBeVisible();expect(await c.locator('.command-list').evaluate(n=>n.scrollHeight)).toBeGreaterThan(0)})
