/* NOT-AUTOMATABLE: 15.5 broad grammatical quality requires editorial review. */
import {archiveFirst,createUser,load,nav,openExport,openUsers,test,expect} from './helpers'
test.beforeEach(async({page})=>{await load(page);await openUsers(page)})
test('15.1 headings_use_consistent_capitalization',async({page})=>{for(const h of (await page.locator('h1,h2,h3').allTextContents()).map(x=>x.trim()).filter(Boolean))expect(h[0]).toBe(h[0].toUpperCase());await nav(page,'Archive');await expect(page.getByRole('heading',{name:'Archive',exact:true})).toBeVisible()})
test('15.2 actions_use_specific_directory_verbs',async({page})=>{for(const x of ['Add user','Export directory'])await expect(page.getByRole('button',{name:x,exact:true}).last()).toBeVisible();await expect(page.getByRole('button',{name:/Duplicate/}).first()).toBeVisible();await expect(page.getByRole('button',{name:/^(Submit|OK)$/})).toHaveCount(0)})
test('15.3 validation_names_field_and_fix',async({page})=>{await nav(page,'Add user');await page.getByLabel('First name').fill('A'.repeat(41));await page.getByLabel('Email').fill('bad');await expect(page.locator('#firstName-error')).toContainText('firstName length must be 1 to 40');await expect(page.locator('#email-error')).toContainText('email must include a domain dot')})
test('15.4 empty_states_explain_next_step',async({page})=>{await page.getByLabel('Search users').fill('none-match');await expect(page.locator('.empty')).toContainText('Clear the filters or search');await nav(page,'Archive');await expect(page.locator('.empty')).toContainText('Users archived from All users will appear here')})
test('15.6 export_tab_labels_exact',async({page})=>{const d=await openExport(page);await expect(d.getByRole('tab',{name:'Directory JSON',exact:true})).toBeVisible();await expect(d.getByRole('tab',{name:'Users CSV',exact:true})).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Open Command palette'}).click();await expect(page.getByRole('dialog',{name:'Command palette'})).toBeVisible()})
test('15.7 import_errors_name_field',async({page})=>{await page.getByRole('button',{name:'Import directory'}).click();const d=page.getByRole('dialog',{name:'Import directory'});await d.getByLabel('Directory JSON text').fill('{');await d.getByRole('button',{name:'Import directory',exact:true}).click();await expect(d.locator('.field-error').last()).toContainText('payload')})
test('15.8 success_messages_are_specific',async({page,context})=>{await context.grantPermissions(['clipboard-read','clipboard-write']);await createUser(page,'Specific','Message','specific@example.dev');await expect(page.getByRole('status')).toContainText('Specific Message was created');await page.getByRole('button',{name:'Delete Specific'}).click();await expect(page.getByRole('status')).toContainText('user was archived');await nav(page,'Archive');await page.getByRole('button',{name:'Restore'}).click();await expect(page.getByRole('status')).toContainText('was restored')})
