/* NOT-AUTOMATABLE: none; WebMCP delivery checks are included alongside rubric criteria. */
import { activeForm, chooseTechnique, dialogByHeading, generateZeroShot, loadApp, openLibrary, saveCurrentPrompt, test, expect } from './helpers'

test.beforeEach(async ({ page }) => loadApp(page))

test('2.1 shared_state_coherence', async ({ page }) => {
  const zero = page.getByRole('button', { name: /Zero-Shot/ }).first()
  await activeForm(page).getByLabel('Task description').fill('One shared state record')
  await expect(zero).toContainText('In progress')
  await activeForm(page).getByRole('button', { name: 'Generate prompt' }).click()
  await expect(page.locator('#prompt-preview pre')).toContainText('One shared state record')
  await expect(zero).toContainText('Generated')
  await saveCurrentPrompt(page, 'Shared state entry')
  await expect(zero).toContainText('Saved')
  await openLibrary(page)
  await expect(page.getByRole('button', { name: 'Open Shared state entry' }).first()).toBeVisible()
})

test('2.2 no_storage_reload_seeded', async ({ page }) => {
  await generateZeroShot(page, 'Ephemeral session data')
  await saveCurrentPrompt(page, 'Ephemeral entry')
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  expect(await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length }))).toEqual({ local: 0, session: 0 })
  await page.reload()
  await expect(page.getByRole('button', { name: /Zero-Shot/ }).first()).toContainText('Neutral')
  await expect(activeForm(page).getByLabel('Task description')).toHaveValue('')
  await openLibrary(page)
  await expect(page.locator('.library-row')).toHaveCount(5)
  await expect(page.getByRole('button', { name: 'Open Ephemeral entry' })).toHaveCount(0)
})

test('2.5 console_clean_during_session', async ({ page }) => {
  await generateZeroShot(page, 'Zero')
  await chooseTechnique(page, 'One-Shot')
  await activeForm(page).getByLabel('Task description').fill('One')
  await activeForm(page).getByLabel('Example input').fill('Input')
  await activeForm(page).getByLabel('Expected output').fill('Output')
  await activeForm(page).getByRole('button', { name: 'Generate prompt' }).click()
  await chooseTechnique(page, 'Few-Shot')
  await activeForm(page).getByLabel('Task description').fill('Few')
  await activeForm(page).getByLabel('Example input').fill('Input')
  await activeForm(page).getByLabel('Expected output').fill('Output')
  await activeForm(page).getByRole('button', { name: 'Add example' }).click()
  await activeForm(page).getByRole('button', { name: 'Remove example 2' }).click()
  await activeForm(page).getByRole('button', { name: 'Add document' }).click()
  await page.getByRole('option', { name: /brand-voice-guide\.pdf/ }).click()
  await activeForm(page).getByRole('button', { name: 'Generate prompt' }).click()
  await chooseTechnique(page, 'Chain-of-Thought')
  await activeForm(page).getByLabel('Goal').fill('Reason')
  await activeForm(page).getByRole('button', { name: 'Generate prompt' }).click()
  await chooseTechnique(page, 'Outcome-Based')
  await activeForm(page).getByLabel('Goal').fill('Outcome')
  const criteria = activeForm(page).locator('input[name^="successCriteria"]')
  for (let index = 0; index < await criteria.count(); index += 1) await criteria.nth(index).fill(`Success ${index + 1}`)
  await activeForm(page).getByRole('button', { name: 'Generate prompt' }).click()
  await chooseTechnique(page, 'Role-Based')
  await activeForm(page).getByLabel('Role or persona').fill('Reviewer')
  await activeForm(page).getByLabel('Task description').fill('Review')
  await activeForm(page).getByRole('button', { name: 'Generate prompt' }).click()
  await chooseTechnique(page, 'Constraint-Based')
  await activeForm(page).getByLabel('Task description').fill('Constrain')
  await activeForm(page).getByLabel('Constraint text').fill('Under ten words')
  await activeForm(page).getByRole('button', { name: 'Generate prompt' }).click()
  await saveCurrentPrompt(page, 'Full session proof')
  await openLibrary(page)
  await page.getByRole('button', { name: 'Open Full session proof' }).first().click()
})

test('2.6 cold_load_interactive_2s', async ({ page }) => {
  const started = Date.now()
  await page.reload()
  await page.getByRole('button', { name: /Role-Based/ }).first().click()
  await activeForm(page).getByLabel('Role or persona').fill('fast')
  expect(Date.now() - started).toBeLessThan(2_000)
})

test('2.7 many_rows_stay_responsive', async ({ page }) => {
  await chooseTechnique(page, 'Few-Shot')
  const form = activeForm(page)
  for (let index = 1; index < 10; index += 1) await form.getByRole('button', { name: 'Add example' }).click()
  await form.getByLabel('Example input').nth(9).fill('Row ten value')
  await form.getByRole('button', { name: 'Remove example 5' }).click()
  await expect(form.locator('.dynamic-row')).toHaveCount(9)
  await chooseTechnique(page, 'Role-Based')
  await expect(activeForm(page).getByLabel('Role or persona')).toHaveValue('')
  await chooseTechnique(page, 'Few-Shot')
  await expect(activeForm(page).getByLabel('Example input').nth(8)).toHaveValue('Row ten value')
})

test('2.8 keyboard_operability_focus', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.getByRole('button', { name: /Few-Shot/ }).first().focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Few-Shot', exact: true })).toBeVisible()
  await page.waitForTimeout(180)
  const form = activeForm(page)
  await form.getByLabel('Task description').fill('Keyboard flow')
  const inputs = form.getByLabel('Example input')
  const outputs = form.getByLabel('Expected output')
  const initialRows = await inputs.count()
  for (let index = 0; index < initialRows; index += 1) {
    await inputs.nth(index).fill(`Keyboard input ${index + 1}`)
    await outputs.nth(index).fill(`Keyboard output ${index + 1}`)
  }
  await form.getByRole('button', { name: 'Add example' }).focus()
  await page.keyboard.press('Enter')
  const rows = form.locator('.dynamic-row:not([style]):has(input[name^="examples"])')
  await expect(rows).toHaveCount(initialRows + 1)
  await rows.last().getByRole('button', { name: `Remove example ${initialRows + 1}` }).focus()
  await page.keyboard.press('Space')
  await expect(rows).toHaveCount(initialRows)
  await form.getByRole('button', { name: 'Add document' }).focus()
  await page.keyboard.press('Enter')
  await page.getByRole('option', { name: /brand-voice-guide\.pdf/ }).focus()
  await page.keyboard.press('Enter')
  await form.getByRole('button', { name: 'Generate prompt' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#prompt-preview')).toContainText('Keyboard flow')
  await page.getByRole('button', { name: 'Copy assembled prompt' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Prompt copied' })).toBeVisible()
})

test('2.9 modal_focus_management', async ({ page }) => {
  await generateZeroShot(page)
  const launcher = page.getByRole('button', { name: 'Save to library' })
  await launcher.click()
  const dialog = dialogByHeading(page, 'Save prompt to library')
  await expect(dialog.getByLabel('Title')).toBeFocused()
  for (let index = 0; index < 8; index += 1) {
    await page.keyboard.press('Tab')
    expect(await page.evaluate(() => Boolean(document.activeElement?.closest('[role="dialog"]')))).toBe(true)
  }
  for (let index = 0; index < 8; index += 1) {
    await page.keyboard.press('Shift+Tab')
    expect(await page.evaluate(() => Boolean(document.activeElement?.closest('[role="dialog"]')))).toBe(true)
  }
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(launcher).toBeFocused()
})

test('2.10 labels_errors_live_region', async ({ page }) => {
  const field = activeForm(page).getByLabel('Task description')
  const live = activeForm(page).locator('[aria-live="polite"]').first()
  await expect(live).toBeAttached()
  await field.focus()
  await field.blur()
  await expect(field).toHaveAttribute('aria-invalid', 'true')
  const describedBy = await field.getAttribute('aria-describedby')
  expect(describedBy).toBeTruthy()
  await expect(page.locator(`#${describedBy!.split(' ')[0]}`)).toContainText('Task description is required')
  await expect(live).toContainText('Task description has a validation error')
})

test('webmcp contract registers, reads, and mutates visible state', async ({ page }) => {
  const session = await page.evaluate(() => window.webmcp_session_info())
  expect(session).toMatchObject({ contract_version: 'zto-webmcp-v1', app: 'Template Forms', tool_count: 10 })
  const tools = await page.evaluate(() => window.webmcp_list_tools())
  expect(tools.map((tool: { name: string }) => tool.name)).toEqual(expect.arrayContaining(['form.validate', 'browse.open', 'browse.search', 'entity.delete', 'artifact.copy']))
  const read = await page.evaluate(() => window.webmcp_invoke_tool('form.validate', {}))
  expect(read).toEqual({ ok: true, valid: false })
  const mutate = await page.evaluate(() => window.webmcp_invoke_tool('browse.search', { query: 'Launch message' }))
  expect(mutate).toMatchObject({ ok: true, query: 'Launch message', matches: 1 })
  await expect(page.getByRole('heading', { name: 'Prompt library' })).toBeVisible()
  await expect(page.locator('.library-row')).toHaveCount(1)
  await expect(page.locator('.library-row')).toContainText('Launch message patterns')
})
