/* NOT-AUTOMATABLE: none. */
import { activeForm, chooseTechnique, confirmDelete, dialogByHeading, exportedDocument, fillFewShot, generateZeroShot, libraryCount, loadApp, openLibrary, saveCurrentPrompt, test, expect } from './helpers'

test.beforeEach(async ({ page }) => loadApp(page))

test('6.1 generate_and_save_few_shot_end_to_end', async ({ page }) => {
  const form = await fillFewShot(page, 'Label product updates')
  await form.getByRole('button', { name: 'Add example' }).click()
  await form.getByLabel('Example input').nth(1).fill('Resolved a crash')
  await form.getByLabel('Expected output').nth(1).fill('Fix')
  await form.getByRole('button', { name: 'Add document' }).click()
  await page.getByRole('option', { name: /research-notes\.md/ }).click()
  await form.getByRole('button', { name: 'Generate prompt' }).click()
  const preview = page.locator('#prompt-preview pre')
  await expect(preview).toContainText('Added an audit log')
  await expect(preview).toContainText('Resolved a crash')
  await expect(preview).toContainText('research-notes.md')
  await saveCurrentPrompt(page, 'Release classifier')
  await expect(page.getByRole('button', { name: /Few-Shot/ }).first()).toContainText('Saved')
  await openLibrary(page)
  expect(await libraryCount(page)).toBe(6)
})

test('6.2 invalid_technique_submit_inline_validation', async ({ page }) => {
  await chooseTechnique(page, 'Chain-of-Thought')
  const form = activeForm(page)
  await expect(form.getByRole('button', { name: 'Generate prompt' })).toBeDisabled()
  await form.evaluate((element) => (element as HTMLFormElement).requestSubmit())
  await expect(form.getByText('Goal is required. Enter goal.')).toBeVisible()
  await expect(page.getByLabel('Prompt preview')).toContainText('Your assembled prompt will appear here')
  await form.getByLabel('Goal').fill('Produce a valid reasoning plan')
  await expect(form.getByText('Goal is required. Enter goal.')).toHaveCount(0)
})

test('6.3 draft_retention_across_technique_switch', async ({ page }) => {
  await activeForm(page).getByLabel('Task description').fill('Retained zero-shot')
  await chooseTechnique(page, 'Role-Based')
  await activeForm(page).getByLabel('Role or persona').fill('analyst')
  await chooseTechnique(page, 'Zero-Shot')
  await expect(activeForm(page).getByLabel('Task description')).toHaveValue('Retained zero-shot')
  await expect(page.getByRole('button', { name: /Zero-Shot/ }).first()).toContainText('In progress')
})

test('6.4 delete_library_entry_updates_count', async ({ page }) => {
  await openLibrary(page)
  const before = await libraryCount(page)
  await confirmDelete(page, 'Executive brief distiller')
  expect(await libraryCount(page)).toBe(before - 1)
  await expect(page.getByRole('button', { name: 'Open Executive brief distiller' })).toHaveCount(0)
})

test('6.5 library_to_form_round_trip', async ({ page }) => {
  await openLibrary(page)
  await page.getByRole('button', { name: 'Open Support reply exemplar' }).first().click()
  await expect(activeForm(page).getByLabel('Example input')).toHaveValue(/order was expected yesterday/)
  await expect(page.locator('#prompt-preview pre')).toContainText('shipment is delayed')
  await activeForm(page).getByLabel('Task description').fill('Write a warm reply for a delayed shipment')
  await activeForm(page).getByRole('button', { name: 'Generate prompt' }).click()
  await expect(page.locator('#prompt-preview pre')).toContainText('warm reply')
})

test('6.6 empty_library_shows_designed_empty_state', async ({ page }) => {
  await openLibrary(page)
  for (const title of ['Executive brief distiller', 'Support reply exemplar', 'Launch message patterns', 'Research synthesis path', 'Product strategist review']) await confirmDelete(page, title)
  await expect(page.getByRole('heading', { name: 'Your library is ready for its first prompt' })).toBeVisible()
  await expect(page.getByText('Build and generate a prompt, then save it here for future use.')).toBeVisible()
})

test('6.7 technique_sidebar_status_chips_track_lifecycle', async ({ page }) => {
  const entry = page.getByRole('button', { name: /Zero-Shot/ }).first()
  await expect(entry).toContainText('Neutral')
  await activeForm(page).getByLabel('Task description').fill('Lifecycle')
  await expect(entry).toContainText('In progress')
  await activeForm(page).getByRole('button', { name: 'Generate prompt' }).click()
  await expect(entry).toContainText('Generated')
  await saveCurrentPrompt(page, 'Lifecycle saved')
  await expect(entry).toContainText('Saved')
  await expect(entry).toHaveAttribute('aria-current', 'page')
})

test('6.8 forms_library_switch_preserves_drafts', async ({ page }) => {
  await chooseTechnique(page, 'Role-Based')
  await activeForm(page).getByLabel('Role or persona').fill('retained role')
  await openLibrary(page)
  await page.getByRole('button', { name: 'Studio' }).click()
  await expect(page.getByRole('heading', { name: 'Role-Based', exact: true })).toBeVisible()
  await expect(activeForm(page).getByLabel('Role or persona')).toHaveValue('retained role')
})

test('6.9 save_export_and_attachment_overlays', async ({ page }) => {
  await chooseTechnique(page, 'Few-Shot')
  await activeForm(page).getByRole('button', { name: 'Add document' }).click()
  await expect(page.getByRole('listbox', { name: 'Choose a reference document' })).toBeVisible()
  await page.getByRole('button', { name: 'Close document picker' }).click()
  await expect(page.getByRole('listbox', { name: 'Choose a reference document' })).toHaveCount(0)
  await chooseTechnique(page, 'Zero-Shot')
  await generateZeroShot(page)
  await page.getByRole('button', { name: 'Save to library' }).click()
  await dialogByHeading(page, 'Save prompt to library').getByRole('button', { name: 'Cancel' }).click()
  await openLibrary(page)
  await page.getByRole('button', { name: 'Export library' }).click()
  await expect(page.getByRole('region', { name: 'Export library' })).toBeVisible()
  await page.getByRole('button', { name: 'Export library' }).click()
  await expect(page.getByRole('region', { name: 'Export library' })).toHaveCount(0)
})

test('6.10 export_import_recover_without_reload', async ({ page }) => {
  await openLibrary(page)
  const baseline = await exportedDocument(page)
  await confirmDelete(page, 'Executive brief distiller')
  await page.getByRole('button', { name: 'Import JSON' }).click()
  let dialog = dialogByHeading(page, 'Import library JSON')
  await dialog.getByLabel('Library document').fill(JSON.stringify(baseline))
  await dialog.getByRole('button', { name: 'Replace library' }).click()
  expect(await libraryCount(page)).toBe(5)
  await page.getByRole('button', { name: 'Import JSON' }).click()
  dialog = dialogByHeading(page, 'Import library JSON')
  await dialog.getByLabel('Library document').fill('{}')
  await dialog.getByRole('button', { name: 'Replace library' }).click()
  await expect(page.getByText(/does not match/).last()).toBeVisible()
  expect(await libraryCount(page)).toBe(5)
})

test('6.11 export_library_after_save_flow', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  const preview = await generateZeroShot(page, 'Export flow prompt')
  const promptText = await preview.innerText()
  await saveCurrentPrompt(page, 'Export flow entry')
  await openLibrary(page)
  let document = await exportedDocument(page)
  expect(document.entries.at(-1)).toMatchObject({ title: 'Export flow entry', technique: 'zero-shot', promptText })
  await page.getByRole('region', { name: 'Export library' }).getByRole('button', { name: 'Copy' }).click()
  expect(JSON.parse(await page.evaluate(() => navigator.clipboard.readText())).entries.at(-1).title).toBe('Export flow entry')
  await confirmDelete(page, 'Export flow entry')
  document = await exportedDocument(page)
  expect(document.entries.some((entry: { title: string }) => entry.title === 'Export flow entry')).toBe(false)
})

test('6.12 import_library_round_trip_flow', async ({ page }) => {
  await generateZeroShot(page, 'Import round trip')
  await saveCurrentPrompt(page, 'Import flow entry')
  await openLibrary(page)
  const exported = await exportedDocument(page)
  await confirmDelete(page, 'Import flow entry')
  await page.getByRole('button', { name: 'Import JSON' }).click()
  const dialog = dialogByHeading(page, 'Import library JSON')
  await dialog.getByLabel('Library document').fill(JSON.stringify(exported))
  await dialog.getByRole('button', { name: 'Replace library' }).click()
  expect((await exportedDocument(page)).entries).toEqual(exported.entries)
})
