import { chromium } from '/usr/lib/node_modules/playwright/index.mjs'

const browser = await chromium.connectOverCDP('http://127.0.0.1:9222')
const context = browser.contexts()[0]
const page = await context.newPage()
const logs = []
page.on('console', (message) => { if (['error', 'warning'].includes(message.type())) logs.push(`${message.type()}: ${message.text()}`) })
page.on('pageerror', (error) => logs.push(`pageerror: ${error.message}`))
await page.setViewportSize({ width: 1440, height: 1000 })
await page.goto('http://127.0.0.1:3000', { waitUntil: 'networkidle' })
await page.evaluate(() => localStorage.clear())
await page.reload({ waitUntil: 'networkidle' })
await page.getByRole('button', { name: 'Triage', exact: true }).click()
await page.waitForTimeout(500)
console.log(JSON.stringify({ afterClickBody: (await page.locator('body').innerText()).slice(0, 1000), afterClickLogs: logs }))
await page.screenshot({ path: '/tmp/taskfoundry-triage-debug.png', fullPage: true })
await page.getByRole('heading', { name: 'Shape the evaluation queue.' }).waitFor()
const tip = page.getByRole('button', { name: 'Dismiss Triage is reversible tip' })
if (await tip.count()) await tip.click()
const rejectedBefore = Number(await page.locator('.stat-card').nth(2).locator('.stat-value').textContent())
const inboxCard = page.locator('.board-column').nth(0).locator('.triage-card').first()
const cardTitle = await inboxCard.locator('.triage-card-title').textContent()
await inboxCard.getByRole('button', { name: 'Reject PR' }).click()
const dialog = page.getByRole('dialog')
await dialog.getByRole('button', { name: 'Reject PR' }).click()
const missingReason = await dialog.getByText(/reason:/).textContent()
await dialog.locator('select[name="reason"]').selectOption('docs-only')
await dialog.getByRole('button', { name: 'Reject PR' }).click()
const rejectedAfter = Number(await page.locator('.stat-card').nth(2).locator('.stat-value').textContent())
await page.getByRole('button', { name: 'Undo' }).click()
const rejectedUndone = Number(await page.locator('.stat-card').nth(2).locator('.stat-value').textContent())
console.log(JSON.stringify({ cardTitle, missingReason, rejectedBefore, rejectedAfter, rejectedUndone, logs }, null, 2))
await browser.close()
