<script setup>
import { computed, h, onMounted, onBeforeUnmount, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { NButton, NConfigProvider, NInput, NSelect, NTag, NTable, NModal, NRadioButton, NRadioGroup, NProgress, NScrollbar } from 'naive-ui'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { BarChart } from 'echarts/charts'
import { GridComponent, TooltipComponent } from 'echarts/components'
import { PhListChecks as ListChecks, PhUsersThree as UsersThree, PhFileText as FileText, PhMagnifyingGlass as MagnifyingGlass, PhX as X, PhArrowLeft as ArrowLeft, PhPlay as Play, PhPause as Pause, PhArrowCounterClockwise as ArrowCounterClockwise, PhClock as Clock, PhCheckCircle as CheckCircle, PhXCircle as XCircle, PhCircle as Circle, PhCopy as Copy, PhDownloadSimple as DownloadSimple, PhUploadSimple as UploadSimple, PhChartBar as ChartBar, PhFunnel as Funnel, PhGitBranch as GitBranch, PhChatCircleText as ChatCircleText, PhSidebarSimple as SidebarSimple, PhDatabase as Database, PhSparkle as Sparkle } from '@phosphor-icons/vue'
import { useAuditStore, title } from './store'
import { CHECKS, CRITERIA, REVIEWERS, FEEDBACK_VERDICTS, STAGES, REPOSITORIES, FeedbackEntrySchema, CriterionFailVerdictSchema, EscalationSchema, ResolutionSchema, firstZodError } from './contracts'
import CriterionRow from './components/CriterionRow.vue'
import FeedbackForm from './components/FeedbackForm.vue'
import EscalationForms from './components/EscalationForms.vue'
import ImportModal from './components/ImportModal.vue'

use([CanvasRenderer,BarChart,GridComponent,TooltipComponent])
const store=useAuditStore()
const { records, activeView, selectedTask, selectedReviewer, visibleRecords, checkRates, criterionRanking, reviewerActivity, datasetSummary, activeFilterChips, touchedRecords }=storeToRefs(store)
const evidenceFilter=ref('all')
const activeViolation=ref(null)
const nowTick=ref(Date.now())
const timer=setInterval(()=>nowTick.value=Date.now(),250)
onBeforeUnmount(()=>clearInterval(timer))
const opt=a=>a.map(value=>({label:value,value}))
const stageOptions=opt(STAGES)
const checkOptions=opt(CHECKS)
const criterionOptions=opt(CRITERIA)
const reviewerOptions=opt(REVIEWERS)
const repoOptions=opt(REPOSITORIES)
const outcomeOptions=opt(['pass','fail'])
const themeOverrides={common:{primaryColor:'#4f6f52',primaryColorHover:'#3f6044',primaryColorPressed:'#345239',borderRadius:'10px',fontFamily:'Inter, Avenir Next, system-ui, sans-serif'},Button:{borderRadiusMedium:'10px'},Input:{borderRadius:'10px'}}

const checkChartOption=computed(()=>({animationDuration:430,color:['#58795c'],grid:{left:46,right:18,top:18,bottom:78},tooltip:{trigger:'axis',formatter:p=>`${p[0].name}<br/><strong>${p[0].value}% pass</strong>`},xAxis:{type:'category',data:checkRates.value.map(x=>x.check),axisLabel:{rotate:42,fontSize:10}},yAxis:{type:'value',max:100,axisLabel:{formatter:'{value}%'}},series:[{type:'bar',data:checkRates.value.map(x=>x.passRate),barMaxWidth:26,itemStyle:{borderRadius:[5,5,0,0]}}]}))
const criterionChartOption=computed(()=>({animationDuration:430,color:['#d78362'],grid:{left:46,right:18,top:18,bottom:92},tooltip:{trigger:'axis',formatter:p=>`${p[0].name}<br/><strong>${p[0].value} failures</strong>`},xAxis:{type:'category',data:criterionRanking.value.map(x=>x.criterion),axisLabel:{rotate:48,fontSize:9}},yAxis:{type:'value',minInterval:1},series:[{type:'bar',data:criterionRanking.value.map(x=>x.failures),barMaxWidth:24,itemStyle:{borderRadius:[5,5,0,0]}}]}))
const reviewerChartOption=computed(()=>{const r=reviewerActivity.value.find(x=>x.reviewer===selectedReviewer.value);return {animationDuration:430,color:['#58795c'],grid:{left:45,right:15,top:15,bottom:60},tooltip:{trigger:'axis'},xAxis:{type:'category',data:FEEDBACK_VERDICTS,axisLabel:{rotate:18}},yAxis:{type:'value',minInterval:1},series:[{type:'bar',data:FEEDBACK_VERDICTS.map(v=>r?.verdictMix[v]||0),barMaxWidth:42,itemStyle:{borderRadius:[5,5,0,0]}}]}})
const activeRun=computed(()=>selectedTask.value?store.runs[selectedTask.value.slug]:null)
const runCounts=computed(()=>{const run=activeRun.value;if(!run)return {done:0,failed:0};return {done:run.steps.filter(s=>['complete','failed'].includes(s.status)).length,failed:run.steps.filter(s=>s.status==='failed').length}})
const elapsed=computed(()=>{const run=activeRun.value;if(!run)return 0;return Math.round(((run.completedAt?Date.parse(run.completedAt):nowTick.value)-Date.parse(run.startedAt))/100)/10})
const filteredEvidence=computed(()=>{const items=activeRun.value?.evidence||[];return evidenceFilter.value==='all'?items:items.filter(e=>e.type===evidenceFilter.value)})
const reportPreview=computed(()=>store.preview(store.exportFormat))
const reviewerEntries=computed(()=>records.value.flatMap(task=>task.feedback.filter(f=>f.reviewer===selectedReviewer.value).map(f=>({...f,slug:task.slug})) ).sort((a,b)=>String(b.at).localeCompare(String(a.at))))
const currentBatchRun=computed(()=>store.batch.active?store.runs[store.batch.slugs[store.batch.index]]:null)

const passCount=t=>CHECKS.filter(c=>t.checkResults[c].status==='pass').length
const criteriaCount=t=>CRITERIA.filter(c=>t.criteria[c].verdict==='pass').length
const failedCriteria=t=>CRITERIA.filter(c=>t.criteria[c].verdict==='fail')
const admissionText=t=>failedCriteria(t).length?`Held · ${failedCriteria(t).join(', ')}`:(passCount(t)===9&&criteriaCount(t)===10?(t.stage==='resolved'?'Resolved':'Admitted'):'Review in progress')
const stageClass=s=>`stage-${s}`
const checkClass=s=>`check-${s}`
const verdictClass=v=>`verdict-${v.toLowerCase().replaceAll(' ','-')}`
const fmt=t=>t?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(t)):'—'
const sortMark=key=>store.sort.key===key?(store.sort.direction==='asc'?'↑':'↓'):'↕'
const reachedAt=(task,stage)=>task.stageHistory.findLast?.(x=>x.stage===stage)?.at || [...task.stageHistory].reverse().find(x=>x.stage===stage)?.at
const currentStepIcon=s=>s.status==='complete'?CheckCircle:s.status==='failed'?XCircle:s.status==='running'||s.status==='retrying'?ArrowCounterClockwise:Circle
function checkClicked(task,check){const result=task.checkResults[check];activeViolation.value=result.status==='fail'?{check,text:result.violation}:null;if(activeRun.value){activeRun.value.highlighted=check;setTimeout(()=>document.querySelector(`[data-step="${check}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),20)}}
function chooseEvidence(entry){if(!activeRun.value)return;const check=CHECKS.find(c=>entry.detail.startsWith(c));if(check){activeRun.value.highlighted=check;document.querySelector(`[data-step="${check}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}}
async function copyExport(){const text=store.recordExport(store.exportFormat);await navigator.clipboard.writeText(text);store.notify('Exact preview copied to clipboard')}
function downloadExport(){const text=store.recordExport(store.exportFormat);const ext=store.exportFormat==='json'?'json':'md';const url=URL.createObjectURL(new Blob([text],{type:store.exportFormat==='json'?'application/json':'text/markdown'}));const a=document.createElement('a');a.href=url;a.download=`quality-audit-${new Date().toISOString().slice(0,10)}.${ext}`;a.click();URL.revokeObjectURL(url)}

function registerWebMcp(){
  const tools=[]; const add=(name,description,inputSchema,handler)=>tools.push({name,description,inputSchema,handler})
  add('browse_open','Open a bounded audit desk destination.',{type:'object',properties:{destination:{enum:['queue','task-detail','reviewers','reviewer-detail','report']},slug:{type:'string'},reviewer:{enum:REVIEWERS}},required:['destination']},a=>{if(a.destination==='task-detail')store.openTask(a.slug);else if(a.destination==='reviewer-detail')store.openReviewer(a.reviewer);else store.setView(a.destination);return {visibleView:store.activeView}})
  add('browse_search','Search audit tasks by slug or repository.',{type:'object',properties:{query:{type:'string'}},required:['query']},a=>{store.search=a.query;store.setView('queue');return {visibleCount:store.visibleRecords.length}})
  add('browse_apply_filter','Apply a bounded queue filter.',{type:'object',properties:{filter:{enum:['check-outcome','criterion-outcome','lifecycle-stage','reviewer']},value:{type:'string'},outcome:{enum:['pass','fail']}},required:['filter','value']},a=>{const k={'check-outcome':'check','criterion-outcome':'criterion','lifecycle-stage':'stage',reviewer:'reviewer'}[a.filter];store.applyFilter(k,a.value,a.outcome);return {visibleCount:store.visibleRecords.length}})
  add('browse_clear_filter','Clear all queue filters.',{type:'object',properties:{}},()=>{store.clearFilters();return {visibleCount:store.visibleRecords.length}})
  add('browse_sort','Sort the task queue.',{type:'object',properties:{column:{enum:['slug','repository','stage','checks','criteria','feedback','lastActivity']},direction:{enum:['column-ascending','column-descending']}},required:['column','direction']},a=>{store.sort={key:a.column,direction:a.direction==='column-ascending'?'asc':'desc'};return {sort:store.sort}})
  add('browse_set_locale','Set the bounded interface locale.',{type:'object',properties:{locale:{enum:['en']}},required:['locale']},()=>({locale:'en'}))
  add('browse_set_theme','Set the bounded interface theme.',{type:'object',properties:{theme:{enum:['light']}},required:['theme']},()=>({theme:'light'}))
  add('form_validate','Validate a declared workflow payload without saving.',{type:'object',properties:{workflow:{enum:['add-feedback-entry','set-criterion-verdict','escalate-task','resolve-task']},slug:{type:'string'},payload:{type:'object'}},required:['workflow','payload']},a=>({valid:validateWorkflow(a.workflow,a.payload).ok,error:validateWorkflow(a.workflow,a.payload).error||null}))
  add('form_submit','Submit a declared workflow through product handlers.',{type:'object',properties:{workflow:{enum:['add-feedback-entry','set-criterion-verdict','escalate-task','apply-simulated-fixes','resolve-task']},slug:{type:'string'},payload:{type:'object'}},required:['workflow','slug']},a=>submitWorkflow(a))
  for(const op of ['cancel','reset','advance','return'])add(`form_${op}`,`${title(op)} the visible form workflow.`,{type:'object',properties:{}},()=>{store.importOpen=false;return {visible:true,operation:op}})
  add('session_start','Start a check-run or filtered batch run.',{type:'object',properties:{demo:{enum:['check-run','batch-run-filtered','re-audit-run']},slug:{type:'string'}},required:['demo']},a=>{if(a.demo==='batch-run-filtered')store.startBatch();else store.runChecks(a.slug||store.selectedSlug);return {started:true}})
  add('session_pause','Pause the current check or batch run.',{type:'object',properties:{slug:{type:'string'}}},a=>{if(store.batch.active)store.pauseBatch();else store.pauseRun(a.slug||store.selectedSlug);return {paused:true}})
  add('session_resume','Resume the current check or batch run.',{type:'object',properties:{slug:{type:'string'}}},a=>{if(store.batch.active)store.resumeBatch();else store.resumeRun(a.slug||store.selectedSlug);return {resumed:true}})
  for(const op of ['stop','restart','advance','trigger_demo','connect','disconnect'])add(`session_${op}`,`${title(op)} a declared audit session.`,{type:'object',properties:{}},()=>({available:false,reason:'This operation has no honest state transition in the simulated audit desk.'}))
  add('artifact_copy','Copy the active export through the visible product handler.',{type:'object',properties:{format:{enum:['audit-package-json','audit-report-markdown']}},required:['format']},a=>{store.exportFormat=a.format==='audit-package-json'?'json':'markdown';copyExport();return {format:a.format,confirmation:'Visible copy confirmation shown'}})
  add('artifact_export','Download the active export through the visible product handler.',{type:'object',properties:{format:{enum:['audit-package-json','audit-report-markdown']}},required:['format']},a=>{store.exportFormat=a.format==='audit-package-json'?'json':'markdown';downloadExport();return {format:a.format,confirmation:'Visible download confirmation shown'}})
  add('artifact_import','Open the visible Audit Package JSON import surface.',{type:'object',properties:{mode:{enum:['paste','file-picker']}},required:['mode']},a=>{store.setView('report');store.importOpen=true;return {visible:true,mode:a.mode}})
  for(const op of ['print_preview','convert'])add(`artifact_${op}`,`${title(op)} the active audit artifact.`,{type:'object',properties:{}},()=>({available:false,reason:'No declared conversion or print workflow is available.'}))
  window.webmcp_session_info=()=>({contract_version:'zto-webmcp-v1',modules:['browse-query-v1','form-workflow-v1','command-session-v1','artifact-transfer-v1'],app:'Benchwise Audit Desk'})
  window.webmcp_list_tools=()=>tools.map(({handler,...x})=>x)
  window.webmcp_invoke_tool=async({name,arguments:args={}})=>{const tool=tools.find(t=>t.name===name);if(!tool)throw new Error(`Unknown tool: ${name}`);return tool.handler(args)}
}
function parseResult(schema,payload){const r=schema.safeParse(payload);return r.success?{ok:true}:{ok:false,error:firstZodError(r.error)}}
function validateWorkflow(workflow,payload){if(workflow==='add-feedback-entry')return parseResult(FeedbackEntrySchema,{reviewer:payload.reviewer,verdict:payload['feedback-verdict'],findings:payload.findings});if(workflow==='set-criterion-verdict')return payload['criterion-verdict']==='pass'?{ok:true}:parseResult(CriterionFailVerdictSchema,{criterion:payload.criterion,verdict:'fail',rationale:payload['fail-rationale']});if(workflow==='escalate-task')return parseResult(EscalationSchema,{category:payload['escalation-category'],summary:payload['escalation-summary']});if(workflow==='resolve-task')return parseResult(ResolutionSchema,{note:payload['resolution-note']});return {ok:false,error:'Unknown workflow'}}
function submitWorkflow(a){const p=a.payload||{};if(a.workflow==='add-feedback-entry')return store.addFeedback(a.slug,{reviewer:p.reviewer,verdict:p['feedback-verdict'],findings:p.findings});if(a.workflow==='set-criterion-verdict')return store.saveCriterion(a.slug,p.criterion,p['criterion-verdict'],p['fail-rationale']);if(a.workflow==='escalate-task')return store.escalate(a.slug,{category:p['escalation-category'],summary:p['escalation-summary']});if(a.workflow==='apply-simulated-fixes')return {ok:store.applyFixes(a.slug)};if(a.workflow==='resolve-task')return store.resolve(a.slug,{note:p['resolution-note']});return {ok:false,error:'Unknown workflow'}}
onMounted(registerWebMcp)
</script>

<template>
<NConfigProvider :theme-overrides="themeOverrides">
  <div class="min-h-screen bg-paper text-ink">
    <aside class="desktop-rail fixed inset-y-0 left-0 z-30 flex w-[224px] flex-col border-r border-line bg-[#fbfcf8] p-4">
      <div class="mb-8 flex items-center gap-3 px-2 pt-2"><div class="grid size-9 place-items-center rounded-xl bg-moss text-white"><ListChecks :size="20" weight="bold"/></div><div><div class="text-lg font-black tracking-tight">Benchwise</div><div class="eyebrow">Audit desk</div></div></div>
      <nav class="space-y-1" aria-label="Primary navigation">
        <button :class="['nav-btn',activeView==='queue'&&'active']" @click="store.setView('queue')"><ListChecks :size="20"/> Queue <span class="ml-auto text-xs">{{ records.length }}</span></button>
        <button :class="['nav-btn',['reviewers','reviewer-detail'].includes(activeView)&&'active']" @click="store.setView('reviewers')"><UsersThree :size="20"/> Reviewers</button>
        <button :class="['nav-btn',activeView==='report'&&'active']" @click="store.setView('report')"><FileText :size="20"/> Report <span v-if="touchedRecords.length" class="ml-auto size-2 rounded-full bg-coral"></span></button>
      </nav>
      <div class="mt-auto rounded-xl border border-line bg-white p-3"><div class="flex items-center gap-2 text-xs font-extrabold"><Database :size="16"/> In-memory session</div><p class="mt-1 text-[11px] leading-4 text-muted">Reload restores the seeded benchmark desk.</p></div>
    </aside>

    <div class="mobile-top sticky top-0 z-20 hidden items-center justify-between border-b border-line bg-[#fbfcf8]/95 px-4 py-3 backdrop-blur"><div class="flex items-center gap-2 font-black"><ListChecks :size="20"/> Benchwise</div><button class="soft-btn !p-2" aria-label="Open navigation" @click="store.mobileNav=true"><SidebarSimple :size="20"/></button></div>
    <NModal v-model:show="store.mobileNav"><div class="fixed inset-y-0 left-0 w-[270px] bg-[#fbfcf8] p-5 shadow-2xl"><div class="mb-7 flex items-center justify-between"><span class="font-black">Audit desk</span><button class="soft-btn !p-2" @click="store.mobileNav=false"><X :size="18"/></button></div><nav class="space-y-2"><button class="nav-btn" @click="store.setView('queue')"><ListChecks/>Queue</button><button class="nav-btn" @click="store.setView('reviewers')"><UsersThree/>Reviewers</button><button class="nav-btn" @click="store.setView('report')"><FileText/>Report</button></nav></div></NModal>

    <main class="main-shell ml-[224px] min-h-screen p-6 lg:p-8">
      <Transition name="detail" mode="out-in">
      <section v-if="activeView==='queue'" key="queue" class="mx-auto max-w-[1600px]">
        <header class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow">Benchmark authoring pipeline</p><h1 class="mt-1 text-3xl font-black tracking-tight">Audit queue</h1><p class="mt-1 text-sm text-muted">Deterministic checks and admission evidence across {{ REPOSITORIES.length }} repositories.</p></div><div class="flex gap-2"><NButton :disabled="!visibleRecords.length||store.batch.active" type="primary" @click="store.startBatch"><Play class="mr-1"/>Run checks on all filtered</NButton></div></header>

        <section class="panel mb-5 overflow-hidden" aria-labelledby="rollup-heading">
          <div class="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 id="rollup-heading" class="text-base font-extrabold">Live rollup</h2><p class="mt-0.5 text-xs text-muted">Cells filter the queue. Charts reflect the shared session.</p></div><ChartBar :size="20" class="text-moss"/></div>
          <div class="overflow-x-auto p-4"><p class="eyebrow mb-2">Deterministic checks</p><div class="flex min-w-max gap-2"><button v-for="x in checkRates" :key="x.check" :class="['roll-cell',store.rollupPulse&&'pulse']" @click="store.applyFilter('check',x.check,'pass')"><span class="block text-[11px] font-bold text-muted">{{ x.check }}</span><strong class="mt-1 block text-xl">{{ x.passRate }}%</strong><span class="text-[11px] text-muted">{{ x.passes }} pass · {{ x.fails }} fail</span></button></div>
            <p class="eyebrow mb-2 mt-4">Admission criteria</p><div class="flex min-w-max gap-2"><button v-for="x in criterionRanking" :key="x.criterion" class="roll-cell" @click="store.applyFilter('criterion',x.criterion,'fail')"><span class="block max-w-[120px] truncate text-[11px] font-bold text-muted" :title="x.criterion">{{ x.criterion }}</span><strong class="mt-1 block text-xl">{{ x.failures }}</strong><span class="text-[11px] text-muted">failures</span></button></div>
            <p class="eyebrow mb-2 mt-4">Reviewer entries</p><div class="flex min-w-max gap-2"><button v-for="x in reviewerActivity" :key="x.reviewer" class="roll-cell" @click="store.applyFilter('reviewer',x.reviewer)"><span class="block text-[11px] font-bold text-muted">{{ x.reviewer }}</span><strong class="mt-1 block text-xl">{{ x.entryCount }}</strong><span class="text-[11px] text-muted">entries</span></button></div></div>
          <div class="grid gap-4 border-t border-line p-4 lg:grid-cols-2"><div><h3 class="mb-1 text-sm font-extrabold">Pass rate per check</h3><VChart class="h-[280px] w-full" :option="checkChartOption" autoresize/></div><div><h3 class="mb-1 text-sm font-extrabold">Criteria ranked by failure count</h3><VChart class="h-[280px] w-full" :option="criterionChartOption" autoresize/></div></div>
        </section>

        <section class="panel overflow-hidden">
          <div class="border-b border-line p-4"><div class="flex flex-col gap-3 xl:flex-row xl:items-center"><label class="xl:max-w-[320px] xl:flex-1"><span class="sr-only">Search queue</span><NInput v-model:value="store.search" clearable placeholder="Search task slug or repository"><template #prefix><MagnifyingGlass/></template></NInput></label><div class="grid flex-1 grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6"><NSelect v-model:value="store.filters.repository" clearable placeholder="Repository" :options="repoOptions"/><NSelect v-model:value="store.filters.check" clearable placeholder="Check" :options="checkOptions"/><NSelect v-model:value="store.filters.checkOutcome" placeholder="Check outcome" :options="outcomeOptions"/><NSelect v-model:value="store.filters.criterion" clearable placeholder="Criterion" :options="criterionOptions"/><NSelect v-model:value="store.filters.criterionOutcome" placeholder="Criterion outcome" :options="outcomeOptions"/><NSelect v-model:value="store.filters.stage" clearable placeholder="Stage" :options="stageOptions"/></div><NSelect v-model:value="store.filters.reviewer" clearable class="xl:max-w-[190px]" placeholder="Reviewer" :options="reviewerOptions"/></div>
            <div v-if="activeFilterChips.length" class="mt-3 flex flex-wrap items-center gap-2"><span class="text-xs font-bold text-muted">Active filters</span><NTag v-for="chip in activeFilterChips" :key="chip.key" closable round @close="store.removeFilter(chip.key)">{{ chip.label }}</NTag><NButton size="tiny" text @click="store.clearFilters">Clear all</NButton></div></div>
          <div class="overflow-x-auto">
            <NTable v-if="visibleRecords.length" :single-line="false" class="min-w-[1050px]" striped>
              <thead><tr><th><button class="flex items-center gap-1 font-extrabold" @click="store.sortBy('slug')">Task {{ sortMark('slug') }}</button></th><th><button class="flex items-center gap-1 font-extrabold" @click="store.sortBy('repository')">Repository {{ sortMark('repository') }}</button></th><th><button class="font-extrabold" @click="store.sortBy('stage')">Stage {{ sortMark('stage') }}</button></th><th><button class="font-extrabold" @click="store.sortBy('checks')">Checks {{ sortMark('checks') }}</button></th><th><button class="font-extrabold" @click="store.sortBy('criteria')">Criteria {{ sortMark('criteria') }}</button></th><th><button class="font-extrabold" @click="store.sortBy('feedback')">Feedback {{ sortMark('feedback') }}</button></th><th><button class="font-extrabold" @click="store.sortBy('lastActivity')">Last activity {{ sortMark('lastActivity') }}</button></th><th><span class="sr-only">Open</span></th></tr></thead>
              <tbody><tr v-for="task in visibleRecords" :key="task.slug" tabindex="0" class="row-hover cursor-pointer" @click="store.openTask(task.slug)" @keydown.enter="store.openTask(task.slug)"><td><span class="block max-w-[245px] truncate font-mono text-xs font-bold" :title="task.slug">{{ task.slug }}</span></td><td class="text-xs">{{ task.repository }}</td><td><span :class="['stage-badge',stageClass(task.stage)]">{{ task.stage }}</span></td><td><strong>{{ passCount(task) }}</strong><span class="text-muted"> of 9</span></td><td><strong>{{ criteriaCount(task) }}</strong><span class="text-muted"> of 10</span></td><td>{{ task.feedback.length }}</td><td class="text-xs text-muted">{{ fmt(task.lastActivity) }}</td><td>›</td></tr></tbody>
            </NTable>
            <div v-else class="grid min-h-[320px] place-items-center p-8 text-center"><div><Funnel class="mx-auto mb-3 text-muted" :size="34"/><h3 class="text-lg font-black">No tasks match these filters</h3><p class="mb-4 mt-1 text-sm text-muted">Clear the active filters to restore the full audit queue.</p><NButton type="primary" @click="store.clearFilters">Clear filters</NButton></div></div>
          </div>
          <div class="border-t border-line px-4 py-3 text-xs text-muted">Showing {{ visibleRecords.length }} of {{ records.length }} tasks</div>
        </section>
      </section>

      <section v-else-if="activeView==='task-detail'&&selectedTask" :key="selectedTask.slug" class="mx-auto max-w-[1320px]">
        <button class="mb-5 flex items-center gap-2 text-sm font-extrabold text-moss" @click="store.setView('queue')"><ArrowLeft/>Back to queue</button>
        <header class="mb-5 flex flex-wrap items-start justify-between gap-4"><div class="min-w-0"><div class="mb-2 flex flex-wrap items-center gap-2"><span :class="['stage-badge',stageClass(selectedTask.stage)]">{{ selectedTask.stage }}</span><span class="text-xs font-bold text-muted">{{ selectedTask.repository }}</span></div><h1 class="break-all text-2xl font-black tracking-tight sm:text-3xl">{{ selectedTask.slug }}</h1></div><div class="flex flex-wrap gap-2"><NButton v-if="!activeRun||activeRun.status==='complete'" type="primary" @click="store.runChecks(selectedTask.slug)"><Play/>{{ selectedTask.fixesApplied?'Run re-audit':'Run checks' }}</NButton><NButton v-if="activeRun?.status==='running'" @click="store.pauseRun(selectedTask.slug)"><Pause/>Pause run</NButton><NButton v-if="activeRun?.status==='paused'" type="primary" @click="store.resumeRun(selectedTask.slug)"><Play/>Resume run</NButton></div></header>

        <section class="panel mb-5 overflow-x-auto p-5"><div class="mb-4 flex items-center gap-2"><GitBranch class="text-moss"/><h2 class="font-extrabold">Lifecycle</h2></div><div class="flex min-w-[720px] items-start"><div v-for="(stage,i) in STAGES" :key="stage" class="relative flex flex-1 flex-col items-center text-center"><div v-if="i" :class="['absolute right-1/2 top-[14px] h-0.5 w-full transition-colors',reachedAt(selectedTask,stage)?'bg-moss':'bg-line']"></div><div :class="['relative z-10 grid size-7 place-items-center rounded-full border-2 transition-all',selectedTask.stage===stage?'scale-110 border-moss bg-moss text-white':reachedAt(selectedTask,stage)?'border-moss bg-moss-soft text-moss':'border-line bg-white text-muted']"><CheckCircle v-if="reachedAt(selectedTask,stage)" :size="15"/><Circle v-else :size="12"/></div><span class="mt-2 text-[11px] font-extrabold capitalize">{{ stage }}</span><span class="mt-0.5 text-[10px] text-muted">{{ fmt(reachedAt(selectedTask,stage)) }}</span></div></div></section>

        <div class="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
          <div class="space-y-5">
            <section class="panel p-5"><div class="mb-4 flex items-center justify-between"><div><h2 class="font-extrabold">Deterministic checks</h2><p class="mt-0.5 text-xs text-muted">Activate a chip to inspect its run evidence.</p></div><span class="text-sm font-black">{{ passCount(selectedTask) }} / 9</span></div><div class="flex flex-wrap gap-2"><button v-for="check in CHECKS" :key="check" :class="['check-pill',checkClass(selectedTask.checkResults[check].status)]" @click="checkClicked(selectedTask,check)">{{ check }} · {{ selectedTask.checkResults[check].status }}</button></div><Transition name="fade"><div v-if="activeViolation" class="mt-4 rounded-xl border border-[#efc0b4] bg-[#fff3ef] p-3 text-sm"><strong>{{ activeViolation.check }}</strong><p class="mt-1 text-[#87392c]">{{ activeViolation.text }}</p></div></Transition></section>

            <section class="panel p-5"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-extrabold">Check runner</h2><p class="mt-0.5 text-xs text-muted">Fixed order, deterministic outcomes, transient retries.</p></div><div class="flex gap-4 text-xs"><span><strong>{{ runCounts.done }}</strong> / 9 complete</span><span><strong>{{ runCounts.failed }}</strong> failed</span><span><strong>{{ elapsed }}s</strong> elapsed</span></div></div><NProgress v-if="activeRun" class="mb-4" type="line" :percentage="Math.round(runCounts.done/9*100)" :show-indicator="false"/>
              <div v-if="activeRun" class="grid gap-2 sm:grid-cols-2"><div v-for="step in activeRun.steps" :key="step.check" :data-step="step.check" :class="['step-card',`status-${step.status}`,activeRun.highlighted===step.check&&'highlighted']"><div class="flex items-center gap-2"><component :is="currentStepIcon(step)" class="status-dot shrink-0" :size="18"/><strong class="min-w-0 flex-1 break-all text-xs">{{ step.check }}</strong><span class="text-[10px] font-black uppercase">{{ step.status }}</span></div><p v-if="step.status==='retrying'" class="mt-2 text-xs">Waiting {{ step.backoff }} before retry {{ step.attempt+1 }} of 3</p><p v-if="step.violation" class="mt-2 text-xs leading-4">{{ step.violation }}</p><p v-if="step.completedAt" class="mt-1 text-[10px] text-muted">{{ fmt(step.completedAt) }} · attempt {{ step.attempt }}</p></div></div>
              <div v-else class="rounded-xl border border-dashed border-line p-8 text-center"><Play class="mx-auto mb-2 text-muted" :size="28"/><p class="font-bold">No session run yet</p><p class="mt-1 text-xs text-muted">Run checks to see all nine steps and their evidence.</p></div>
              <div v-if="activeRun" class="mt-5 border-t border-line pt-4"><div class="mb-3 flex flex-wrap items-center justify-between gap-2"><h3 class="text-sm font-extrabold">Run evidence log</h3><NSelect v-model:value="evidenceFilter" size="small" class="w-[150px]" :options="opt(['all','running','retrying','complete','failed'])"/></div><div class="max-h-[220px] space-y-1 overflow-y-auto"><button v-for="entry in filteredEvidence" :key="entry.id" class="row-hover flex w-full items-start gap-3 rounded-lg p-2 text-left text-xs" @click="chooseEvidence(entry)"><Clock class="mt-0.5 shrink-0"/><span class="flex-1">{{ entry.detail }}</span><span class="shrink-0 text-[10px] text-muted">{{ fmt(entry.at) }}</span></button></div></div>
            </section>

            <section class="panel p-5"><div class="mb-3 flex items-center justify-between"><div><h2 class="font-extrabold">Admission rubric</h2><p class="mt-0.5 text-xs text-muted">Ten operator judgments with saved rationale evidence.</p></div><span class="text-sm font-black">{{ criteriaCount(selectedTask) }} / 10</span></div><div v-if="!selectedTask.firstRunCompleted" class="mb-3 rounded-xl bg-[#eef2ec] p-3 text-sm font-bold text-muted">Checks must run first. Verdict toggles are disabled until a completed run.</div><div :class="['mb-3 rounded-xl p-3 text-sm font-extrabold',failedCriteria(selectedTask).length?'bg-[#fff1d5] text-[#795817]':passCount(selectedTask)===9&&criteriaCount(selectedTask)===10?'bg-[#e5f3e7] text-[#2e6737]':'bg-[#eef2ec] text-muted']">{{ admissionText(selectedTask) }}</div><CriterionRow v-for="criterion in CRITERIA" :key="criterion" :task="selectedTask" :criterion="criterion"/></section>
          </div>

          <div class="space-y-5">
            <EscalationForms :task="selectedTask"/>
            <section class="panel p-5"><div class="mb-4 flex items-center gap-2"><ChatCircleText class="text-moss"/><div><h2 class="font-extrabold">Feedback thread</h2><p class="text-xs text-muted">{{ selectedTask.feedback.length }} timestamped entries</p></div></div><div class="mb-5 max-h-[420px] space-y-3 overflow-y-auto pr-1"><div v-for="entry in [...selectedTask.feedback].reverse()" :key="entry.at+entry.reviewer" class="rounded-xl border border-line p-3"><div class="flex flex-wrap items-center gap-2"><strong class="text-sm">{{ entry.reviewer }}</strong><span :class="['stage-badge',verdictClass(entry.verdict)]">{{ entry.verdict }}</span><time class="ml-auto text-[10px] text-muted">{{ fmt(entry.at) }}</time></div><p class="mt-2 text-sm leading-5">{{ entry.findings }}</p></div><div v-if="!selectedTask.feedback.length" class="rounded-xl border border-dashed border-line p-5 text-center text-sm text-muted">Feedback entries will appear here.</div></div><div class="border-t border-line pt-4"><h3 class="mb-3 text-sm font-extrabold">Add feedback entry</h3><FeedbackForm :task="selectedTask"/></div></section>

            <section class="panel p-5"><div class="mb-4 flex items-center gap-2"><Clock class="text-moss"/><div><h2 class="font-extrabold">Audit timeline</h2><p class="text-xs text-muted">All session and lifecycle events in order.</p></div></div><ol class="space-y-1"><li v-for="item in [...selectedTask.timeline].reverse()" :key="item.id" class="row-hover relative rounded-lg py-2 pl-7 pr-2 text-xs before:absolute before:left-[10px] before:top-[13px] before:size-2 before:rounded-full before:bg-moss"><div class="font-extrabold">{{ title(item.type) }}</div><p class="mt-0.5 leading-4 text-muted">{{ item.detail }}</p><time class="mt-1 block text-[10px] text-muted">{{ fmt(item.at) }}</time></li></ol></section>
          </div>
        </div>
      </section>

      <section v-else-if="activeView==='reviewers'" key="reviewers" class="mx-auto max-w-[1120px]"><header class="mb-6"><p class="eyebrow">Feedback coverage</p><h1 class="mt-1 text-3xl font-black">Reviewers</h1><p class="mt-1 text-sm text-muted">Activity from the nine seeded benchmark reviewers.</p></header><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><button v-for="r in reviewerActivity" :key="r.reviewer" class="panel row-hover p-5 text-left" @click="store.openReviewer(r.reviewer)"><div class="mb-4 flex items-center justify-between"><div class="grid size-10 place-items-center rounded-full bg-moss-soft font-black text-moss">{{ r.reviewer.split(' ').map(x=>x[0]).join('') }}</div><span class="text-2xl font-black">{{ r.entryCount }}</span></div><h2 class="font-extrabold">{{ r.reviewer }}</h2><p class="mt-1 text-xs text-muted">{{ r.entryCount }} feedback entries · {{ r.verdictMix.Approve }} approvals</p></button></div></section>

      <section v-else-if="activeView==='reviewer-detail'&&selectedReviewer" key="reviewer-detail" class="mx-auto max-w-[1050px]"><button class="mb-5 flex items-center gap-2 text-sm font-extrabold text-moss" @click="store.setView('reviewers')"><ArrowLeft/>Back to reviewers</button><header class="mb-6"><p class="eyebrow">Reviewer activity</p><h1 class="mt-1 text-3xl font-black">{{ selectedReviewer }}</h1><p class="mt-1 text-sm text-muted">{{ reviewerEntries.length }} feedback entries across the audit queue.</p></header><div class="grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><section class="panel p-5"><h2 class="mb-2 font-extrabold">Verdict distribution</h2><VChart class="h-[320px]" :option="reviewerChartOption" autoresize/></section><section class="panel p-5"><h2 class="mb-4 font-extrabold">Feedback entries</h2><div class="space-y-3"><button v-for="entry in reviewerEntries" :key="entry.slug+entry.at" class="row-hover w-full rounded-xl border border-line p-4 text-left" @click="store.openTask(entry.slug)"><div class="flex flex-wrap items-center gap-2"><span class="break-all font-mono text-xs font-bold">{{ entry.slug }}</span><span :class="['stage-badge',verdictClass(entry.verdict)]">{{ entry.verdict }}</span><time class="ml-auto text-[10px] text-muted">{{ fmt(entry.at) }}</time></div><p class="mt-2 text-sm">{{ entry.findings }}</p></button></div></section></div></section>

      <section v-else-if="activeView==='report'" key="report" class="mx-auto max-w-[1380px]"><header class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow">Portable session artifact</p><h1 class="mt-1 text-3xl font-black">Audit report</h1><p class="mt-1 text-sm text-muted">Compiled live from {{ touchedRecords.length }} session-touched tasks.</p></div><div class="flex flex-wrap gap-2"><NButton @click="store.importOpen=true"><UploadSimple/>Import package</NButton><NButton @click="copyExport"><Copy/>Copy export</NButton><NButton type="primary" @click="downloadExport"><DownloadSimple/>Download export</NButton></div></header>
        <div class="mb-5 grid gap-3 sm:grid-cols-5"><div v-for="(value,key) in datasetSummary" :key="key" class="panel p-4"><span class="eyebrow">{{ key }}</span><strong class="mt-1 block text-2xl">{{ value }}</strong></div></div>
        <div class="grid gap-5 xl:grid-cols-[1fr_300px]"><section class="panel overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-line p-4"><div><h2 class="font-extrabold">Live export preview</h2><p class="mt-0.5 text-xs text-muted">Field names and enum values match the API-shaped contract.</p></div><NRadioGroup v-model:value="store.exportFormat" size="small"><NRadioButton value="json">Audit Package JSON</NRadioButton><NRadioButton value="markdown">Audit Report Markdown</NRadioButton></NRadioGroup></div><div class="p-3"><pre class="mono-preview" tabindex="0">{{ reportPreview }}</pre></div></section><aside class="space-y-5"><section class="panel p-5"><div class="mb-3 flex items-center gap-2"><Sparkle class="text-moss"/><h2 class="font-extrabold">Package contract</h2></div><p class="text-xs leading-5 text-muted">Exports use <strong>quality-audit-package-v1</strong>, a UTC timestamp, complete rollups, request-body-shaped evidence, and a session task appendix.</p></section><section class="panel p-5"><h2 class="mb-3 font-extrabold">Export history</h2><div v-if="store.exportHistory.length" class="space-y-2"><div v-for="item in [...store.exportHistory].reverse()" :key="item.exportedAt+item.format" class="rounded-lg bg-[#f3f5f0] p-3"><div class="text-xs font-extrabold uppercase">{{ item.format }}</div><time class="text-[10px] text-muted">{{ fmt(item.exportedAt) }}</time></div></div><p v-else class="text-xs leading-5 text-muted">Copy or download an export to add a timestamped history entry.</p></section></aside></div>
      </section>
      </Transition>
    </main>

    <Transition name="fade"><div v-if="store.batch.active" class="fixed bottom-4 left-4 right-4 z-40 rounded-2xl border border-line bg-white p-4 shadow-2xl sm:left-auto sm:w-[430px]"><div class="mb-3 flex items-start justify-between"><div><p class="eyebrow">Batch run</p><h3 class="font-black">Task {{ store.batch.index+1 }} of {{ store.batch.slugs.length }}</h3><p class="mt-0.5 max-w-[310px] truncate text-xs text-muted">{{ store.batch.slugs[store.batch.index] }}</p></div><NButton v-if="!store.batch.paused" size="small" @click="store.pauseBatch"><Pause/>Pause</NButton><NButton v-else size="small" type="primary" @click="store.resumeBatch"><Play/>Resume</NButton></div><div class="grid grid-cols-9 gap-1"><div v-for="step in currentBatchRun?.steps" :key="step.check" :title="`${step.check}: ${step.status}`" :class="['h-2 rounded-full',step.status==='complete'?'bg-[#5c8a63]':step.status==='failed'?'bg-[#c85b47]':step.status==='running'?'animate-pulse bg-blue':step.status==='retrying'?'bg-sun':'bg-[#e0e3dc]']"></div></div></div></Transition>
    <Transition name="toast"><div v-if="store.toast" role="status" class="fixed right-4 top-4 z-[70] flex max-w-[360px] items-center gap-2 rounded-xl bg-[#253128] px-4 py-3 text-sm font-bold text-white shadow-xl"><CheckCircle :size="19"/>{{ store.toast }}</div></Transition>
    <div class="sr-only" aria-live="polite">{{ store.liveMessage }}</div>
    <ImportModal/>
  </div>
</NConfigProvider>
</template>
