import { test } from '@playwright/test'
import { criterionProbe } from './helpers'

test.describe('core_features rubric', () => {
  test('1.1 seeded_library_entries', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'seeded_library_entries'))
  test('1.2 new_script_modal_gating', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'new_script_modal_gating'))
  test('1.3 invalid_url_validation', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'invalid_url_validation'))
  test('1.4 library_bulk_operations', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'library_bulk_operations'))
  test('1.5 script_delete_cascades', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'script_delete_cascades'))
  test('1.6 palette_opens_and_filters', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'palette_opens_and_filters'))
  test('1.7 palette_keyboard_activation', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'palette_keyboard_activation'))
  test('1.8 numbered_step_list_inline_fields', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'numbered_step_list_inline_fields'))
  test('1.9 type_specific_fields_only', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'type_specific_fields_only'))
  test('1.10 step_param_validation_markers', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'step_param_validation_markers'))
  test('1.11 add_reorder_delete_steps', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'add_reorder_delete_steps'))
  test('1.12 bulk_step_operations', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'bulk_step_operations'))
  test('1.13 unsaved_marker_and_save_version', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'unsaved_marker_and_save_version'))
  test('1.14 versions_panel_lists_history', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'versions_panel_lists_history'))
  test('1.15 version_preview_and_restore', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'version_preview_and_restore'))
  test('1.16 run_highlights_and_badges', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'run_highlights_and_badges'))
  test('1.17 terminal_console_lines', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'terminal_console_lines'))
  test('1.18 console_theme_selector', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'console_theme_selector'))
  test('1.19 console_follow_and_smooth_scroll', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'console_follow_and_smooth_scroll'))
  test('1.20 retry_backoff_and_resume', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'retry_backoff_and_resume'))
  test('1.21 pause_resume_checkpoint', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'pause_resume_checkpoint'))
  test('1.22 run_rollup_live', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'run_rollup_live'))
  test('1.23 event_timeline_filter_highlight', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'event_timeline_filter_highlight'))
  test('1.24 extracted_values_table_fills', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'extracted_values_table_fills'))
  test('1.25 screenshot_placeholder_modal', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'screenshot_placeholder_modal'))
  test('1.26 playground_matching_and_count', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'playground_matching_and_count'))
  test('1.27 playground_error_states', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'playground_error_states'))
  test('1.28 send_selector_to_step', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'send_selector_to_step'))
  test('1.29 runs_view_seeded_and_detail', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'runs_view_seeded_and_detail'))
  test('1.30 diff_view_three_treatments', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'diff_view_three_treatments'))
  test('1.31 self_compare_no_differences', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'self_compare_no_differences'))
  test('1.32 schedule_toggle_and_badge', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'schedule_toggle_and_badge'))
  test('1.33 scheduled_queue_and_trigger', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'scheduled_queue_and_trigger'))
  test('1.34 schedule_form_validation', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'schedule_form_validation'))
  test('1.35 undo_redo_controls', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'undo_redo_controls'))
  test('1.36 undo_restores_complete_state', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'undo_restores_complete_state'))
  test('1.37 history_timeline_rollback', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'history_timeline_rollback'))
  test('1.38 export_api_shaped_tabs', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'export_api_shaped_tabs'))
  test('1.39 export_recompiles_live', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'export_recompiles_live'))
  test('1.40 copy_export_confirmation', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'copy_export_confirmation'))
  test('1.41 report_totals_match_everywhere', async ({ page }, testInfo) => criterionProbe(page, testInfo, 'report_totals_match_everywhere'))
})

