import { expect, test } from '@playwright/test'
import {
  addFinding, boot, exportJson, exportText, moveEmptySubmissionToReview, openExport,
  openSubmission, overrideFirstFinding, queueRow, queueRows, requestRevision,
  selectQueueRows, submissionFromPackage, titles,
} from './helpers.js'

test('1.1 seeded_queue_walkthrough', async ({ page }) => {
  await boot(page)
  await expect(queueRows(page)).toHaveCount(12)
  for (const heading of ['Submission', 'Contributor', 'Stage', 'Payout']) await expect(page.getByRole('columnheader', { name: heading, exact: true })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /Findings/ })).toBeVisible()
  const text = await page.locator('.queue-table').innerText()
  for (const value of ['submitted', 'in review', 'needs revision', 'approved', 'pending', 'held', 'released']) expect(text.toLowerCase()).toContain(value)
  for (const contributor of ['Mara Voss', 'Ilya Brandt', 'Tessa Okafor', 'Ruben Calla']) expect(text).toContain(contributor)
})

test('1.2 tier_chips_summarize_findings', async ({ page }) => {
  await boot(page)
  await expect(queueRow(page, titles.blocker)).toContainText(/blocker.*minor/i)
  await expect(queueRow(page, titles.empty)).toContainText(/Zero open/i)
})

test('1.3 filters_combine_and_clear', async ({ page }) => {
  await boot(page)
  const baseline = await queueRows(page).count()
  await page.getByLabel('Filter by stage').selectOption('approved')
  await page.getByLabel('Filter by contributor').selectOption('Mara Voss')
  await expect(queueRows(page)).toHaveCount(1)
  await page.getByLabel('Filter by finding tier').selectOption('blocker')
  await expect(page.getByRole('heading', { name: 'No submissions match' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear all filters' }).click()
  await expect(queueRows(page)).toHaveCount(baseline)
})

test('1.4 sort_by_finding_count_reverses', async ({ page }) => {
  await boot(page)
  const order = async () => queueRows(page).evaluateAll((rows) => rows.map((row) => row.getAttribute('aria-label')))
  await page.getByLabel('Sort by open finding count').selectOption('asc')
  const ascending = await order()
  await page.getByLabel('Sort by open finding count').selectOption('desc')
  const descending = await order()
  expect(descending).toEqual([...ascending].reverse())
})

test('1.5 detail_view_anatomy', async ({ page }) => {
  await boot(page)
  await openSubmission(page, titles.blocker)
  await expect(page.locator('.detail-meta')).toContainText(/Ilya Brandt.*in review.*pending/i)
  const card = page.locator('.finding-card').first()
  await expect(card).toContainText(/blocker.*correctness.*Reference answer contradicts/i)
  const disclosure = card.getByRole('button', { name: /Evidence/ })
  await expect(disclosure).toHaveAttribute('aria-expanded', 'false')
  await disclosure.click()
  await expect(disclosure).toHaveAttribute('aria-expanded', 'true')
  await expect(card).toContainText('Trial 07 cites sector C')
})

test('1.6 gate_banner_derives_live', async ({ page }) => {
  await boot(page)
  await moveEmptySubmissionToReview(page)
  await expect(page.getByRole('heading', { name: 'Gate passed' })).toBeVisible()
  await addFinding(page)
  await expect(page.getByRole('heading', { name: 'Gate failed' })).toBeVisible()
  await overrideFirstFinding(page)
  await expect(page.getByRole('heading', { name: 'Gate passed' })).toBeVisible()
})

test('1.7 add_finding_validated_count_delta', async ({ page }) => {
  await boot(page)
  await openSubmission(page, titles.empty)
  await page.getByRole('button', { name: 'Add finding' }).first().click()
  const dialog = page.getByRole('dialog', { name: 'Add finding' })
  await expect(dialog.getByText('Tier is required.')).toBeVisible()
  await expect(dialog.getByText('Category is required.')).toBeVisible()
  await expect(dialog.getByText('Description must be at least 10 characters.')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Add finding' })).toBeDisabled()
  await dialog.getByLabel('Tier').selectOption('major')
  await dialog.getByLabel('Category').selectOption('tooling')
  await dialog.getByLabel('Description').fill('A precise regression description')
  await dialog.getByLabel('Evidence').fill('Evidence text')
  await dialog.getByRole('button', { name: 'Add finding' }).click()
  await expect(page.locator('.finding-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Back to queue' }).click()
  await expect(queueRow(page, titles.empty)).toContainText(/1\s*major/i)
})

test('1.8 revision_loop_stage_round_trip', async ({ page }) => {
  await boot(page)
  await openSubmission(page, titles.major)
  await page.getByRole('button', { name: 'Request revision' }).click()
  const dialog = page.getByRole('dialog', { name: 'Request revision' })
  await dialog.getByLabel('Summary').fill('too short')
  await expect(dialog.getByText('Summary must be at least 20 characters.')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Request revision' })).toBeDisabled()
  await dialog.getByLabel('Summary').fill('Please repair the recovery confirmation step.')
  await dialog.getByRole('button', { name: 'Request revision' }).click()
  await expect(page.locator('.detail-meta')).toContainText('needs revision')
  await page.getByRole('button', { name: 'Mark revised' }).click()
  await expect(page.locator('.detail-meta')).toContainText('in review')
})

test('1.9 approve_gating_and_effect', async ({ page }) => {
  await boot(page)
  await openSubmission(page, titles.blocker)
  await expect(page.getByRole('button', { name: 'Approve' })).toBeDisabled()
  await expect(page.getByRole('status').filter({ hasText: /open blocker finding/ })).toBeVisible()
  await overrideFirstFinding(page)
  await page.getByRole('button', { name: 'Approve' }).click()
  await page.getByRole('dialog', { name: 'Approve submission' }).getByRole('button', { name: 'Confirm approval' }).click()
  await expect(page.locator('.detail-meta')).toContainText(/approved.*released/i)
})

test('1.10 override_flow_gate_flip', async ({ page }) => {
  await boot(page)
  await openSubmission(page, titles.revision)
  await page.getByRole('button', { name: 'Override' }).click()
  const dialog = page.getByRole('dialog', { name: 'Override finding' })
  await dialog.getByLabel('Justification').fill('short')
  await expect(dialog.getByText('Justification must be at least 10 characters.')).toBeVisible()
  await dialog.getByLabel('Justification').fill('This exception is documented and approved.')
  await dialog.getByRole('button', { name: 'Confirm override' }).click()
  await expect(page.locator('.finding-card.overridden')).toContainText(/Overridden.*Override justification/i)
  await expect(page.getByRole('heading', { name: 'Gate passed' })).toBeVisible()
})

test('1.11 failure_profile_anatomy', async ({ page }) => {
  await boot(page)
  await openSubmission(page, titles.blocker)
  const rows = page.locator('.profile-row')
  await expect(rows).toHaveCount(5)
  await expect(page.locator('.trial-badge')).toContainText('10 trials')
  const rates = await rows.locator('.profile-label strong').allTextContents()
  expect(rates.every((rate) => /%$/.test(rate))).toBe(true)
  await expect(rows.first()).toContainText(/Mean score/)
})

test('1.12 date_range_recomputes_profile', async ({ page }) => {
  await boot(page)
  await openSubmission(page, titles.blocker)
  const snapshot = () => page.locator('.profile-row').allTextContents()
  const all = await snapshot()
  await page.getByRole('button', { name: 'Early' }).click()
  const early = await snapshot()
  expect(early).not.toEqual(all)
  await page.getByRole('button', { name: 'All' }).click()
  expect(await snapshot()).toEqual(all)
})

test('1.13 contributor_drawer_timeline', async ({ page }) => {
  await boot(page)
  const opener = page.getByRole('button', { name: 'Mara Voss' }).first()
  await opener.click()
  const drawer = page.getByRole('dialog')
  await expect(drawer).toContainText(/Submissions.*Stage history.*Newest first/i)
  await drawer.getByRole('button', { name: 'Close contributor drawer' }).click()
  await expect(drawer).toBeHidden()
})

test('1.14 recheck_progress_list', async ({ page }) => {
  test.setTimeout(10_000)
  await boot(page)
  await openSubmission(page, titles.blocker)
  await page.getByRole('button', { name: 'Run re-check' }).click()
  await expect(page.locator('.recheck-steps li')).toHaveCount(4)
  await expect(page.getByRole('button', { name: /Running/ })).toBeVisible()
  await expect(page.getByText(/Re-check complete/)).toBeVisible({ timeout: 5_000 })
  await expect(page.locator('.recheck-steps li.complete')).toHaveCount(4)
})

test('1.15 bulk_queue_actions', async ({ page }) => {
  await boot(page)
  await selectQueueRows(page, [titles.empty, titles.blocker])
  await expect(page.getByRole('form', { name: 'Bulk submission actions' })).toContainText('2 selected')
  await page.getByRole('button', { name: 'Hold payout' }).click()
  await expect(queueRow(page, titles.empty)).toContainText('held')
  await expect(queueRow(page, titles.blocker)).toContainText('held')
  await page.getByRole('button', { name: 'Clear selection' }).click()
  await expect(page.getByRole('form', { name: 'Bulk submission actions' })).toBeHidden()
})

test('1.16 command_palette_navigation', async ({ page }) => {
  await boot(page)
  await page.keyboard.press('Control+k')
  const palette = page.getByRole('dialog', { name: 'Command palette' })
  await expect(palette.getByRole('searchbox', { name: 'Search commands' })).toBeFocused()
  await palette.getByRole('searchbox').fill('evidence reconciliation')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: titles.blocker })).toBeVisible()
  await page.keyboard.press('Control+k')
  await palette.getByRole('searchbox').fill('zzzz-no-result')
  await expect(palette).toContainText('No commands found')
  await page.keyboard.press('Escape')
  await expect(palette).toBeHidden()
})

test('1.17 undo_redo_restores_mutations', async ({ page }) => {
  await boot(page)
  await openSubmission(page, titles.empty)
  await addFinding(page, { tier: 'minor', category: 'tooling' })
  await expect(page.locator('.finding-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Undo last action' }).click()
  await expect(page.locator('.finding-card')).toHaveCount(0)
  await page.getByRole('button', { name: 'Redo last action' }).click()
  await expect(page.locator('.finding-card')).toHaveCount(1)
})

test('1.18 qc_package_export_live', async ({ page }) => {
  await boot(page)
  await openExport(page)
  const json = await exportJson(page)
  expect(json).toMatchObject({ schemaVersion: 1, queue_summary: { total: 12 } })
  expect(json.submissions[0]).toEqual(expect.objectContaining({ id: expect.any(String), title: expect.any(String), contributor_name: expect.any(String), findings: expect.any(Array), history: expect.any(Array) }))
  await page.getByRole('button', { name: /QC report/ }).click()
  await expect(page.locator('.code-window pre')).toContainText('# Arcfield quality-control report')
  const preview = await exportText(page)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Download/ }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('arcfield-qc-report.md')
  expect(await download.createReadStream().then(async (stream) => { let value = ''; for await (const chunk of stream) value += chunk; return value })).toBe(preview)
})

test('1.19 undo_redo_keyboard_shortcuts', async ({ page }) => {
  await boot(page)
  await openSubmission(page, titles.empty)
  await addFinding(page)
  await page.keyboard.press('Control+z')
  await expect(page.locator('.finding-card')).toHaveCount(0)
  await page.keyboard.press('Control+Shift+z')
  await expect(page.locator('.finding-card')).toHaveCount(1)
})

test('1.20 qc_package_schema_header_and_summary_counts', async ({ page }) => {
  await boot(page)
  await openExport(page)
  const pkg = await exportJson(page)
  expect(pkg.schemaVersion).toBe(1)
  expect(pkg.exported_at).toMatch(/^\d{4}-\d\d-\d\dT.*Z$/)
  expect(Object.values(pkg.queue_summary.stages).reduce((a, b) => a + b, 0)).toBe(pkg.queue_summary.total)
  expect(Object.values(pkg.queue_summary.payout_states).reduce((a, b) => a + b, 0)).toBe(pkg.queue_summary.total)
  const blocker = submissionFromPackage(pkg, titles.blocker)
  expect(blocker).toMatchObject({ gate_status: 'failed', open_finding_counts: { blocker: 1, major: 0, minor: 1 } })
})
