/* NOT-AUTOMATABLE: none; all behavioral relationships are state-delta assertions. */
import{assertClean,cards,cells,chooseTag,expect,gallery,importText,load,openExport,paint,remove,removeAll,save,session,stats,test}from'./helpers.js'
test.beforeEach(async({page})=>load(page));test.afterEach(async({page})=>assertClean(page))
test('14.1 in_memory_multi_facet_reload_reset',async({page})=>{await page.getByRole('button',{name:'Color Brush'}).click();await page.getByRole('button',{name:/red palette/}).click();await paint(page,[0,1,2]);await save(page,'Transient','Temp');await page.reload();expect((await stats(page)).painted).toBe(0);await expect(page.getByRole('slider',{name:'Cell size'})).toBeEnabled();await gallery(page);await expect(cards(page)).toHaveCount(4)})
test('14.2 tag_filter_then_clear_restores_list',async({page})=>{await gallery(page);const names=await cards(page).getByRole('heading').allTextContents();await chooseTag(page,'Festival');expect(await cards(page).count()).toBeLessThan(names.length);await chooseTag(page,'All tags');expect(await cards(page).getByRole('heading').allTextContents()).toEqual(names)})
test('14.3 gallery_list_responds_to_tag_filter',async({page})=>{await gallery(page);const n=await cards(page).count();await chooseTag(page,'Poster');await expect(cards(page)).toHaveCount(1);await expect(cards(page).first()).toContainText('Poster');await chooseTag(page,'All tags');await expect(cards(page)).toHaveCount(n)})
test('14.4 paint_save_echo_across_modes',async({page})=>{await page.getByRole('button',{name:'Color Brush'}).click();await paint(page,[210,211,212]);await save(page,'Echo Pattern','Echo');await expect(cards(page).filter({hasText:'Echo Pattern'}).locator('canvas')).toBeVisible();await page.getByRole('button',{name:'Paint',exact:true}).click();expect((await stats(page)).painted).toBe(3);await gallery(page);await expect(page.getByText('Echo Pattern',{exact:true})).toBeVisible()})
test('14.5 gallery_count_delta_exact',async({page})=>{await gallery(page);const n=await cards(page).count();await save(page,'Delta','Count');await expect(cards(page)).toHaveCount(n+1);await remove(page,'Delta');await expect(cards(page)).toHaveCount(n)})
test('14.6 different_paints_save_different_thumbnails',async({page})=>{await page.getByRole('button',{name:'Color Brush'}).click();await page.getByRole('button',{name:/red palette/}).click();await paint(page,[0]);await save(page,'Red Pattern','Diff');await page.getByRole('button',{name:'Paint',exact:true}).click();await page.getByRole('button',{name:/blue palette/}).click();await paint(page,[50]);await save(page,'Blue Pattern','Diff');const hashes=await cards(page).filter({hasText:/Pattern/}).locator('canvas').evaluateAll(cs=>cs.map(c=>c.toDataURL()));expect(new Set(hashes).size).toBe(2)})
test('14.7 interleaved_paint_and_gallery',async({page})=>{await paint(page,[0]);await gallery(page);const fav=cards(page).first().getByRole('button',{name:/favorites/});await fav.click();const state=await fav.getAttribute('aria-pressed');await page.getByRole('button',{name:'Paint',exact:true}).click();await paint(page,[1]);expect((await stats(page)).painted).toBe(2);await gallery(page);await expect(cards(page).first().getByRole('button',{name:/favorites/})).toHaveAttribute('aria-pressed',state)})
test('14.8 empty_gallery_then_repopulate',async({page})=>{await removeAll(page);await expect(cards(page)).toHaveCount(0);await page.getByRole('button',{name:'Paint',exact:true}).click();await paint(page,[0]);await save(page,'Restart','New');await expect(cards(page)).toHaveCount(1);await expect(page.getByText('Restart',{exact:true})).toBeVisible()})
test('14.9 export_import_roundtrip_under_session_schema',async({page})=>{await page.getByRole('button',{name:'Color Brush'}).click();await page.getByRole('button',{name:/pink palette/}).click();await page.getByRole('button',{name:'Horizontal mirror'}).click();await paint(page,[0]);await save(page,'Round Trip','JSON');await page.getByRole('button',{name:'Paint',exact:true}).click();const before=await session(page);await page.keyboard.press('Escape');await page.waitForTimeout(180);await page.getByRole('button',{name:/Clear the board/}).click();await page.getByRole('button',{name:/Confirm clear/}).click();const d=await importText(page,JSON.stringify(before));await d.getByRole('button',{name:'Import session'}).click();await expect(d).toHaveCount(0);const after=await session(page);expect(after).toEqual(before)})
test('14.10 import_schema_rejection_preserves_studio',async({page})=>{await paint(page,[0]);await save(page,'Stable','Keep');await page.getByRole('button',{name:'Paint',exact:true}).click();const before=await stats(page);const d=await importText(page,'{"schemaVersion":"bad"}');await expect(d.getByRole('alert')).toContainText('schemaVersion');expect(await stats(page)).toEqual(before);await page.keyboard.press('Escape');await page.waitForTimeout(180);await gallery(page);await expect(page.getByText('Stable',{exact:true})).toBeVisible()})
test('14.11 mirror_and_fill_stats_cross_view',async({page})=>{await page.getByRole('button',{name:'Horizontal mirror'}).click();await paint(page,[0,1]);const s=await stats(page);expect(s.painted).toBe(4);const x=await session(page);expect(x.mirrorMode).toBe('horizontal');expect(x.fillStats).toEqual(s)})
