/* NOT-AUTOMATABLE: none; responsiveness is bounded by deterministic wall-clock limits and state deltas. */
import{assertClean,cards,cells,chooseTag,expect,gallery,load,openExport,paint,save,stats,test}from'./helpers.js'
test.beforeEach(async({page})=>load(page));test.afterEach(async({page})=>assertClean(page))
test('9.1 cold_start_under_two_seconds',async({page})=>{const t=Date.now();await page.reload();await expect(page.getByRole('grid')).toBeVisible();expect(Date.now()-t).toBeLessThan(2000)})
test('9.2 console_clean_during_studio_flows',async({page})=>{await paint(page,[0,1]);await save(page,'Perf Flow','Perf');await page.getByRole('button',{name:'Load Perf Flow'}).click();await gallery(page);await chooseTag(page,'Perf');await page.getByRole('button',{name:'Paint',exact:true}).click();await openExport(page)})
test('9.3 paint_strokes_respond_immediately',async({page})=>{await page.getByRole('button',{name:'Vertical mirror'}).click();const a=await cells(page).nth(0).boundingBox(),b=await cells(page).nth(10).boundingBox(),t=Date.now();await page.mouse.move(a.x+2,a.y+2);await page.mouse.down();await page.mouse.move(b.x+2,b.y+2,{steps:15});await page.mouse.up();expect(Date.now()-t).toBeLessThan(1200);expect((await stats(page)).painted).toBeGreaterThan(10)})
test('9.4 image_import_stays_responsive',async({page})=>{const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2n1cAAAAASUVORK5CYII=','base64'),t=Date.now();await page.locator('input[type=file][accept="image/*"]').setInputFiles({name:'x.png',mimeType:'image/png',buffer:png});await expect(page.getByRole('slider',{name:'Cell size'})).toBeDisabled();expect(Date.now()-t).toBeLessThan(2000);await expect(page.getByRole('button',{name:'Export',exact:true})).toBeEnabled()})
test('9.5 cell_rebuild_without_freeze',async({page})=>{const t=Date.now();await page.getByRole('slider',{name:'Cell size'}).press('End');expect(Date.now()-t).toBeLessThan(1000);await expect(page.getByRole('grid')).toBeVisible()})
test('9.6 mode_switch_stays_interactive',async({page})=>{const t=Date.now();for(let i=0;i<5;i++){await gallery(page);await page.getByRole('button',{name:'Paint',exact:true}).click()}expect(Date.now()-t).toBeLessThan(1500);await save(page,'Fast Save','Perf');await expect(cards(page).filter({hasText:'Fast Save'})).toBeVisible()})
test('9.7 rapid_drag_stays_smooth',async({page})=>{const boxes=await cells(page).evaluateAll(es=>es.slice(0,15).map(e=>{const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}}));await page.mouse.move(boxes[0].x,boxes[0].y);await page.mouse.down();for(const b of boxes)await page.mouse.move(b.x,b.y);await page.mouse.up();expect((await stats(page)).painted).toBeGreaterThanOrEqual(10)})
test('9.8 rapid_tool_and_undo_no_freeze',async({page})=>{const t=Date.now();for(let i=0;i<20;i++){await page.keyboard.press(['q','b','e'][i%3]);await page.keyboard.press(String(i%7+1))}await paint(page,[0]);await page.keyboard.press('Backspace');expect(Date.now()-t).toBeLessThan(1500);expect((await stats(page)).painted).toBe(0)})
test('9.9 extended_paint_session_stable',async({page})=>{const t=Date.now(),indexes=[...Array(4)].flatMap((_,r)=>[...Array(10)].map((_,c)=>210+r*20+c));await paint(page,indexes);expect((await stats(page)).painted).toBeGreaterThanOrEqual(40);expect(Date.now()-t).toBeLessThan(5000);await save(page,'Extended','Perf')})
test('9.10 camera_cancel_recovers_promptly',async({page})=>{const t=Date.now();await page.getByRole('button',{name:'Camera'}).click();await page.getByRole('dialog',{name:'Capture image'}).getByRole('button',{name:'Dismiss'}).click();await expect(page.getByRole('button',{name:'Color Brush'})).toBeEnabled();expect(Date.now()-t).toBeLessThan(1500)})
