/* NOT-AUTOMATABLE: none; 2.5 is covered through local data-URL generation and zero QR network requests. */
import{assertClean,cards,cells,expect,gallery,importText,invoke,load,paint,renameFirst,save,session,stats,test}from'./helpers.js'
test.beforeEach(async({page})=>load(page));test.afterEach(async({page})=>assertClean(page))
test('2.1 shared_state_coherence',async({page})=>{await save(page,'Shared Datum','Shared');const card=cards(page).filter({hasText:'Shared Datum'});await card.getByRole('button',{name:'Rename Shared Datum'}).click();const d=page.getByRole('dialog',{name:'Rename board'});await d.getByLabel('Name required · max 40').fill('Shared Renamed');await d.getByRole('button',{name:'Update board'}).click();await expect(page.getByText('Shared Renamed',{exact:true})).toBeVisible();await choose(page,'Shared');await expect(page.getByText('Shared Renamed',{exact:true})).toBeVisible()})
async function choose(page,tag){await page.getByRole('button',{name:'Filter boards by tag'}).click();await page.getByRole('option',{name:tag,exact:true}).click()}
test('2.2 reload_returns_seeded_baseline',async({page})=>{await paint(page,[0]);await save(page,'No Persist','Temp');await page.reload();expect((await stats(page)).painted).toBe(0);await gallery(page);await expect(cards(page)).toHaveCount(4)})
test('2.5 local_qrious_festival_mask',async({page})=>{const requests=[];page.on('request',r=>requests.push(r.url()));await paint(page,[0]);await expect(cells(page).first()).toHaveCSS('background-image',/data:image\/png/);expect(requests.filter(u=>/qr|shapeshiftfestival/i.test(u))).toEqual([])})
test('2.7 keyboard_operable_with_focus_ring',async({page})=>{const b=page.getByRole('button',{name:'QR Brush'});await b.focus();await expect(b).toBeFocused();const s=await b.evaluate(e=>getComputedStyle(e));expect(s.outlineStyle).not.toBe('none')})
test('2.8 camera_dialog_traps_focus',async({page})=>{const b=page.getByRole('button',{name:'Camera'});await b.click();const d=page.getByRole('dialog',{name:'Capture image'});expect(await d.locator(':focus').count()).toBe(1);await page.keyboard.press('Escape');await expect(d).toHaveCount(0);await expect(b).toBeFocused()})
test('2.9 swatches_expose_color_names',async({page})=>{for(const c of['white','black','red','yellow','green','blue','pink'])await expect(page.getByRole('button',{name:new RegExp(`^${c} palette`)})).toBeVisible()})
test('2.10 validation_message_announced',async({page})=>{await page.getByRole('button',{name:'Save current board'}).click();const n=page.getByLabel('Name required · max 40');await n.focus();await n.blur();await expect(page.getByRole('alert')).toHaveAttribute('aria-live','assertive')})
test('2.11 interactive_within_two_seconds',async({page})=>{const t=Date.now();await page.reload();await page.getByRole('button',{name:'Color Brush'}).click();await expect(page.getByRole('button',{name:'Color Brush'})).toHaveAttribute('aria-pressed','true');expect(Date.now()-t).toBeLessThan(2000)})
test('2.13 drag_painting_stays_smooth',async({page})=>{const start=Date.now(),a=await cells(page).nth(0).boundingBox(),b=await cells(page).nth(10).boundingBox();await page.mouse.move(a.x+2,a.y+2);await page.mouse.down();await page.mouse.move(b.x+2,b.y+2,{steps:12});await page.mouse.up();expect(Date.now()-start).toBeLessThan(1000);expect((await stats(page)).painted).toBeGreaterThan(5)})
test('2.15 form_and_export_share_board_session_schema',async({page})=>{await save(page,'Contract Board','Schema');await page.getByRole('button',{name:'Paint',exact:true}).click();const x=await session(page),b=x.boards.find(v=>v.name==='Contract Board');expect(Object.keys(b).sort()).toEqual(['cells','favorite','name','tag']);await page.keyboard.press('Escape');await page.waitForTimeout(180);const d=await importText(page,JSON.stringify({...x,brushMode:'invalid'}));await expect(d.getByRole('alert')).toContainText('brushMode')})
test('webmcp read and mutation tools synchronize tool state and DOM',async({page})=>{const info=await page.evaluate(()=>window.webmcp_session_info());expect(info.contractVersion).toBe('zto-webmcp-v1');const tools=await page.evaluate(()=>window.webmcp_list_tools());expect(tools.length).toBeGreaterThanOrEqual(10);await invoke(page,'editor_select',{row:0,col:0});await invoke(page,'editor_update_property',{property:'color',value:'red'});await expect(cells(page).first()).toHaveClass(/kind-color/);await expect(cells(page).first()).toHaveAttribute('aria-label',/red/);const preview=await invoke(page,'editor_preview',{});expect(preview).toBeTruthy();const x=JSON.parse(await page.getByLabel('Session JSON preview').innerText());expect(x.cells[0]).toMatchObject({kind:'color',color:'red'})})
test('webmcp entity mutation changes tool-readable state and gallery DOM',async({page})=>{await invoke(page,'entity_create',{entity:'board',name:'MCP Board',tag:'MCP',favorite:false});await expect(page.getByRole('heading',{name:'MCP Board'})).toBeVisible();const result=await invoke(page,'entity_toggle',{entity:'board',name:'MCP Board'});expect(result).toBeTruthy();await expect(cards(page).filter({hasText:'MCP Board'}).getByRole('button',{name:/favorites/})).toHaveAttribute('aria-pressed','true')})
