/* NOT-AUTOMATABLE: 15.5 broad spelling/grammar quality is an editorial judgment. */
import{assertClean,expect,importText,load,removeAll,save,test}from'./helpers.js'
test.beforeEach(async({page})=>load(page));test.afterEach(async({page})=>assertClean(page))
test('15.1 toolbar_gallery_capitalization_consistent',async({page})=>{for(const label of['QR Brush','Color Brush','Eraser','Grid On','Save board','Import','Export','Share PNG'])await expect(page.getByText(label,{exact:true}).first()).toBeVisible()})
test('15.2 actions_use_specific_labels',async({page})=>{for(const name of['Save current board','Clear the board','Turn grid overlay off','Export','Import'])await expect(page.getByRole('button',{name,exact:name==='Export'||name==='Import'})).toBeVisible();await expect(page.getByRole('button',{name:/^(Submit|OK)$/})).toHaveCount(0)})
test('15.3 validation_names_field_and_fix',async({page})=>{await page.getByRole('button',{name:'Save current board'}).click();const n=page.getByLabel('Name required · max 40');await n.fill('X'.repeat(41));await n.blur();await expect(page.getByRole('alert')).toContainText(/name.*40/i);await page.keyboard.press('Escape');await page.waitForTimeout(180);const d=await importText(page,'{"schemaVersion":"bad"}');await expect(d.getByRole('alert')).toContainText(/schemaVersion/)})
test('15.4 empty_gallery_copy_explains_next_step',async({page})=>{await removeAll(page);await expect(page.locator('.empty-gallery')).toContainText(/gallery is empty/i);await expect(page.locator('.empty-gallery')).toContainText(/Paint.*Save board/i)})
test('15.6 board_terminology_consistent',async({page})=>{await expect(page.getByRole('button',{name:'Save current board'})).toContainText('Save board');await page.getByRole('button',{name:/^Gallery/}).click();await expect(page.getByLabel('Saved boards gallery')).toContainText(/BOARD COLLECTION/);await expect(page.getByText(/project|document|item/i)).toHaveCount(0)})
test('15.7 export_footer_copy_consistent',async({page})=>{const footer=page.locator('.site-footer');await expect(footer).toContainText('/MADE WITH SHAPESHIFT GRID TOOL');await expect(footer).toContainText('<SHAPESHIFTFESTIVAL.COM>');await expect(page.getByRole('heading',{level:1})).toContainText(/SHAPESHIFT GRID\s*TOOL/)})
test('15.8 save_feedback_is_specific',async({page})=>{await save(page,'Feedback Board','Copy');await page.getByRole('button',{name:'Paint',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Saved “Feedback Board”'})).toBeVisible()})
