/* NOT-AUTOMATABLE: none; includes the required WebMCP contract round-trip. */
import { addNote, chainButton, closeDialog, exportPackage, gateRow, loadApp, openExport, stageButton, startRerun, test, expect } from './helpers'

test('5.1 interactive_within_two_seconds', async ({ page }) => { const start=Date.now(); await page.goto('/'); const run=page.getByRole('button',{name:'Open run RUN-2407-B04'}); await run.click(); await expect(run).toHaveAttribute('aria-pressed','true'); expect(Date.now()-start).toBeLessThan(2000) })

test('5.2 console_clean_full_exercise', async ({ page, diagnostics }) => { await loadApp(page); await page.getByRole('switch',{name:'What-if mode'}).check(); await page.getByRole('button',{name:/TST-328 Fail; flip/}).click(); await page.getByRole('button',{name:'Revert'}).click(); await addNote(page,'full-exercise-note'); await startRerun(page); await openExport(page); expect(diagnostics.errors).toEqual([]); expect(diagnostics.warnings).toEqual([]); expect(diagnostics.pageErrors).toEqual([]) })

test('5.3 reload_returns_seeded_state', async ({ page }) => { await loadApp(page); await addNote(page,'ephemeral'); await page.getByRole('switch',{name:'What-if mode'}).check(); await page.getByRole('button',{name:'Switch to dark theme'}).click(); await page.reload(); await expect(page.locator('html')).not.toHaveClass(/dark/); await expect(page.locator('.stage-foot')).toContainText('0 gate notes'); await expect(page.getByText('What-if simulation is active')).toHaveCount(0); expect(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length}))).toEqual({local:0,session:0}) })

test('5.4 cross_view_state_coherence', async ({ page }) => { await loadApp(page); await addNote(page,'coherence-note'); await expect(gateRow(page)).toContainText('coherence-note'); await expect(page.locator('.timeline-list')).toContainText('Note added to TST-328'); expect(JSON.stringify(await exportPackage(page))).toContain('coherence-note'); await closeDialog(page,'export'); await startRerun(page); await expect(stageButton(page,'Test Generation','passed')).toBeVisible(); await expect(chainButton(page,'Test Generation')).toBeEnabled(); await expect(page.locator('.suite-outcome')).toContainText('PASS') })

test('5.5 stable_under_rapid_input', async ({ page }) => { await loadApp(page); for(let i=0;i<8;i++) await page.locator('.run-card').nth(i%6).click(); await page.getByRole('button',{name:'Gate registry'}).click(); const filter=page.getByLabel('Severity filter'); for(const v of ['S1','S3','S2','all']) await filter.selectOption(v); await page.getByRole('button',{name:'Runs'}).click(); await page.getByRole('button',{name:'Start re-run'}).evaluate((b:HTMLButtonElement)=>{b.click();b.click()}); await expect(page.getByText(/re-run passed|re-run rejected/).last()).toBeVisible({timeout:10_000}); await expect(page.getByText(/re-run started/)).toHaveCount(1) })

test('5.6 whatif_excluded_from_export', async ({ page }) => { await loadApp(page); await page.getByRole('switch',{name:'What-if mode'}).check(); await page.getByRole('button',{name:/TST-328 Fail; flip/}).click(); await expect(page.getByRole('button',{name:/TST-328 Pass; flip/})).toBeVisible(); const payload=await exportPackage(page); expect(payload.stages[2].gates.find((g:{id:string})=>g.id==='TST-328').state).toBe('fail'); await closeDialog(page,'export'); await page.getByRole('button',{name:'Revert'}).click(); await expect(page.getByRole('button',{name:/TST-328 Fail$/})).toBeVisible() })

test('webmcp contract registers and mutates tool-readable and DOM state', async ({ page }) => { await loadApp(page); const session=await page.evaluate(()=>window.webmcp_session_info()); expect(session.contractVersion).toBe('zto-webmcp-v1'); const tools=await page.evaluate(()=>window.webmcp_list_tools()); expect(tools.length).toBeGreaterThanOrEqual(15); const result=await page.evaluate(()=>window.webmcp_invoke_tool('browse_apply_filter',{filter:'severity',value:'S1'})); expect(result).toMatchObject({ok:true,filter:'severity',value:'S1'}); await expect(page.getByRole('heading',{name:'Gate registry'})).toBeVisible(); await expect(page.getByLabel('Severity filter')).toHaveValue('S1'); const read=await page.evaluate(()=>window.webmcp_invoke_tool('browse_sort',{direction:'oldest'})); expect(read).toMatchObject({ok:true,direction:'oldest'}) })
