/* NOT-AUTOMATABLE: none; every flow has a deterministic UI round trip. */
import { addNote, chainButton, closeDialog, exportPackage, expandGate, gateRow, loadApp, openExport, openRegistry, stageButton, test, expect } from './helpers'

test.beforeEach(async ({ page }) => loadApp(page))

test('6.1 rejection_investigation_whatif_flow', async ({ page }) => { await expect(page.getByRole('alert')).toContainText('TST-328 · Fixture isolation'); await expandGate(page,'TST-328'); await page.getByRole('switch',{name:'What-if mode'}).check(); await page.getByRole('button',{name:/TST-328 Fail; flip/}).click(); await expect(page.locator('.suite-outcome')).toContainText('PASS'); await expect(page.locator('.stage-status')).toContainText('passed'); await page.getByRole('button',{name:'Revert'}).click(); await expect(page.locator('.suite-outcome')).toContainText('FAIL'); await expect(page.locator('.stage-status')).toContainText('rejected') })

test('6.2 invalid_note_shows_inline_validation', async ({ page }) => { await page.locator('[data-add-note="TST-328"]').click(); const d=page.getByRole('dialog',{name:'Add gate note'}); await expect(d.getByRole('button',{name:'Attach note'})).toBeDisabled(); await expect(d).toContainText('text must contain 1 to 200'); await expect(d).toContainText('category is required'); await d.getByLabel('Text Required').fill('x'.repeat(201)); await expect(d).toContainText('201/200'); await expect(d.getByRole('button',{name:'Attach note'})).toBeDisabled(); await page.keyboard.press('Escape'); await expect(page.locator('.stage-foot')).toContainText('0 gate notes') })

test('6.3 annotate_then_export_flow', async ({ page }) => { await addNote(page,'note-alpha-17','observation'); const p=await exportPackage(page); expect(p.schemaVersion).toBe('gate-console.acceptance-package.v1'); const note=p.stages.flatMap((s:{gates:any[]})=>s.gates).flatMap((g:{notes:any[]})=>g.notes).find((n:{text:string})=>n.text==='note-alpha-17'); expect(note).toMatchObject({text:'note-alpha-17',category:'observation'}) })

test('6.4 rerun_updates_strip_chain_timeline', async ({ page }) => { await page.getByRole('button',{name:'Start re-run'}).click(); await expect(page.locator('.rerun-progress')).toBeVisible(); await expect(page.locator('.gate-state').filter({hasText:'Running'}).first()).toBeVisible(); await expect(page.getByText(/re-run passed|re-run rejected/).last()).toBeVisible({timeout:10_000}); await expect(stageButton(page,'Test Generation','passed')).toBeVisible(); await expect(chainButton(page,'Test Generation')).toBeEnabled(); await expect(page.locator('.timeline-list')).toContainText('re-run started') })

test('6.5 registry_filter_and_selection_flow', async ({ page }) => { await openRegistry(page); const all=await page.locator('.registry-list > button').count(); await page.getByLabel('Severity filter').selectOption('S1'); const s1=page.locator('.registry-list > button'); expect(await s1.count()).toBeLessThan(all); await s1.first().click(); await expect(page.locator('.registry-detail h3')).toBeVisible(); expect(await page.locator('.stage-membership .included').count()).toBeGreaterThan(0); await page.getByRole('button',{name:'Clear filter'}).click(); await expect(page.locator('.registry-list > button')).toHaveCount(all) })

test('6.6 timeline_empty_state_for_filtered_type', async ({ page }) => { await page.getByLabel('Filter timeline by entry type').selectOption('note'); await expect(page.locator('.timeline-list')).toContainText(/No notes yet.*gate notes will appear here/s) })

test('6.7 severity_and_timeline_filters_agree', async ({ page }) => { const timelineAll=await page.locator('.timeline-entry').count(); await page.getByLabel('Filter timeline by entry type').selectOption('certificate'); const certs=await page.locator('.timeline-entry').count(); expect(certs).toBeLessThanOrEqual(timelineAll); await openRegistry(page); await page.getByLabel('Severity filter').selectOption('S1'); for(const chip of await page.locator('.registry-list .severity').all()) await expect(chip).toHaveText('S1'); await page.getByRole('button',{name:'Runs'}).click(); await expect(page.getByLabel('Filter timeline by entry type')).toHaveValue('certificate'); await page.getByLabel('Filter timeline by entry type').selectOption('all'); await expect(page.locator('.timeline-entry')).toHaveCount(timelineAll) })

test('6.8 export_drawer_preserves_run_selection', async ({ page }) => { const selected=page.getByRole('button',{name:'Open run RUN-2407-A91'}); await expect(selected).toHaveAttribute('aria-pressed','true'); await openExport(page); await page.keyboard.press('Escape'); await expect(selected).toHaveAttribute('aria-pressed','true'); await expect(page.locator('.run-detail-head')).toContainText('RUN-2407-A91') })

test('6.9 certificate_copy_and_export_overlays', async ({ page,context }) => { await context.grantPermissions(['clipboard-read','clipboard-write']); await stageButton(page,'Source','passed').click(); const certOpen=page.getByRole('button',{name:'View certificate'}); await certOpen.click(); await page.getByRole('button',{name:'Copy fingerprint'}).click(); await expect(page.getByRole('button',{name:'Copied'})).toBeVisible(); await page.keyboard.press('Escape'); await expect(certOpen).toBeFocused(); const exportOpen=page.getByRole('button',{name:'Export acceptance package'}).first(); await exportOpen.click(); await page.getByRole('dialog',{name:'Export acceptance package'}).getByRole('button',{name:'Copy'}).click(); await expect(page.getByRole('button',{name:'Copied'})).toBeVisible(); await page.keyboard.press('Escape'); await expect(exportOpen).toBeFocused() })

test('6.10 export_import_round_trip_flow', async ({ page }) => { await addNote(page,'flow-roundtrip'); const payload=await exportPackage(page); await closeDialog(page,'export'); await gateRow(page).getByRole('button',{name:/Remove note 1/}).click(); await page.getByRole('button',{name:'Import acceptance package'}).first().click(); const d=page.getByRole('dialog',{name:'Import acceptance package'}); await d.getByLabel('Acceptance Package JSON Required').fill(JSON.stringify(payload)); await d.getByRole('button',{name:'Import package'}).click(); await stageButton(page,'Test Generation','rejected').click(); await expandGate(page); await expect(gateRow(page)).toContainText('flow-roundtrip'); expect(JSON.stringify(await exportPackage(page))).toContain('flow-roundtrip') })

test('6.11 valid_import_reconstructs_every_run_surface', async ({ page }) => { const payload=await exportPackage(page); await closeDialog(page,'export'); payload.stages[0].gates[0].notes=[{text:'import-reconstruct',category:'follow-up'}]; payload.timeline.push({type:'note',timestamp:new Date().toISOString(),summary:'Imported reconstruction note'}); await page.getByRole('button',{name:'Import acceptance package'}).first().click(); const d=page.getByRole('dialog',{name:'Import acceptance package'}); await d.getByLabel('Acceptance Package JSON Required').fill(JSON.stringify(payload)); await d.getByRole('button',{name:'Import package'}).click(); await expect(page.getByRole('heading',{name:'Source'})).toBeVisible(); await expandGate(page,'SRC-101'); await expect(gateRow(page,'SRC-101')).toContainText('import-reconstruct'); await expect(page.locator('.timeline-list')).toContainText('Imported reconstruction note'); expect(JSON.stringify(await exportPackage(page))).toContain('import-reconstruct') })

test('6.12 certificate_markdown_contains_complete_chain', async ({ page }) => { const d=await openExport(page); await d.getByRole('tab',{name:'Certificate Chain Markdown'}).click(); const md=await d.getByLabel('markdown export preview').innerText(); expect(md).toContain('RUN-2407-A91'); for(const stage of ['Source','Build','Test Generation','Hardening','Publish']) expect(md).toContain(`### ${stage}`); expect(md).toMatch(/Fingerprint: `sha256:/); expect(md).toMatch(/- `SRC-101` · S1 · pass/) })

test('6.13 invalid_import_names_field_and_preserves_run', async ({ page }) => { const before=await page.locator('.stage-segment').evaluateAll(ns=>ns.map(n=>n.getAttribute('aria-label'))); await page.getByRole('button',{name:'Import acceptance package'}).first().click(); const d=page.getByRole('dialog',{name:'Import acceptance package'}); await d.getByLabel('Acceptance Package JSON Required').fill('{bad'); await expect(d.getByRole('alert')).toContainText('payload'); await d.getByLabel('Acceptance Package JSON Required').fill(JSON.stringify({schemaVersion:'wrong'})); await expect(d.getByRole('alert')).toContainText('schemaVersion'); await page.keyboard.press('Escape'); expect(await page.locator('.stage-segment').evaluateAll(ns=>ns.map(n=>n.getAttribute('aria-label')))).toEqual(before) })
