/* NOT-AUTOMATABLE: 15.5 body_copy_is_well_written — broad grammar/style quality requires editorial review. */
import { loadApp, test, expect } from './helpers'

test.beforeEach(async({page})=>loadApp(page))

test('15.1 headings_use_consistent_capitalization',async({page})=>{const hs=await page.locator('h1,h2,h3').allTextContents();for(const h of hs.map(s=>s.trim()).filter(Boolean))expect(h[0]).toBe(h[0].toUpperCase())})
test('15.2 actions_use_specific_labels',async({page})=>{for(const label of ['Add note','Start re-run','Export acceptance package','Import acceptance package'])await expect(page.getByRole('button',{name:label}).first()).toBeVisible();await expect(page.getByRole('button',{name:/^(Submit|OK)$/})).toHaveCount(0)})
test('15.3 errors_name_problem_and_fix',async({page})=>{await page.getByRole('button',{name:'Add note'}).first().click();const d=page.getByRole('dialog',{name:'Add gate note'});await expect(d).toContainText('text must contain 1 to 200 trimmed characters');await expect(d).toContainText('category is required and must match the allowed enum');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Import acceptance package'}).first().click();const importDialog=page.getByRole('dialog',{name:'Import acceptance package'});await page.getByLabel('Acceptance Package JSON Required').fill('{');await expect(importDialog.getByRole('alert')).toContainText('payload')})
test('15.4 empty_states_explain_next_step',async({page})=>{await page.getByLabel('Filter timeline by entry type').selectOption('note');await expect(page.locator('.timeline-list')).toContainText('gate notes will appear here');await page.getByRole('button',{name:'Open run RUN-2407-F63'}).click();await page.getByLabel('Filter timeline by entry type').selectOption('all');await expect(page.locator('.timeline-list')).toContainText('Re-runs, rejections, certificates, and gate notes will appear here')})
test('15.6 terminology_is_consistent',async({page})=>{await expect(page.getByText('Acceptance package',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Export acceptance package'}).first()).toBeVisible();await expect(page.getByRole('button',{name:'Import acceptance package'}).first()).toBeVisible()})
test('15.7 numbers_dates_and_units_are_consistent',async({page})=>{for(const text of await page.locator('.run-card-top div span').allTextContents())expect(text).toMatch(/^Submitted [A-Z][a-z]{2} \d{2}, \d{2}:\d{2} UTC$/);for(const text of await page.locator('time').allTextContents())expect(text).toMatch(/[A-Z][a-z]{2} \d{2}, \d{2}:\d{2} UTC/)})
test('15.8 success_messages_are_specific',async({page})=>{await page.getByRole('button',{name:'Add note'}).first().click();const d=page.getByRole('dialog',{name:'Add gate note'});await d.getByLabel('Text Required').fill('specific-message');await d.getByLabel('Category Required').selectOption('observation');await d.getByRole('button',{name:'Attach note'}).click();await expect(page.locator('.live-region')).toContainText('Note added to TST-301')})
